### ISSUE TITLE
when the width is in percent, it doens't work well

### ISSUE THREAD

**Issue by hyoseon-kim** [naver/egjs-flicking#113]
## Description
When the upper element of flicking elements has width in percent, the width of each sub-panel is sometimes genreated in decimal point.
In this case, the image of the former flicking area doesn't go over well. so some part of  the image remains like below example.
![image](https://user-images.githubusercontent.com/12962452/41526113-1edd4566-731e-11e8-8271-d3d6ab963953.png)
As you can see, the left side of that image remains. Follwing images will explain the reason.
![image](https://user-images.githubusercontent.com/12962452/41526145-3591ded4-731e-11e8-970a-453fd2d5be83.png)
When I try to flick to the left, that will be "translate(-734px, 0px)". but we expect "translate(-734.326px, 0px)". so we modified some of eg.js code, and it worked well.
1. modify flick-container's translate > from parseInt to parseFloat.
* _getUnitValue
`return (parseFloat(val, 10) || 0) + (String(val).match(rx) || "px");`

2. modify flick-panel's initial tranlate value > from percent to px (It was selected by "SUPPORT_TRANSFORM")
* _applyPanelsCss
`var coords = this._getDataByDirection([(this._conf.panel.size * i) + "px", 0]);`

please review this corrections.

**Comment by netil** [comment]
Hi @hyoseon-kim, thanks for the detailed report.
I'll try fix this on next release.

**Comment by netil** [comment]
The internal panel's dimension will be treated in float instead the integer.

And will be added new `useTranslate` option, which let opt how to move panels. 
- true: will use `transform:translate`
- false: will use top and left property
