### ISSUE TITLE
useTranslate, deceleration type wrongly applied

### ISSUE THREAD

**Issue by joohokwon** [naver/egjs-flicking#167]
## Description

useTranslate type is expected to be `boolean`, but `number`
deceleration type is applied with `string` type, but require `number` one

based on readme.md, applied options example

**Comment by younkue** [comment]
@joohokwon 
Thank you for your error report. I'll fix it right away and update it.

**Comment by younkue** [comment]
@joohokwon 
We've deployed version **`@egjs/react-flicking@0.0.4`**. Please check it.

**Comment by joohokwon** [comment]
@younkue confirmed. thanks!
