### ISSUE TITLE
How to use option gap?

### ISSUE THREAD

**Issue by joohokwon** [naver/egjs-flicking#175]
How can I set `gap` option like below on react-flicking module?

```ts
var iphone = new eg.Flicking(".iphone .panels", {
	circular: true,
	gap: 10,
});
```

I'd like to use as below. 
```ts
...
  <Flicking style={{ height: '100px' }} circular gap={10}>
    <div>some markups here!</div>
    <div>some markups here!</div>
    <div>some markups here!</div>
  </Flicking>
...
```

Thank you for your answer in advance.

**Comment by WoodNeck** [comment]
@joohokwon 
Unfortunately, react-flicking is currently unavailable in v3.0.0.
We're doing our best to provide wrapper for our new version in frameworks like React, Vue, Angular.
That's planned to deploy within June, so we hope you can wait for us a bit :)

**Comment by daybrush** [comment]
@joohokwon 

Beta version of react-flicking 3.0.0 has been deployed. Try it.

https://www.npmjs.com/package/@egjs/react-flicking
