### ISSUE TITLE
Improve .resize() to handle width and height

### ISSUE THREAD

**Issue by sculove** [naver/egjs-flicking#18]
@netil commented on [Mon Jan 16 2017](https://github.com/naver/egjs/issues/439)

## Description

Currently `.resize()`, only treat one sided dimension value.

ex.)
- when option.horizontal == true, resize only `width`
- when option.horizontal == false, resize only `height`

Improve `.resize()` to adjust width and height

---

@sculove commented on [Thu Aug 03 2017](https://github.com/naver/egjs/issues/439#issuecomment-319864952)

Issue moved to [naver/egjs-flicking #17](https://github.com/naver/egjs-flicking/issues/17) via [**ZenHub**](https://www.zenhub.com/)

**Comment by netil** [comment]
duplicated with #17
