### ISSUE TITLE
how about ``forEach`` polyfill?

### ISSUE THREAD

**Issue by sangmoon** [naver/egjs-flicking#22]
안녕하세요. 
ie8 에서 egjs-flicking을 사용하려고
hammerjs-compatible
hammer
의 dependency를 맞추니
``forEach`` 가 없어서 에러가 발생합니다.

polyfill 하니 기본적인 플리킹 기능이 ie8에서도 잘 작동하는데,
아예 flicker코드 내에 polyfill을 해서 ie8 하위 호환을 맞추는 건 어떠신가요? 
```js
if (typeof Array.prototype.forEach != 'function') {
    Array.prototype.forEach = function(callback, thisArg) {
        if (typeof this.length != 'number') return;
        if (typeof callback != 'function') return;

        if (typeof this == 'object') {
            for (var i = 0; i < this.length; i++) {
                if (i in this) {
                    callback.call(thisArg || this, this[i], i, this);
                } else {
                    return;
                }
            }
        }
    };
}
```
pr 받으시나요?

**Comment by netil** [comment]
@sangmoon thanks suggesting.
Officially, we're supporting from IE9+ and above and the support of old IE is not an official support. Is just giving an alternative for those environment.

If you need to use on that environment, adding polyfills is the right approach.

And we're always welcoming for the contribution. So, don't hesitate to do so.
