### ISSUE TITLE
vue-flicking Readme example

### ISSUE THREAD

**Issue by JunyeongYang** [naver/egjs-flicking#264]
Hi, I'm appreciated to your work.
  And I just founded tiny little typo in vue-flicking README.md.
  Please check this below,
  **before**
       :options="{ gap: 10, moveType='freeScroll' }"
  
  **after**
       :options="{ gap: 10, moveType:'freeScroll' }"

  I guess, '=' should be changed to ':'.

 Thank you and keep going for the world!

**Comment by JunyeongYang** [comment]
+ plus
Is there any examples for responsive web?
I have an issue, when I resize my browser.
 -> I followed 'AutoPlay example(vue)'
Thank you!

**Comment by WoodNeck** [comment]
Hey @JunyeongYang, thank you for your feedback!
Thanks for pointing out the typo. I'll fix README right away.

For responsive web, there's an `autoResize` option.
You can use it like this.
```js
:options="{ autoResize: true }"
```
It will perform resizing automatically when there's a window size update.

**Comment by JunyeongYang** [comment]
Yeah, I just founded in your [documents](https://naver.github.io/egjs-flicking/release/latest/doc/eg.Flicking.html#resize).

But I couldn't find set min-width of elements when the window has been resized.
Is there way to set their min-width?
Even If there isn't, It's just okay :) I'm still satisfying with autoResize option.

Thank you!

**Comment by WoodNeck** [comment]
We currently don't provide such an option. 
Using responsive CSS(like @media) with Flicking's `autoResize` option will work, so that can be a solution for a moment.
I know some other carousel components provide that option, so we'll discuss including that as our feature.
Anyway, thanks for suggesting!

**Comment by JunyeongYang** [comment]
No worries :)

I'm still going to watch your module for making an audio timeline.
See you again when I work on it.
 
Hope you have a great weekend!
