### ISSUE TITLE
Cannot set zIndex as 0 

### ISSUE THREAD

**Issue by carly-lee** [naver/egjs-flicking#267]
## Description
If I set `zIndex={0}`, it's still 2000. 

## Steps to check or reproduce
I think the issue is here. https://github.com/naver/egjs-flicking/blob/master/src/components/Viewport.ts#L877

**Comment by daybrush** [comment]
@carly-lee 
Thank you for reporting the issue.
This is a bug and I'll fix it.

**Comment by WoodNeck** [comment]
Fixed & merged in #268.
