### ISSUE TITLE
Can i stoppropagation when flicking is clicked? 

### ISSUE THREAD

**Issue by SoYoung210** [naver/egjs-flicking#271]
## Description
I use Flicking for modal.

I want.. 
* When overlay clicked -> modal off 
* modal clicked -> not off 

But when i click modal, it's off..... 
How can i stoppropagation when modal clicked? 
<img width="1015" alt="스크린샷 2019-08-05 오후 2 31 32" src="https://user-images.githubusercontent.com/18658235/62441099-dc8cd680-b78d-11e9-8a8f-6559a31705f1.png">

```tsx
  private offModal = (e: SyntheticEvent) => {

    this.setState({
      isModalVisible: false,
    });
  }

  private onClickNextContent = (e: SyntheticEvent) => {
    e.stopPropagation();
    this.flickingElement.next();
  }

      <div className={styles.overlay} onClick={this.offModal}>
        <div className={styles.prevButton} onClick={this.onClickPrevContent} />
        <Flicking
          ref={e => (this.flickingElement = e)}
          onSelect={(e: SelectEvent) => {
            console.log('e.axesEvent.currentTarget', e.axesEvent.currentTarget);
          }}
        >
          {DATA.map(data => (
            <ContentsModal
              key={data.speakerName}
              offModal={this.offModal}
              data={data}
            />
          ))}
        </Flicking>

        <div className={styles.nextButton} onClick={this.onClickNextContent} />
      </div>
```

I use ` e.stopPropagation();` in next, prev Button.

**Comment by daybrush** [comment]
@SoYoung210 
Hello. Thank you for reporting the issue.

When you click around the modal, you can use it as follows:

```js
// offModal

if (e.currentTarget !== e.target) {
    return;
}
this.setState({
    isModalVisible: false,
});
```

**Comment by SoYoung210** [comment]
Oops! Thanks for kind reply.

Basically, when swiping the screen from inside the modal, this works well. If i click the mouse inside the modal area and release the mouse outside the modal area, offModal will work. Is this part of the control possible with the Flicking function?

**Comment by daybrush** [comment]
@SoYoung210 

Then you can use the following events in Flicking as below.
```jsx
<Flicking onClick={e => { e. stopPropagation(); ]}}/>
```
