### ISSUE TITLE
supports 'hold' event

### ISSUE THREAD

**Issue by sculove** [naver/egjs-flicking#3]
user want to do something when touching on flicking.

```js
flikcking.on("hold", function(e) {
   // do it!
});
```

**Comment by netil** [comment]
Nope. It doesn't need to implement.
If want when is held during `flick` event, user can get that moment with [event.hodling](http://naver.github.io/egjs/latest/doc/eg.Flicking.html#event:flick) property value.

**Comment by sculove** [comment]
user want to do `first time` when touching on flicking.

example, I want to display `image` I handle it on `flick` event like this.
```js
flicking.on("flick", function(e) {
   if(e.holding) {
        if(image.style.display === "none") {
            image.style.display = "block";
        }
   }
);
```
I should check every time.

but, If flicking supports `hold` or `start` event I handle it like this.
```js
flicking.on("start", function(e) {
   image.style.display = "block";
});
```
It's so simple!!!

**Comment by netil** [comment]
Hmm.. I not fully convinced your opinion.
I agree that it'll be simple in that occasion, but in general, is that functionality really matter?
Having multiple custom events can be good, in terms of providing different option. But... I'm not fully persuade on that just "simple".
