### ISSUE TITLE
Nuxt.js production mode(nuxt build && nuxt start) is not working

### ISSUE THREAD

**Issue by james-song** [naver/egjs-flicking#300]
## Description
`nuxt dev` is working, but production mode(`nuxt build && nuxt start`) is not working 

## Steps to check or reproduce
same problem [ssr demo project](https://github.com/naver/egjs-flicking/tree/master/packages/vue-flicking/demo/ssr)

**Comment by WoodNeck** [comment]
Hello there, @james-song.

We've just found out that Flicking's `name` property is changed on Nuxt's production mode.
So, I made a commit that fixes that issue. (ce6cafefa7d7be8b49d21f7687ab05ff8d8869b6)
And also released a new version for @egjs/vue-flicking, which is v3.1.1

Thanks for reporting the issue. 😉

**Comment by james-song** [comment]
great! thank you for quickly action !
