### ISSUE TITLE
incorrect select event triggered in mobile mode

### ISSUE THREAD

**Issue by james-song** [naver/egjs-flicking#303]
## Description
In mobile mode, incorrect select event triggered when push the touch event and move to up or down edge (scroll up or down)

desktop mode nice work!

## Steps to check or reproduce

 https://naver.github.io/egjs-flicking/features/events.html

0. open the demo site for mobile mode in chrome.
1. click down any element
2. move down or up to out of edge 
3. click up

**Comment by WoodNeck** [comment]
Hello, @james-song. Good to see you again with another nice feedback.

I guess what you're saying, in short, is `select` event must be triggered only when mouse/touch pointer is on viewport area.
I think you're right, as it might trigger unnecessary `select` event.
But as this spec wasn't discussed yet, we'll discuss it first.
And if we conclude this issue as a bug, I'll fix it as soon as possible.

Thanks!
