### ISSUE TITLE
can i know next release schedule ?

### ISSUE THREAD

**Issue by james-song** [naver/egjs-flicking#308]
hello flicking team.
I just wondering about the next release schedule with fixes #305 
:)

**Comment by WoodNeck** [comment]
Hello, @james-song.
We can release it today I guess.
We were too kind of busy these days so just forgot to release it :)
I'll leave a comment here after releasing it.

**Comment by WoodNeck** [comment]
v3.4.2 is released and published to npm :)
Thanks for using @egjs/flicking!

**Comment by james-song** [comment]
great ! thank you so much !
