### ISSUE TITLE
Angular - Script error with circular option when OnPush mode is enabled

### ISSUE THREAD

**Issue by johnny-mh** [naver/egjs-flicking#311]
## Description
컴포넌트가 OnPush 모드일 때 circular옵션을 사용할 경우

패닝 과정에서 빈번한 스크립트 오류가 발생합니다.

![image](https://user-images.githubusercontent.com/1061205/67909980-782eb700-fbc4-11e9-942b-8cefbf633fbb.png)

## Steps to check or reproduce
https://angular-ngx-flicking-error.stackblitz.io

**Comment by WoodNeck** [comment]
Hello @johnny-mh :)
Looks like I can't see the page you provided due to the following error.
![image](https://user-images.githubusercontent.com/26213435/67912061-08bcc580-fbcc-11e9-921d-4fa966f8a6f7.png)
Can you please check that page settings for me? Thanks.

**Comment by johnny-mh** [comment]
https://stackblitz.com/edit/angular-ngx-flicking-error 이 주소로도 접속이 가능하실까요?

**Comment by WoodNeck** [comment]
It works fine! Thanks for checking. I'll check the issue and will leave the comment after.

> 넵 잘 접속됩니다! 확인해보고 댓글 다시 남기겠습니다 :)

**Comment by daybrush** [comment]
안녕하세요. @egjs/ngx-flicking@3.1.2-rc 버전을 배포했습니다. 문제가 없으면 3.1.2 버전으로 올리겠습니다.
또한 OnPush 모드에 대한 PR을 공유드립니다. 감사합니다.
> Hi ~ I have deployed @egjs/ngx-flicking@3.1.2-rc version. If there is no problem, we will deploy to 3.1.2. We also share a PR about OnPush mode.


https://github.com/naver/egjs-flicking/pull/312/files#diff-8d4e2c353cad97bd45ea8806e5c7b72d

**Comment by johnny-mh** [comment]
@daybrush 잘 됩니다. 고맙습니다!

**Comment by johnny-mh** [comment]
angular에서 DOM의 깊이가 깊어지고 async 파이프를 사용해 비동기로 렌더링을 반복하는 경우

ng-template으로 넣은 템플릿을 panel로 사용하지 못하는 경우가 있네요.

```html
    <div style="height:90px;">
      <ng-container *ngIf="getImages(item) as obj; else singleImg">
        <ngx-flicking>
          <ng-template>
            <div *ngFor="let img of obj?.list" style="display:block;width:90px;height:90px">
              <img class="img_thumb" [src]="img.url" />
            </div>
          </ng-template>
        </ngx-flicking>
      </ng-container>
```

![image](https://user-images.githubusercontent.com/1061205/68017028-26c41c00-fcd9-11e9-9067-65266972fb13.png)

**Comment by daybrush** [comment]
@johnny-mh 
안녕하세요. @egjs/ngx-flicking@3.1.2-rc2 버전을 배포했습니다. 확인해보시길 바랍니다.

**Comment by johnny-mh** [comment]
@daybrush 말씀주셨던대로 하니 패널로 인식이 잘 되네요.

다만 패널의 크기를 단말 크기에 따라 조절하는 부분이 있는데 이 때의 크기가 flicking쪽으로 전달되지 않는 현상이 있는데 이는 저희 쪽 코드를 더 봐야 하겠네요. 대응 고맙습니다.
