### ISSUE TITLE
버전 업 된 이후로 잘 작동되던게 안됩니다.

### ISSUE THREAD

**Issue by jxamen** [naver/egjs-flicking#33]
destroy() 한번 호출 한 이후에
새로 this.f1 = new eg.Flicking 객체 생성하면 연결이 안됩니다.

js로 html 그리고
다른 메뉴 선택시 destroy로 연결 끊고 html 비우고
새로운 메뉴의 html 다시 그리고
this.f1 = new eg.Flicking으로 다시 그린 부분 잡아서
컨트롤 하고 있었습니다.

// 해제
itemUtil.flickingDestroy();

// 화면 다시 그리기
	var index = 0;
	$.each(json_cate,function(k,v){
		itemUtil.drawItem(k, index++);
	});

// 다시 그린 화면 컨트롤 하기 위해 연결
itemUtil.getFlicking();

// destroy 호출 후 다시 잡으면
// transform: translate(200%, 0px); 이 값 설정도 안됨.

이렇게 동적으로 호출 할 때는 에러가 나는데
         getFlicking : function() {
		start = <?=$next_start?>;
		
		this.f1 = new eg.Flicking("#mflick", {
		  duration : 100,
		  hwAccelerable : true,			
		  threshold : 20, 
		  circular: true
		}).on({
		  flickEnd: function(e) {
			itemUtil.selectMenu();
			itemUtil.setHeight();
		  }
		});
	}
	, flickingDestroy : function() {
		//log('flickingDestroy');
		$('.ssMenu').hide();

		this.f1.currentIndex = 0;
		this.selectMenu();
		this.f1.destroy();
		
		$('#mflick').empty();
	}

페이지가 처음 로드 될 때는 에러가 안납니다. 
$(document).ready(function(){
	var index = 0;

	$.each(json_cate,function(k,v){
		itemUtil.drawItem(k, index++);
	});

	itemUtil.getFlicking();
	itemUtil.selectMenu();

	//console.log("mainList li img : " + $(".mainList li img").height());
});

에러-----------------------------------

Uncaught TypeError: Cannot read property 'destroy' of null
    at PanInput.connect (flicking.pkgd.min.js:1)
    at Axes.connect (flicking.pkgd.min.js:1)
    at Flicking._bindEvents (flicking.pkgd.min.js:1)
    at new Flicking (flicking.pkgd.min.js:1)

    at HTMLAnchorElement.dispatch (jquery-1.11.3.min.js:4)
    at HTMLAnchorElement.r.handle (jquery-1.11.3.min.js:4)

**Comment by netil** [comment]
@jxamen thanks for reporting.
It was caused by the major update of dependency modules which eg.Flicking has.

Released `2.0.3` fixing this issue. Just updating will work as before.

And in addition, will be appreciated english posting for the next time  :)
