### ISSUE TITLE
react-flicking 3.1.3 오류

### ISSUE THREAD

**Issue by subicura** [naver/egjs-flicking#330]
react-flicking 3.1.3에서 addPlugins 함수를 못찾는 에러가 발생합니다.

```
flicking.esm.js:239 Uncaught TypeError: this.addPlugins is not a function
    at Flicking.__proto.checkPlugins (flicking.esm.js:239)
    at Flicking.__proto.componentDidMount (flicking.esm.js:217)
    at commitLifeCycles (react-dom.development.js:22101)
    at commitLayoutEffects (react-dom.development.js:25344)
...(생략)
```

원인은 flicking 소스인것 같고

https://github.com/naver/egjs-flicking/commit/2286bb38859c68898a903efb7e1a8ff5c74d18e1

FLICKING_METHODS에서 addPlugins와 removePlugins가 제거되었는데 작성하신분 의도를 몰라서 수정하지는 않았습니다. 확인부탁드려요!

**Comment by WoodNeck** [comment]
Hello, @subicura!

As you mentioned, plugin related methods are removed on purpose.
But there was a mistake that still using removed methods on the inside.

I've just released react-flicking@3.1.4 with the fix, so check that, please! 

We're really sorry for the inconvenience.
Thanks.

---

안녕하세요.
해당 메소드들은 저희가 처음 react-flicking 3.0.0버젼을 만들 때 실수로 삭제되지 않은 메소드들입니다. 최근에 메소드 타입들을 재확인하면서 발견하게 되었네요.

다만, 실수로 리액트에서만 내부적으로 자기 자신의 addPlugins 및 removedPlugins를 여전히 사용하고 있었네요. 때문에 이를 수정하는 버젼(3.1.4)을 배포했습니다, 확인 부탁드리겠습니다.

감사합니다.

**Comment by WoodNeck** [comment]
I'll close this issue, for now.
Feel free to reopen it whenever you like :)

**Comment by subicura** [comment]
수정 확인했습니다. 감사합니다. :+1:
