### ISSUE TITLE
How do I using prev and next in Vue.js?

### ISSUE THREAD

**Issue by antony989** [naver/egjs-flicking#331]
How do I using prev and next in Vue.js??
i'm Using now vue.js and quasar.js

I don't understand the document well.
https://naver.github.io/egjs-flicking/projects/grafolio.html

how to use moveto or next&prev function in Vue.js? show me exmple plz

**Comment by WoodNeck** [comment]
Hello, @antony989!

You can call methods in Vue.js by setting a reference to the Flicking component.

```vue
<template>
  <div>
    <Flicking
      ref="flick">
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
    </Flicking>
    <button @click="click" />
  </div>
</template>
<script>
export default {
  methods: {
    click() {
      // You can call it like this
      this.$refs.flick.next();
    }
  }
}
</script>
```

You can also see this [demo](https://codesandbox.io/s/codesandbox-nuxt-9rfg9). It is made with Nuxt.js but basically it's same.
See where it using ref with the name "flicking3" :)

Thanks.

**Comment by aizeek1** [comment]
hi this is not working for me can you assist
