### ISSUE TITLE
How do I pause when flying over the carousel?

### ISSUE THREAD

**Issue by GitHubish** [naver/egjs-flicking#337]
I am trying to pause the scrolling of the carousel when the user hovers over the carousel with his mouse. I think this feature does not exist / is not possible today. For information I use ngx-flicking and the AutoPlay plugin.

Thanks

**Comment by WoodNeck** [comment]
Hello @GitHubish!
As you said, such a feature is not supported by the current AutoPlay plugin.

For now, I think the fastest way you can do that is by extending the AutoPlay class.

```ts
// I suppose you're using typescript, as you're using ngx-flicking
import { AutoPlay } from "@egjs/flicking-plugins";

class PauseOnHoverAutoPlay extends AutoPlay {
  public init(flicking: any): void {
    super.init(flicking);
    const wrapper = flicking.getElement();

    wrapper.addEventListener("mouseenter", (this as any).onStop);
    wrapper.addEventListener("mouseleave", () => {
      (this as any).onPlay({ currentTarget: flicking });
    });
  }
}
```

I've tested the above code. Change AutoPlay plugin you're using into that new class and it will work.
I know that looks kinda messy, but this will be the fastest way to add that feature into your code.

I'll add "pause on hover" as a new feature candidate on the flicking-plugins repository.

See [AutoPlay source](https://github.com/naver/egjs-flicking-plugins/blob/master/src/AutoPlay.ts) for more info.
Thanks.

**Comment by WoodNeck** [comment]
It's quite late to notice you, but we've added an option for this on https://github.com/naver/egjs-flicking-plugins/issues/10
Now you can use it like
```js
new AutoPlay({
  stopOnHover: true
});
```
I'll close this issue for now, feel free to reopen it whenever you want.

**Comment by GitHubish** [comment]
@WoodNeck The latest version does not seem to be available for Angular. The option is therefore not available. When do you plan to release it? Thank you

**Comment by WoodNeck** [comment]
@GitHubish 
We don't release plugin for each frameworks, you should update he version of flicking-plugins only.
