### ISSUE TITLE
Performance issue when using the vue-flicking

### ISSUE THREAD

**Issue by teamboot88** [naver/egjs-flicking#338]
## Description

안녕하세요.
vue-flicking 적용 중 성능 이슈가 있어, 혹시 개선이 가능한 부분인지 문의드립니다.

현재 총 7~8개의 패널을 사용하고 있습니다.
그러나 사용자에게 노출되지 않는 패널은, 최상위 레벨에서 분기처리하여 
최대한 1개의 패널만 렌더링 하도록 하였습니다.

```html
<flicking id="contentFlicker" ref="contentFlicker" class="content-flicking"
                  :options="{defaultIndex: initialIndex, zIndex: 0, hanger: 0, anchor: 0, threshold: 50, circular: false, collectStatistics: false, zIndex: 0}" tag="div"
                  @move-start="e => {this.contentMoveStart(e);}"
                  @move-end="e => {this.contentMoveEnd(e);}">

        <div v-for="(tab, tabIndex) in tabs" :key="tab.type"  class="panel">
                <div v-if="tab.visible">
                        ..
                </div>
        </div>

</flicking
```

위와 같이 실질적으로 한 개의 패널을 사용하고 있습니다. 이슈는,
**현재 패널 내에 수십~수백개 정도의 많은 수의 DOM이 존재하는 경우 (다른 패널은 비어 있음)** 
화면에 터치를 할 경우 (클릭 후 순간적으로 손가락을 떼더라도)
hold-start > hold-end > select 이벤트가 완료되기까지 수백ms가 소요되며
터치스크롤 역시 다소간(약 100ms)의 딜레이 후, 스크롤이 시작되는 등
프레임 저하가 발생하고 있습니다.

하지만 완전히 동일한 콘텐츠를 Flicking만 제거 후 테스트시에는 
반응속도가 매우 빠른 것을 확인했습니다.
동일한 콘텐츠에 대하여 플리킹을 적용한 것과 적용하지 않은 것의 성능 차이가 다소 발생하는데요, 
성능 저하는 어쩔 수 없는 것인지, 성능 저하를 개선할 방법이 있을지 문의드립니다.

감사합니다.

**Comment by WoodNeck** [comment]
Hello, @teamboot88!
There're some options that we're providing to settle the performance issue, which is also applicable for the vue-flicking too.
You can see it in the last section of the [Infinite Flicking](https://naver.github.io/egjs-flicking/features/infiniteflicking.html) demo.
For the `isEqualSize` and `isContantSize` option, be sure that they fit your UI.
See [FlickingOptions](https://naver.github.io/egjs-flicking/release/latest/doc/eg.Flicking.html#.FlickingOptions) for more info.
Thanks!

---

안녕하세요.
말씀하신 퍼포먼스 이슈를 대응하기 위해서 Flicking에서는 몇 가지 옵션을 제공하고 있습니다.
[Infinite Flicking](https://naver.github.io/egjs-flicking/features/infiniteflicking.html)의 제일 아래쪽 데모를 보시면, 플리킹에서는 3가지 옵션(renderOnlyVisible, isEqualSize, isConstantSize)을 통해 이를 지원하는 것을 확인해보실 수 있습니다.
주의하실 점은, `isEqualSize`와 `isConstantSize` 옵션의 경우 사용하실 UI에 따라 적용이 불가능할 수도 있다는 점입니다.
[FlickingOptions](https://naver.github.io/egjs-flicking/release/latest/doc/eg.Flicking.html#.FlickingOptions) API 페이지를 참조해주세요.
감사합니다.

**Comment by teamboot88** [comment]
The performance degradation was caused by the overlapping use of Flicking and PullToRefresh.
IsEqualSize, isConstantSize, or renderOnlyVisible has not worked.
I wanted to create a rich web, but eventually I decided to remove the PullToREefresh feature.
Thank you
---


안녕하세요.
우선 답변 감사합니다.

결론부터 말씀드리면 
제가 Flicking 패널에 추가로 PullToRefresh 기능을 사용했기 때문에
급격하게 성능 저하가 발생했습니다.
https://www.npmjs.com/package/pulltorefreshjs

isEqualSize나 isConstantSize, renderOnlyVisible는 모두 시도해보았으나
차이가 없었습니다.

PullToRefresh 로 인해서 상하좌우 모두 이동이 가능하게 되면서
급격하게 프레임 저하가 일어난 것 같습니다.
rich한 웹을 만들고자 했으나 성능의 벽에 부딪혀.. PullToRefresh 기능은 제거하기로 했습니다.

감사합니다.

**Comment by WoodNeck** [comment]
I've just checked it and looks like the performance issue is derived from the "PullToRefresh.js".
They're changing the element's `min-height` style, which can be very inadequate for your situation.
I think Flicking's `renderOnlyVisible` can ease a bit of that performance issue, but as you're saying that it still produces the issue, I guess you can instead use any other library that uses `transform` attribute(I don't know whether it exists, though).

Thanks for reporting the issue!

**Comment by teamboot88** [comment]
감사합니다 ^^
