### ISSUE TITLE
Carousel items moving on destroy

### ISSUE THREAD

**Issue by larsvanhilten** [naver/egjs-flicking#341]
## Description
When switching to another page, the carousel is destroyed. This causes the carousel items to move from next to each other to underneath each other.
Because there is a sliding animation on the page transition, the user is able to see the carousel items underneath each other, instead of next to each other, for a brief time.

## Steps to check or reproduce (Angular)
1. Create carousel with multiple items
2. Add page animation (e.g. slide in animation)
3. Go to next page
4. See carousel items underneath each other during animation

I noticed  that #233 might be a potential solution for this problem, however there is no clear documentation on how to use it?

**Comment by WoodNeck** [comment]
Hello! @larsvanhilten 
That looks kind of an issue I've also seen while I'm working on vue-flicking's demo.
You're right that #233 is the fix for it, but it looks like there's no guide on how to use it like you said.
You can use it like:
```js
flicking.destroy({ preserveUI: true });
```
See https://github.com/naver/egjs-flicking/blob/master/packages/vue-flicking/src/Flicking.ts#L70 for actual usage.
I'll add the guide on our API docs page :)
Thanks!

**Comment by larsvanhilten** [comment]
Thanks for the help!

How would one reach the `destroy` function in Angular though? The `NgxFlickingComponent` does not seem to contain the `destroy` function? 

I'm accessing the carousel like this:  `@ViewChild(NgxFlickingComponent, { static: false }) flick: NgxFlickingComponent;`.

**Comment by WoodNeck** [comment]
There's a native(a.k.a. without framework) Flicking inside the component with name "flicking".
So if you're accessing NgxFlickingComponent with the name "flick", you can use it like this.
```js
flick.flicking.destroy({ preserveUI: true });
```

**Comment by larsvanhilten** [comment]
Ah, it appears it is on the `NgxFlickingComponent`, I just had to update the package 🙄: `this.flick.destroy({ preserveUI: true });`

**Comment by WoodNeck** [comment]
Oh, does it make issue settled?

**Comment by larsvanhilten** [comment]
Yes, thanks for the help 👍
