### ISSUE TITLE
How to using multiple instances of flicking?

### ISSUE THREAD

**Issue by nuno360** [naver/egjs-flicking#345]
I would like to use multiple instances of flicking. This is possible with egjs-flicking? I don't found it on documentation.

**Comment by WoodNeck** [comment]
Hello, @nuno360!
Which do you mean, nested type or just multiple instances on the page?
Flicking currently doesn't support nested Flicking due to the dependency issue.
But putting multiple of them on the page is just fine :)

**Comment by nuno360** [comment]
Hello, @WoodNeck!

Thanks for reply. What I want is a way to set flicking one time and that it works for all ".js-carousel", this is possible or I need to set a new instance of flicking for each carousel?

**Comment by WoodNeck** [comment]
Well, unfortunately, you should make each flicking instance for each carousel as a state should be managed separately for each carousel.
However, you can use the same class name for each carousel wrappers.
Here's the way:

```js
const flickings = document.querySelectorAll(".js-carousel").map(element => {
  return new Flicking(element, options);
});
```

**Comment by nuno360** [comment]
@WoodNeck thanks!
