### ISSUE TITLE
How can I make the panels move on only one axis? (GIF attached)

### ISSUE THREAD

**Issue by teamboot88** [naver/egjs-flicking#346]
## Description
Hello? First of all, thank you for developing a great library. I'm using it well. (@egjs/vue-flicking)

If the panel is moving in one of the longitudinal and transverse directions, it can also be moved to the other axis. And this is causing the error log below.

```
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, 
for example because scrolling is in progress and cannot be interrupted.
```

this is my options
```javascript
zIndex: 0, hanger: 0, anchor: 0, threshold: 55, circular: false, 
collectStatistics: false, autoResize: true
```

I'd appreciate it if you could tell me how to prevent it.
Thank you

## Steps to check or reproduce
You can reproduct it in my site. (@mobile environment)
https://trol.kr

![ezgif-4-05d5ba97bd4d](https://user-images.githubusercontent.com/54491002/78023121-0e902000-7391-11ea-8d35-c59347036276.gif)

---

안녕하세요
현재 vue-flicking 을 웹사이트 메인에 적용해 잘 사용하고 있습니다. 감사합니다.
(모바일웹 환경에서만 발생합니다.)

패널을 가로로 배치하여 (default) 사용하고 있는데요,
컨텐츠를 세로 스크롤 하다가, 도중에 좌우로 크게 움직이면 
좌우로도 움직임이 가능합니다. 그 때 위에 말씀드린 console 로그도 찍히고요.
이 현상을 방지할 수 있는 방법이 있을까요?

네이버 모웹 메인도 egjs-flicking 을 사용중인 것으로 알고 있습니다.
네이버 메인에서는 위와 같은 현상은 발생하지 않아 어떻게 처리가 된 것인지 궁금합니다.

+ 추가질문
컨텐츠 내용이 rich한 경우,
사용자가 터치를 시작해 최초 세로 스크롤되기까지 미세한 딜레이가 생기고 있습니다.
그래서 화면이 사용자의 손을 못 따라가고 버벅이면서 따라옵니다.
손을 놀리지 않고 계속 스크롤 액션을 하면 괜찮은데, 
화면에서 몇 초 손을 떼었다가 스크롤하려고 하면 발생합니다.
동일한 페이지가 플리킹 적용된 곳과 적용 안된 곳이 있는데요,
두 화면에서 비교 가능하십니다.

1) 플리킹 적용
https://trol.kr/posts/43

2) 플리킹 미적용
https://trol.kr/categories/25/posts/43

재현하기 어려우실 수도 있습니다.. (미세합니다. 그러나 신경이 쓰여서요..)
저의 근거없는 추측으로는 현재 가로세로 스크롤이 모두 가능하기 때문에
어느 쪽으로 플리킹을 시켜야 하는지 결정을 못해서 딜레이가 생기지 않나 싶은데..
순전히 추측입니다
도움을 주시면 감사하겠습니다. _ _)

**Comment by WoodNeck** [comment]
Hello, @teamboot88!
Actually, Naver's main page is using an older version of Flicking(2.x) and it actually works quite differently from Flicking 3.x
Flicking 3.x currently doesn't provide such an option.
But preventing horizontal Flicking when vertical scrolled is simple with one additional flag.

```js
let scrolled = false;

// You can this in vue-flicking with @hold-start
flicking.on("holdStart", e => {
  scrolled = false;
});

// Same, @move-start
flicking.on("moveStart", e => {
   if (scrolled) {
      e.stop();
   }
});

window.addEventListener("scroll", () => {
   scrolled = true;
});
```

Check this codepen: https://codepen.io/woodneck/pen/ExjMoON

But this can't prevent console's error log, as a dependency of Flicking is not checking `cancelable` property before it cancels. So I'll make a quick PR to it, so it can be fixed on next version.

And for the additional question, sorry but I can't reproduce it (tested on Android Chrome).
Can you give me more info about how to reproduce it?

Thanks :)

**Comment by teamboot88** [comment]
I did what you told me and it worked out.
Thank you :)

**Comment by WoodNeck** [comment]
I'm glad that worked :)
We'll also fix Flicking to work in that way by default.
I'll close this issue for now, feel free to reopen it whenever needed.
