### ISSUE TITLE
Item resize makes other items to overlap

### ISSUE THREAD

**Issue by tiagocorreiaalmeida** [naver/egjs-flicking#350]
## Description
Im trying to update the active item dimensions, im doing it by keeping track of the active item using the onMoveEnd event and from there I pick the current index, I noticed that if I increase the item dimensions some of the other items end up overlaping the active one.

## Steps to check or reproduce
I used the base codebox to make a reproducible example

https://codesandbox.io/s/react-flicking-examples-gjicc
https://gjicc.csb.app/

**Comment by WoodNeck** [comment]
Hello @tiagocorreiaalmeida! :)
You can do that by flipping order of `setState` and `resize` at onMoveEnd.

```diff
- e.currentTarget.resize();
- this.setState(() => ({ activeItem: e.index }));
+ this.setState(() => ({ activeItem: e.index }));
+ e.currentTarget.resize();
```

This is because you have to change size before resizing.

**Comment by tiagocorreiaalmeida** [comment]
It worked like charme, somehow I had it before but removed it when I was testing and forgot to place it back in, thanks :) 
One last question if you dont mind, im trying to animate the width transition and im not sure if that's possible currently because if I resize right away the animation is still in progress so the item size won't be final, if I resize only after the animation timing it loses the animation im trying to present, if you can give a last look to the sandbox, thanks

**Comment by WoodNeck** [comment]
Sorry but that kind of UX is really hard to implement in the current Flicking structure.
It is mostly due to the fact that Flicking is rendering panels with CSS `position: absolute;` and `left` values.
I've tried, but was really really tricky.
Sorry that I can't help :(

**Comment by tiagocorreiaalmeida** [comment]
Dont worry, most of the solutions I searched for seem to suffer from the same "problem", the package is awesome you can't fill every gap that exist there, thanks once again :)
