### ISSUE TITLE
(a tag) link questions

### ISSUE THREAD

**Issue by kurosaki-ken** [naver/egjs-flicking#353]
I am using nuxt and egjs-flicking together.
When swiping with the mouse nuxt-link action is executed.
I only want it to work when clicked directly.

I know that the problem is not a module problem.
Can you suggest a solution?

Sorry for the poor quality of the question.

**Comment by WoodNeck** [comment]
Hello @kurosaki-ken!
I've tested your case on our codesandbox.
Here's my attempt on it: https://codesandbox.io/s/egjsvue-flicking-nuxt-examples-p72nw?file=/pages/features/AnchorClick.vue
As the page is not listed on the main page(index.vue), you can see the result at: https://p72nw.sse.codesandbox.io/features/AnchorClick

Basically I've checked whether to prevent or not "click" event on anchor(which will act the same to `nuxt-link` I guess), by checking Flicking is scrolled least once by using event `moveStart` and `moveEnd`.
You can see the actual code at the link above, so go check it and tell me whether it works on your case :)

**Comment by kurosaki-ken** [comment]
thank you so much.
sovled my issue.
`            <flicking
              ref="flicker"
              class="flicking flicking1"
              @move-start="move_start"
              @move-end="move_end"
              @hold-start="drag_start"
              @hold-end="drag_stop"
`
...
`              <v-card
                v-for="item in default_anime"
                :key="item.id"
                @dragstart="is_dragged"
                @click="handle_click($event,item.slug)"`

`
    move_start: function(e) {
      this.moved = true;
    },
    move_end: function(e) {
      setTimeout(function () {
        this.moved = false;
      }.bind(this),500)
    },
    is_dragged: function(e){
      e.preventDefault();
    },
    drag_start: function(e) {
      this.dragged = true
    },
    drag_stop: function(e){
      this.dragged = false
    },
    handle_click: function(e,link) {
      if (this.moved) {
        e.preventDefault();
      } else {
        if(!this.moved){
          if(!this.dragged){
            this.$router.push(`/${link}`)
          }
        }
      }
    }
`

**Comment by WoodNeck** [comment]
That's good to know :)
I'll close the issue as you've solved it. Feel free to reopen it whenever it's needed.
