### ISSUE TITLE
React.StrictMode is breaking the react-flicking component

### ISSUE THREAD

**Issue by ihatem** [naver/egjs-flicking#354]
## Description

I was testing the react-flicking component on CodeSandbox it worked perfectly until I switched to my local react project. I tried several debugs until I found that `React.StrictMode` which is wrapped about my app component (automatically set with the new `create-react-app` is causing all that. 

### Working demo without `StrictMode`
- [CodeSandbox](https://codesandbox.io/s/flicking-no-strictmode-6e10g)
### Not working demo with `StrictMode` 
- [CodeSandbox](https://codesandbox.io/s/flicking-strictmode-y54n9)

**Comment by daybrush** [comment]
@ihatem 

Oh, we will fix it and release it again.

**Comment by daybrush** [comment]
@ihatem 

`@egjs/react-flicking` 3.2.2 is released. Check it again.

Thank you :)
