### ISSUE TITLE
flicking.prev() not work when click first time

### ISSUE THREAD

**Issue by borm** [naver/egjs-flicking#360]
## Description
subj

## Steps to check or reproduce
Go to link
https://codesandbox.io/s/react-flicking-examples-6ft8h?file=/src/features/Progress.tsx:480-498
Scroll Flicking by touch to last slide
Click prev button

**Comment by WoodNeck** [comment]
Hello :)
That's actually because the last panel(the blue one) is selected when you slide to the last.
This will work:
```jsx
<button
  onClick={() => {
    if (this.flicking.isPlaying()) return;
    const visiblePanels = this.flicking.getVisiblePanels();
    const firstVisiblePanel = visiblePanels[0];

    if (firstVisiblePanel.getProgress() < 0) {
      firstVisiblePanel.focus(300);
    } else {
      const prevPanel = firstVisiblePanel.prev();
      prevPanel && prevPanel.focus(300);
    }
  }}
>
```

**Comment by borm** [comment]
Hello ;))), 
As always thanks for the quick reply

Can u explain it please?)
```
if (firstVisiblePanel.getProgress() < 0) {
    firstVisiblePanel.focus(300);
}
```

because how i can see it`s also work only with bellow fragment
```
const prevPanel = firstVisiblePanel.prev();
prevPanel && prevPanel.focus(300);
```

**Comment by WoodNeck** [comment]
That prevents going to the orange panel when you're on the last panel.
With it, Flicking will move to the yellow panel because it's not fully visible.
I think you can choose what you prefer :)

**Comment by borm** [comment]
Ah, okay, thx u so much,
i think u should add this improvement to next release version,
thx u again and have a nice day;)
