### ISSUE TITLE
React, Question, how i can do all panels same height by higher

### ISSUE THREAD

**Issue by borm** [naver/egjs-flicking#361]
## Description
As example, we have multi panels with some dynamic text on each,
i need have all panels same height

## Steps to check or reproduce
https://codesandbox.io/s/react-flicking-examples-2pq0w

**ER:**
![image](https://user-images.githubusercontent.com/4027842/89521322-57992a80-d7f0-11ea-92c3-1175cee46094.png)

**Comment by WoodNeck** [comment]
Hello again :)
Well, this is the only way Flicking can do that. Assuming panels won't be re-rendered.
```js
  public componentDidMount() {
    this.flicking.getAllPanels().forEach(panel => {
      panel.update(el => {
        el.style.height = "100%";
      })
    });
  }
```

Note:
- Please don't set Flicking wrapper's height to fixed px.
- As it set the panel's height to "100%", panels will set their height to 0 when it is re-rendered, making it invisible.
To prevent it, please set all panel's height style to "" before re-rendering.
I think you can use `componentWillUpdate` for that.
```js
  public componentWillUpdate() {
    this.flicking.getAllPanels().forEach(panel => {
      panel.update(el => {
        el.style.height = "";
      })
    });
  }
```
