### ISSUE TITLE
eg Flicking을 2.5.1버전과 3.x.x버전을 같이 쓸 때

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#362]
이전 문의 드린것 과 같이 겉의 판을 알려주신대로 2.5.1버전을 네임스페이스 바꿔서 쓰고 안의 컨텐츠들 플리킹은 egjs최신버전을 따로 쓰고 있습니다. 버전을 따로쓰다보니 안의 컨텐츠(3.x.x)플리킹 할때 자꾸 판플리킹(2.5.1)버전도 함께 움직이게 되는데요
이를 해결하고자
겉의 판플리킹 변수 var wPanflick 을 전역변수로 두고 안의 컨텐츠(3.x.x) 버전이 플리킹이 발생할때 저 전역변수를 통해 
disableInput()을 호출하여 같이 플리킹이 되는 것을 막고자 합니다.

만약 가능한 방법이라면 안의 컨텐츠를 어떤 시점에 disableInput()을 호출해주고 어떤 시점에 enableInput()을 주어 풀어 주는 것이 맞을까요?

생각같아서는 holdStart 시점에 disableInput을 하고 moveEnd 시점에 enableInput을 해야 하나 생각하고 있는데요.

3.x.x버전과 2.5.1버전을 동시에 사용하기 위해서 어떻게 해야 하는지 혹은 관련 샘플이 있을까요?

_Originally posted by @changdongchun in https://github.com/naver/egjs-flicking/issues/347#issuecomment-671188297_

**Comment by WoodNeck** [comment]
안녕하세요, 혹시 말씀해주신 disableInput & enableInput 방법 시도해보셨나요?
저희가 의존성 관련 문제가 있어 아직 중첩된 플리킹에 대한 예시는 공식적으로 지원하고 있지는 않습니다.
다른 라이브러리의 경우 해당 기능을 mouse/touch이벤트에 별도의 프로퍼티를 추가해서 해당 프로퍼티 존재 여부를 통해 안쪽 캐로셀이 동작했는지를 판별하는 방식을 사용하는데요, 저희도 해당 기능을 준비하고 있습니다.

**Comment by changdongchun** [comment]
우선 holdStart 시점에 겉의 플리킹에 disableInput을 하고 moveEnd 시점에 enableInput을 넣어보니 판안의 내용 컨텐츠들 플리킹 시 판도 함께 플리킹이 되는 현상은 사라짐을 확인 하였습니다.
플리킹 시 최초 발생하는 이벤트가 holdStart 제일 마지막이 moveEnd라고 생각하면 될까요?

**Comment by WoodNeck** [comment]
넵 말씀하신 내용이 맞습니다.
다만 주의하실 점은, `moveEnd` 이벤트의 경우 애니메이션 종료 시점에 트리거되므로 패널이 움직이는 도중에는 외부 패널을 움직이는게 불가능하게 됩니다.
입력을 뗀 순간 외부 패널을 움직일 수 있게 하시려면 `holdEnd`를 이용해보시는 것이 좋을 것 같습니다.
