### ISSUE TITLE
egFlicking내 구글 소스 용도는?

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#363]
## Steps to check or reproduce

egFlicking내 구글 소스가 있던데 이 부분 하는 역할이 어떻게 되는건가요?

**Comment by WoodNeck** [comment]
안녕하세요.
Google Analytics 적용을 위한 코드로, [README](https://github.com/naver/egjs-flicking/blob/master/README_KR.md#%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%A7%80%ED%91%9C%EC%9D%98-%EC%88%98%EC%A7%91)에 있는 내용을 참조해주세요
