### ISSUE TITLE
플러그인 AutoPlay 에서 롤링을 일시 멈춤 할 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#366]
## Steps to check or reproduce

```js
var flicking = new eg.Flicking(".flicking", {
    circular: true,
    gap: 10,
    duration: 500,
});

flicking.addPlugins(new eg.Flicking.plugins.AutoPlay(2000, "NEXT"));
```

라고 했을 때 AutoPlay를 일시 멈춤 할 수 있는 기능이 있을까요?

**Comment by WoodNeck** [comment]
안녕하세요.
네, 해당 인터페이스가 외부로 노출되어있진 않긴 하지만 호출하셔도 기능적으로는 문제 없을 것으로 보입니다.
```js
const autoplay = new eg.Flicking.plugins.AutoPlay(2000, "NEXT");
flicking.addPlugins(autoplay);

// When pause is needed
autoplay.onStop();
```

이후 resume을 위해서는 play를 호출해주시면 될 것 같네요.
```js
autoplay.play(flicking);
```

다만, 해당 기능을 현재 명시적으로 지원하지 않기 때문에, 이후에 인터페이스 변경 가능성이 있음은 유의해주시기 바랍니다.
플러그인 기능 업데이트시에 말씀해주신 기능 참고해서 개발하도록 하겠습니다.
