### ISSUE TITLE
lazyload적용시 dummy dom문제

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#369]
## Description

lazyload적용 시 dummy html파일이 생겨 같은 파일을 중복해서 load혹은 이미 불러온 파일인데 여전히 origin이미지 이전 빈 이미지일 경우가 있는데요 eg.flicking에 lazy load를 적용하는 레퍼런스가 혹시 있을까요?

**Comment by WoodNeck** [comment]
안녕하세요.
아직 관련 데모/레퍼런스는 없습니다.
원본 및 클론된 이미지를 동시에 업데이트 하기 위해서, FlickingPanel의 `update`메소드를 사용해서 업데이트 하시면 될 것 같은데요, 테스트해보시고 잘 안된다면 Codepen 등을 이용한 예제를 같이 첨부해주시면 가이드해드리겠습니다.
https://naver.github.io/egjs-flicking/release/latest/doc/eg.Flicking.html#.FlickingPanel

**Comment by changdongchun** [comment]
항상 빠른 답변 감사합니다. update 를 활용해서 처리 해보도록 하겠습니다.

**Comment by WoodNeck** [comment]
넵~^^ 이슈는 닫아두도록 하겠습니다. 필요시 다시 오픈해주세요.
