### ISSUE TITLE
Not working properly on Android 4.1.1 (Galaxy S3)

### ISSUE THREAD

**Issue by incleaf** [naver/egjs-flicking#37]
## Description
![](https://thumbs.gfycat.com/UniformFirstIzuthrush-size_restricted.gif)
Have tested on Android 4.1.1 (Galaxy S3)

## Steps to check or reproduce
I just bumped up to `2.0.3`. It works just like as vertical/horizontal scroll. It has been working well in `1.5.0`.

**Comment by netil** [comment]
thanks @incleaf for the report.
I'll check for that.

**Comment by netil** [comment]
I did test with real devices. I couldn't test on that env. exactly, but I think with the similar devices will be enough for check.

From the left to right, Galaxy S3 4.0.4 and Galaxy Note1 4.1.2 respectively.
![galaxy](https://user-images.githubusercontent.com/2178435/30147315-98ab7ac8-93d8-11e7-8b4b-2882ea63f253.gif)

I can't see similar behavior as yours. If you can reproduce the bug, please let us know.

**Comment by incleaf** [comment]
Thank you for testing. The virtual device is using AOSP browser which is not shipped in actual devices, so it seems like not a real world problem. I'll reopen this issue if I reproduce it in actual devices. Thank you.
