### ISSUE TITLE
화면 스크롤 시 IOS에서 화면 깜빡임

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#370]
## Description

[IOS_11.zip](https://github.com/naver/egjs-flicking/files/5185394/IOS_11.zip)

개편 중인 아이패드 미니 IOS 11.1.2에서 스크로를 내리면 화면내 배너 이미지들이 깜빡하는 현상이 있습니다.
기존 사이트(개편 전,JINDO)에서는 그런 현상이 없었는데요
혹시 IOS 11.1.2와 관련되어 리포팅된 버그나 방어코드같은 것들이 있을까요?

**Comment by WoodNeck** [comment]
안녕하세요, 관련 버그가 리포팅된 기록은 없는데요.
비슷한 사례로는 이미지가 캐시되지 않은 상태에서 엘리먼트가 삭제되었다 다시 추가될 경우 비슷한 현상이 나타나긴 하는데요
이 경우 직접적으로 해당 페이지를 저희쪽에서 테스트해봐야 정확히 확인 가능할 것 같습니다.
