### ISSUE TITLE
3판플리킹 구조에서 판데이터를 저장하는방법

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#371]
## Description

10개이상의 판플리킹을 3판구조로 개발하였는데요
3판을 순환시키면서 각 판에 맞는 내용을 넣다보니 dom구조는 10개판을 순환시킬때보다 가벼운데
메뉴 클릭시마다 불러오는 시간이 걸리고 있어서요
이미 불러온 메뉴 정보라면 쿠키시간내에서는 불러오지 않도록 하는 방법이 있을까요?

**Comment by WoodNeck** [comment]
안녕하세요.
어떤걸 로드하시는건지 잘 모르겠는데요, ajax 요청의 경우 캐시가 되어있다면 해당 캐시를 불러오는게 기본 동작일 것 같은데 어떤 경우에 해당 콘텐츠를 다시 요청하고 있는건지 구체적인 사례를 봐야 알 것 같습니다.
만약 내부 마크업 관련이시라면 현재 패널 내용물 엘리먼트를 부모 엘리먼트로부터 remove하시되
레퍼런스는 제거하지 않고 메모리에 남겨놓으신 다음 필요할때 재사용해보시면 어떨까 하네요.
구체적인 예시가 있다면 답변드리기 더 용이할 것 같습니다.

**Comment by changdongchun** [comment]
//판플리킹 구성
function setWelcomePanFlick() {
    //웰컴 판 플리킹(2.5.1)
    wPanFlick = new pan.Flicking("#wPanFlick", {
        prefix: "welcome",
        circular: true,
        adaptiveHeight: true,
        threshold: 60,
        thresholdAngle: 25,
        duration: 200
    }).on({
        flickEnd: function (e) {
            serFlickContents(e);
        }
    });
}

//플리킹 종료 후 실행
function serFlickContents(e) {
    if (isMoveEvent) {
        isMoveEvent = false;
        $("#loadingdiv").css("display", "none");
        return;
    }
    partial_loading_bottom = false;

    //판 정보 셋팅
    var currPan = e.no;
    var nextPan = currPan >= 2 ? 0 : currPan + 1;
    var prevPan = currPan == 0 ? 2 : currPan - 1;

    //메뉴 정보 셋팅
    var currMenu = Number($('#pan' + e.no).attr('data-menu-idx'));
    var nextMenu = currMenu >= welcomeMenuCount ? 0 : currMenu + 1;
    var prevMenu = currMenu == 0 ? welcomeMenuCount : currMenu - 1;

    var next = { "menu": welcomeMenu[nextMenu].MENU_NAME, "url": welcomeMenu[nextMenu].URL, "idx": nextMenu, "panId": "#pan" + nextPan };
    var prev = { "menu": welcomeMenu[prevMenu].MENU_NAME, "url": welcomeMenu[prevMenu].URL, "idx": prevMenu, "panId": "#pan" + prevPan };

    
    //우측으로 플리킹
    if (e.direction == 2) {
        loadPanelFromAjax(next);
    }
    //좌측으로 플리킹
    else if (e.direction == 4) {
        loadPanelFromAjax(prev);
    }

    var currUrl = welcomeMenu[currMenu].URL;    

    //패널 이동 시, 스크롤바 최상단으로 이동
    if (window.scrollY > 80) {
        sclTop($("#wPanFlick"), -50, 0);
    }

    //플리킹으로 진입 시, 이미지세팅
    setImageLoad(currUrl);

    //플리킹 이동 시, 클릭코드 설정
    setMcode('' + welcomeMenu[currMenu].CLICK_CODE + '');
    $("#loadingdiv").css("display", "none");
}

//판 데이터 조회
function loadPanelFromAjax(obj, loading, lazyload) {
    if (obj != null && obj.menu != undefined) {
        if (loading != false) {
            $("#loadingdiv").css("display", "block")
                .css("padding-top", window.scrollY + 150);
        }

        $(obj.panId).attr('data-menu-idx', obj.idx).attr('data-menu', obj.menu);

        $.ajax({
            type: "GET",
            url: "/HomeRenewal/" + obj.url,
            contentType: "application/html; charset=utf-8",
            headers: {
                "Yes-Page": "welcome",
            },
            success: function (result) {
                $(obj.panId).html(result);

                if (lazyload == true)
                    setImageCover(obj.url + '_top_area');
                
                wPanFlick.resize();
            },
            error: function (xhr, textStatus, thrownError) {
            },
            complete: function () {
                $("#loadingdiv").css("display", "none");
                SetInitPanHeight();
            }
        });
    }
}

플리킹이 끝날때마다 좌우 필요한 판을 판단해서 ajax로 불러오고 있습니다.
판 내용이 크다보니 효율적으로  load할 수 있는 방법이 있을까 해서 문의 드려봅니다.

**Comment by WoodNeck** [comment]
확인해야 할 부분이 있는데요, `obj.url`이 동일하단 가정 하에, 해당 요청으로 반환되는 결과가 캐시된 값인지를 알아봐야 할 것 같습니다.
Devtool의 Network탭에서 해당 요청이 캐시되었는지 확인해보실 수 있을까요?
불러오는 시간이 요청에 의한 것인지 혹은 다른 이유인지 알아야 도움을 드릴 수 있을 것 같습니다.
요청에 의한게 아닐 경우, 실제 페이지에서 퍼포먼스 분석이 필요할 것 같네요

**Comment by changdongchun** [comment]
Cache-Control = "private" 캐시가 되는 구조는 아닌듯 싶습니다.
ajax에서 불러온 후 변수같은 형태로 저장을 해야 할까요?

**Comment by WoodNeck** [comment]
캐시되지 않는 케이스군요, 그 경우엔 위에 제가 적은것처럼 패널 내용물을 교체하는 과정에서(`$(obj.panId).html(result);`)
기존 패널의 내부 엘리먼트(`$(obj.panId).get()`)를 메모리에 인덱스를 key로 보관하신 후 재활용해보시는게 어떨까 싶습니다.
ajax 요청 이전에 현재 요청하고자 하는 인덱스의 엘리먼트가 존재하는지 확인한 이후에 존재할 경우 추가적인 ajax 요청 없이 기존 엘리먼트를 이용하여 교체하시는게 좋을 것 같네요.
