### ISSUE TITLE
특정 영역안의 flicking 요소들을 한번에 destory할 수 있을까요?

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#373]
## Steps to check or reproduce

특정 함수내에서 지역변수로 플리킹이 선언되어 한 페이지 안에 플리킹요소가 다수 존재 하는데요
이 페이지를 .html('') 으로 지우기 전에 이전에 해당 페이지(영역)에 선언된 Flicking들을 모두 destory하고 싶습니다.

destory하지 않았더니 가로세로 화면 전환 시 getIndex등의 오류가 나오고 있어서요 

혹시 특정 영역안의 플리킹 요소들을 찾아서 destory시킬 수 있을까요

**Comment by WoodNeck** [comment]
안녕하세요.
Flicking에 사용자가 생성한 인스턴스를 관리하는 기능은 없습니다.
때문에 생성된 인스턴스는 직접 관리해주셔야합니다.
