### ISSUE TITLE
flicking 2.5.1

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#374]
## Description

현재 웰컴 판 플리킹중   

pan.pkgd.min.js?v=20200914:13 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

위와 같은 에러가 콘솔창에서 나고 있는데요

동작에는 문제 없이 돌아가고는 있는데 에러가 쌓이고 있어서 혹시 원인을 알 수 있을 지 문의 드립니다.

**Comment by WoodNeck** [comment]
안녕하세요
Flicking의 경우 내부적으로 사용자 input을 핸들링하기 위해 Axes라는 컴포넌트를 사용하고 있는데요
해당 이슈의 경우 Axes 버젼 2.6.0 이후에 픽스되었습니다. (https://github.com/naver/egjs-axes/blob/master/src/inputType/PanInput.ts#L325)
지금 사용중이신 pkgd의 경우 그 이전 버젼을 사용하고 계신 것 같은데요, 모듈 버젼 업데이트를 해보시길 추천드립니다.

**Comment by changdongchun** [comment]
말씀해주신 대로 flicking.pkgd.js 안이 소스를 보니 
/*
  Copyright (c) 2017 NAVER Corp.
  @egjs/axes project is licensed under the MIT license

  @egjs/axes JavaScript library
  https://github.com/naver/egjs-axes

  @version 2.5.10
  */

와 같이 되어있는데요

flicking.pkgd.js 에 말씀하신 Axes 버전을 머지 하려고 하는데 어떤 파일을 받아 보면 될까요?

아니면 혹시 2.5.1의 flicking.pkgd.js에 Axes 최신버전 2.7.0 을 넣어도 되는 걸까요?

**Comment by WoodNeck** [comment]
이전에 CDN에서 pkgd 파일 자체를 받으신 경우라면, 직접 빌드하시는게 나을 것 같네요.
이 레포지토리에서 git clone 이후에, `2.x` 브랜치로 checkout하시고 build 수행해주시면 될 것 같습니다.
```sh
git clone git@github.com:naver/egjs-flicking.git
cd egjs-flicking
git checkout 2.x
git pull
npm i
npm run build
```
이후에 "dist" 폴더에 pkgd파일이 생성될테니 그걸 사용해주세요

**Comment by changdongchun** [comment]
flicking.pkgd.js 파일에서


if (prevent) {
            var srcEvent = event.srcEvent;
            
            if (srcEvent.cancelable !== false) {
                srcEvent.preventDefault();
            }
            srcEvent.stopPropagation();
        }

이 부분만 수정해주닌 더이상 오류가 나타나진 않고 있습니다.
감사합니다.

**Comment by WoodNeck** [comment]
넵^^ 이슈는 닫아두겠습니다. 필요시 다시 열어주세요
