### ISSUE TITLE
flicking 비순환 시 화면 리사이즈에 따른 위치 값 오류

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#375]
## Description

var giftBestScroll = $("#giftBestScl").egFlick({
	circular:false,
	deceleration:.0024,
	moveType:"freeScroll",
	bounce:15,
	gap:-25,
	bound:true,
	onresize:function(idx,e){
		e.moveTo(idx,0);
	}
});

위와 같이 작업 후 모바일웹에서 스크롤 시 브라우저 중 몇몇 브라우저에서 리사이즈 이벤트(세로 스크롤 시 브라우저 주소창 노출 비노출 하면서 resize이벤트 발생)
폭은 변함이 없는데 리사이즈 이벤트가 발생하면서 스크롤 내리고 올리고 할때마다 가로 스크롤 위치가 잘못 표현이 되고 있는데요. 

순환 구조일때는 저런 현상이 나오지는 않는 것 같습니다.
혹시 몰라 영상 첨부하였습니다.
GIFT BEST의 가로 라운드 메뉴에서 그런 현상이 발생하고 있습니다. 패키지 파일 version: 3.4.7을 쓰고 있습니다.

[동영상.zip](https://github.com/naver/egjs-flicking/files/5222312/default.zip)

**Comment by WoodNeck** [comment]
안녕하세요.
Flicking의 경우 freeScroll모드에서 resize시에 현재 선택된 패널 대비 camera element 위치의 percentage를 이용하여 새롭게 위치를 재조정하는 기능이 있습니다.
올려주신 영상의 경우 해당 기능에 의해 이슈가 발생된 것이 아닐까 예상되는데요.
사용중이신 onresize의 경우 직접 구현하신 것 같은데, 해당 메소드에서 Flicking의 index를 0으로 변경하는 동작을 하고계신 것으로 보입니다.
resize => 인덱스 변경 => 위치 조정의 순서가 뭔가 꼬인게 아닐까 생각되는데요, 정확한 원인은 디버깅을 직접 해봐야 파악 가능할 것 같습니다.
디버깅시 Viewport의 `updateCameraPosition` 메소드가 어떤 순서로 수행되는지 파악해보시는게 좋을 것 같습니다.
https://github.com/naver/egjs-flicking/blob/master/src/components/Viewport.ts#L605
위 소스코드를 참조해주세요.

**Comment by changdongchun** [comment]
onresize:function(idx,e){
e.moveTo(idx,0);
}
idx는 현재 idx에서 호출되게끔 한 부분인데요 이부분을 빼고서도 리사이즈 이벤트 auto로 설정해놓으면 동일한 현상이 발생하고 있습니다.

**Comment by WoodNeck** [comment]
Flicking의 경우 resize 이벤트를 따로 제공하고 있지 않습니다.
저 옵션의 경우 따로 구현하신건가요?

**Comment by changdongchun** [comment]
플리킹 옵션 중 autoResize = true 우선 처리하고 쓰고있다가 
해당 현상이 발견되어어 windows.resize일 때 현재 idx를 받아와서 moveTo(숫자,0) 으로 duration 0로 바로 움직이게 처리 했었습니다. 우선 테스트 html에서는 resize를 뺐는데도 
autoResize = true만 준상태인데도 발생이 되는 것 같습니다.

**Comment by changdongchun** [comment]
최초에 한번만 이상하게 나오고 이후에는 정상적으로 보여지는 것 같습니다.
[재현.zip](https://github.com/naver/egjs-flicking/files/5223014/default.zip)

**Comment by WoodNeck** [comment]
디버깅 후 확인해봤는데요, Flicking 버그로 판단됩니다.
원인은 위에 제가 기술한 freeScroll모드에서의 동작과 관련한 것으로 보이구요,
현재 bound 옵션을 사용하고 계시다보니, panelMaintainRatio 값이 범위를 일반적인 범위를 넘어서 값이 잡히고 있는데요
이로 인한 문제로, resize 중 nearestPanel 판정시에 position이 실제보다 더 높은 값으로 판정되어 현재 선택된 패널보다 더 멀리있는 패널을 선택하게 됩니다.

위 버그는 이후 버젼에서 저희가 픽스하도록 하겠습니다.
그 이전에는, 임시로 다음과 같은 방법을 시도해볼 수 있으나,
다만 내부 private 변수를 참조해야하는 불편함은 있을 것 같습니다.

Viewport 내부의 state에는 스크롤 가능 영역인 scrollArea와 camera position에 대한 정보가 있습니다.
현재의 경우 bound 조건 하에서만 위 현상이 일어나는데, 이 경우 camera position === scrollArea.prev 혹은 scrollArea.next인 경우입니다.
따라서, autoResize를 해제하시고, resize전에 위 조건을 체크하여, 만약 해당하는 경우 scrollArea.prev일 때는 index 0으로 이동 후 resize,
scrollArea.next일 경우 last index로 이동 후 resize 수행해주시면 될 것 같습니다.

https://codepen.io/woodneck/pen/LYNBYRX
위 코드는 예시이니 참고해주세요.
