### ISSUE TITLE
Camera position can be wrong when resized with "freeScroll" and "bound"

### ISSUE THREAD

**Issue by WoodNeck** [naver/egjs-flicking#376]
## Description
Camera position can be wrong when resized with the option "freeScroll" and "bound".
This is probably due to the wrong panelMaintainRatio & nearestPanel value on Viewport's `updateCameraPosition` method.
See https://github.com/naver/egjs-flicking/blob/master/src/components/Viewport.ts#L606

## Steps to check or reproduce
https://codepen.io/woodneck/pen/LYNBYRX
- With forking the above example, remove where it compares camera position with scroll area limit then scroll.
- After initializing Flicking, click the second panel
- Make Flicking resized by changing the browser window size

**Comment by changdongchun** [comment]
autoResize = false만으로도 우선 재현이 되질 않고 있는데요

보내주신 케이스처럼 처리를 더 해야 하는건가요?

빠른 답변 감사드립니다.

**Comment by WoodNeck** [comment]
@changdongchun 
autoResize=false 사용시에는 실제 플리킹 가능 영역이 제대로 업데이트되지 않아 제대로 동작하지 않을 것 같은데요
우선 테스트해보시고 사용에 문제 없을 경우에는 해당 방법으로 구현하셔도 괜찮을 것 같습니다~
