### ISSUE TITLE
플리킹 내부에 플리킹을 넣고 안쪽을 드래그하면 안쪽/바깥쪽 함께 넘어가는데 안쪽만 넘어가게 하는 방법을 찾고 있습니다.

### ISSUE THREAD

**Issue by silverprize** [naver/egjs-flicking#379]
## Description
이러한 구조를 만들고 있습니다.
바깥은 5개의 슬라이드로된 Flicking이고 내부Flicking 이라고 적힌 부분은 3개의 슬라이드로된 안쪽 Flicking입니다.
안쪽 Flicking 을 왼쪽이든 오른쪽이든 잡아 끌면 두 Flicking 슬라이드가 함께 넘어갑니다.
마우스나 터치 입력이 안쪽Flicking에 들어가면 안쪽만 넘어가게 할 수 있는 방법이 있나요?
바깥 Flicking에 onHoldStart={(e) => e.stop()} 넣어줘도 바깥 Flicking 슬라이드가 넘어가네요.
이것저것 시도해 보다가 해결이 안되서 문의드립니다.
<img width="415" alt="스크린샷 2020-09-30 오전 9 40 41" src="https://user-images.githubusercontent.com/860087/94630671-689e7d80-0301-11eb-862f-c9d83ae4d72e.png">

**Comment by WoodNeck** [comment]
안녕하세요.
현재 Flicking은 `nested` 옵션이 업데이트 예정에 있어 지원하고 있지 않습니다.
때문에 말씀하신 기능은 현재 버젼으로는 구현하기 어려울 것 같습니다.

---

Hello @silverprize!
Flicking doesn't provide `nested` option at the moment.
It is not possible to create that kind of UI with the current version of Flicking.

**Comment by silverprize** [comment]
@WoodNeck 고맙습니다.
