### ISSUE TITLE
Mousewheel event does not work

### ISSUE THREAD

**Issue by jrodbet** [naver/egjs-flicking#380]
When I try to scroll with the mouse wheel the carousel does not work (scroll). There is some property to activate this?

**Comment by WoodNeck** [comment]
Hello, @jrodbet!
We're preparing for that feature, you can't do that at the moment.
There's a [demo](https://codepen.io/woodneck/pen/oNxOZOp) for that feature, but it uses Flicking's private properties.

**Comment by jrodbet** [comment]
Hi @WoodNeck,
Thanks for your quickly reply!
I was wondering if there is some way to implement that feature (like the demo) with React. Do you know if there is some demo like this for React?
Thanks :)

**Comment by WoodNeck** [comment]
Here you go :)
https://codesandbox.io/s/react-flicking-examples-xboxz?file=/src/Wheel.tsx

**Comment by fullyherge** [comment]
Hi, opening this up again to ask; is this something that is now better supported in v4? Can't find any information elsewhere, but I might be missing something obvious?

Thanks

**Comment by devadaviddd** [comment]
Hi you could using this one to scroll using your mouse wheel  
`import Flicking from '@egjs/react-flicking'
import { useEffect, useRef } from 'react'

export default function PostList() {
  const postCarouselRef = useRef<Flicking>(null)

  useEffect(() => {
    document.body.addEventListener('wheel', onWheelChange)
  }, [])

  const onWheelChange = (e: WheelEvent) => {
    if (postCarouselRef.current) {
      const postCarousel = postCarouselRef.current
      const cameraPosition = postCarousel.camera.position
      postCarousel.control.controller.axes.setTo(
        { flick: cameraPosition + e.deltaY },
        0
      )
    }
  }

  return (
    <Flicking
      circular={true}
      horizontal={false}
      className="w-full h-3/4"
      ref={postCarouselRef}
    >
      <div className="w-full h-1/2 bg-black m-2"></div>
      <div className="w-full h-1/2 bg-black m-2"></div>
    </Flicking>
  )
}
`
![chrome_fE1foSgTad](https://github.com/naver/egjs-flicking/assets/103375085/54338136-ebf0-4076-b160-224e1f41e889)

**Comment by klich3** [comment]
According to the comments, here is the plugin that you can install from ***NPM***, it also has the possibility to scroll horizontally.
[plugin](https://www.npmjs.com/package/egjs-flicking-plugins-whellslide)

```shell
npm i egjs-flicking-plugins-whellslide
```
Regards

**Comment by Omnistas** [comment]
For Vue 3 or Nuxt 3 (with <Flicking ref="flicking">...</Flicking>):

`import Flicking from "@egjs/vue3-flicking"
import "@egjs/vue3-flicking/dist/flicking.css"

const flicking = ref(null)

onMounted(() => {
    flicking.value.element.addEventListener("wheel", (e) => {
        e.preventDefault();

        flicking.value.control.controller.axes.setTo({
            flick: flicking.value.camera.position + e.deltaY
        }, 0)
    })
})`
