### ISSUE TITLE
how can I use prev() next() functions in REACT FLICKING ?

### ISSUE THREAD

**Issue by sosunnyproject** [naver/egjs-flicking#385]
## Description

In pure js version of egjs/flicking, I have used prev() and next() methods (https://naver.github.io/egjs-flicking/release/latest/doc/eg.Flicking.html#next)  to slide the images with custom buttons I made outside of egjs/flicking component. But after I changed it to react-flicking, I cannot find appropriate API to change the index. I'd like to slide the images in flicking with buttons, neither touch nor mouse, and looking for methods like prev() or next(). 
Is it not supported yet in React version, or is there another recommended way of implementing such actions with different API ? 
 기본 js 버전에서는 prev() next() 함수로 flicking의 index를 조절할 수 있었는데, React 버전에서는 해당 기능을 해주는 API를 못찾겠네요. 터치나 마우스가 아닌 따로 커스텀한 버튼을 연결해서 react-flicking 슬라이드와 연결하려는데, index를 바꿀 수 있는 API가 지원되는게 있나요?

**Comment by WoodNeck** [comment]
Hello @sosunnyproject!
You can use the same methods in react-flicking, you can just grab the reference of the component instance and use it.
Here's a sample for it :)
- https://codesandbox.io/s/react-flicking-examples-xboxz?file=/src/Sample.tsx

**Comment by sosunnyproject** [comment]
Thanks! it works now. The sample you provided was helpful!
Just leaving a quick note here, I wish there was a more organized/easier way to find your sandbox example codes. I see a lot of sandbox examples you made, but the link [on this page]((https://github.com/naver/egjs-flicking/blob/master/packages/react-flicking/README.md) only shows one of them (which isn't the one you commented above) 

Great work and thanks for being responsive!
