### ISSUE TITLE
How to create a nested Flicking?

### ISSUE THREAD

**Issue by dol2156** [naver/egjs-flicking#387]
![image](https://user-images.githubusercontent.com/15097841/99635848-ebcc8c00-2a85-11eb-8cbc-11378fb7fcaa.png)

안녕하세요^^

예를들어 2개의 패널을 만들어두고

패널 내부에 가로 방향 이미지 슬라이드를 넣었습니다.
사용한 이미지 슬라이드는 https://kenwheeler.github.io/slick/ 입니다.

플리킹 방향도 좌우이고 이미지 슬라이드도 좌우라서 이 2가지가 동시에 움직이는 현상이 있는데
이미지 슬라이드에서만 플리킹이 작동 하지 않게 하는 방법은 API로 마련되어 있지 않나요?

'holdStart'를 이용해서 
![image](https://user-images.githubusercontent.com/15097841/99636140-60072f80-2a86-11eb-84ed-765ca93afc88.png)
stop() 을 실행시켜 임시방편으로 처리는 했습니다만,

비단 슬라이드 뿐아니라 가로 스크롤이 있는 div 도 좌우 스크롤이 되지 않아 어떻게해야할지 난관에 부딪혔습니다.

도움 부탁드립니다 ㅜㅜ

**Comment by WoodNeck** [comment]
안녕하세요~
현재 관련 기능을 준비중에 있습니다. 이후에 `nested`와 같은 이름으로 추가될 예정입니다.
때문에 현재는 말씀하신 기능을 현재 제공되는 API으로 만드는건 어려울 것 같습니다.
대신 일부 내부 프로퍼티에 접근시 비슷한 기능을 만드는건 가능합니다.

예시를 간단하게 만들었으니 확인해보세요: https://codepen.io/woodneck/pen/JjKqXWz

+ 작성하신 예제의 경우 flicking의 인스턴스를 slick보다 먼저 만드신 것 같은데요, 이 경우 Flicking의 이벤트 핸들러가 slick보다 먼저 등록되기 때문에 stop()시에 slick의 이벤트 핸들러도 작동하지 않게된 것으로 보입니다. 인스턴스 생성 순서를 바꿔보시면 어떨까 합니다.
이벤트 핸들러 순서는 대부분의 브라우저에서 등록한 순서와 동일하기 때문에 해당 방법을 사용하시더라도 큰 문제는 없을거라고 생각됩니다. IE8 이전의 브라우저의 경우엔 문제가 될 수 있습니다.

**Comment by dol2156** [comment]
정말 감사합니다! ^^ 많은 도움 되었습니다!

**Comment by WoodNeck** [comment]
@dol2156 
데모에 제가 잠깐 테스트하던 코드가 포함되어있어서 제대로 동작하지 않아 수정했습니다.
필요하시면 확인해보세요~

**Comment by dol2156** [comment]
아~ 옙! 감사합니다!
