### ISSUE TITLE
How to snap exact 2 or 3 panels at once?

### ISSUE THREAD

**Issue by do2bly** [naver/egjs-flicking#399]
## Description
반응형에 따라 3판 또는 2판으로 UI를 구성하고
이를 snap과 좌우 prev, next 버튼으로 3판이나 2판씩 단위로 슬라이딩 되도록 플리킹을 구현하려고 합니다.
prev, next로 컨트롤하는 부분은 moveTo 함수에 index를 계산하여 주입하는걸로 구현했지만,
snap액션의 경우 어느부분에서 이를 처리해줘야할지 모호한 상황인데요.
이를 구현할수 있는 방법을 가이드해 주실수 있을까요?

**Comment by WoodNeck** [comment]
@do2bly 님 안녕하세요~
현재 아쉽게도 관련 기능을 지원하고 있지 않습니다.
앞으로 추가할 기능인 #189 (strict move type)에서 해당 기능을 지원할 예정입니다.

현재 상태에서 관련 기능을 구현하시기 위해선, change 이벤트를 stop하신 후 별도로 패널의 `focus` 메소드를 호출하시는 방법이 있을 것 같습니다.

**Comment by do2bly** [comment]
@WoodNeck 
빠른 답변 감사드립니다!
제안해주신 구현방법을 좀더 디테일하게 설명해주실순 없을까요?
예제 케이스가 있다면 공유해주시면 정말 감사하겠습니다!

**Comment by WoodNeck** [comment]
@do2bly 
https://codepen.io/woodneck/pen/NWWRKgM
위 예제는 circular 상황에서 비슷한 UX를 구현한 예제인데요, 참고가 된다면 좋겠습니다^^

**Comment by do2bly** [comment]
@WoodNeck 
예제 정말 감사드립니다! 예제중에 currentPanel.next().next() 이부분을 가변적으로 처리할수 없을까요?
currentPanel 기준으로 next가 아닌 n번째 패널을 가져올수 있는 방법이 궁금합니다.

**Comment by WoodNeck** [comment]
circular 옵션을 사용중이시라면 currentPanel을 기준으로 next()를 n회 호출해주시면 될 것 같구요,
그렇지 않은 경우라면 `getPanel()` 메소드를 활용해주시면 될 것 같습니다.

```js
let n = 3;

const panelCount = flicking.getPanelCount();
const currentPanel = flicking.getCurrentPanel();
const clamp = (val, min, max) => Math.max(Math.min(val, max), min);

const targetIndex = clamp(currentPanel.getIndex() + n, 0, panelCount - 1);
const targetPanel = flicking.getPanel(targetIndex);

targetPanel.focus(500);
```

**Comment by do2bly** [comment]
@WoodNeck 
감사합니다! 안내해주신 덕분에 잘 구현할 수 있었습니다.
strict move type 이 추가된 버전은 언제 릴리즈 될 예정일까요?
