### ISSUE TITLE
Access of viewport

### ISSUE THREAD

**Issue by gamtiq** [naver/egjs-flicking#401]
## Description

Sometimes it is necessary to access `flicking's` viewport. For example, to make calculations based on viewport’s and panels sizes.
It seems at the moment there is no way to access viewport. It is possible only by using private properties.
The issue is also true for React Flicking.

**Comment by WoodNeck** [comment]
I totally agree with you, as I often create a demo including access to viewport & axes inside Flicking.
But before making Viewport public, refactoring should be done first.
Like I've written on the roadmap, Flicking should be more structured.
Viewport currently has so many responsibilities for a single component, and its responsibilities should be redistributed to smaller components.
That's the main reason why we left it private, I think we can make our private properties public after that :)

**Comment by gamtiq** [comment]
I understand and agree with your reasons.
I presume that refactoring can take long time.
Is it possible before that to add method `getViewportSize` to `flicking` and React component that returns viewport's size?
Such method can be useful itself and can be saved after refactoring is done.

**Comment by WoodNeck** [comment]
@gamtiq 
I think I can do that :)
I'll leave a comment here after adding it.

**Comment by WoodNeck** [comment]
@gamtiq 
We've released a new version of react-flicking (v3.5.0)
That'll have a method called `getSize` which will return the value what you need :)

**Comment by gamtiq** [comment]
Thank you very much!

**Comment by gamtiq** [comment]
Unfortunately `getSize` isn't available in React component's API in version 3.5.0.

**Comment by WoodNeck** [comment]
@gamtiq 
I've found out that there was a problem with the dependency version in react-flicking, so I've updated it to v3.5.1.
Please use that version instead :)
