### ISSUE TITLE
React Flicking remove stop()

### ISSUE THREAD

**Issue by carlocarpio** [naver/egjs-flicking#410]
## Description
I'm using React Flicking for mobile web and I'm stopping the `onMoveStart` when user is scrolling vertically so it will not have unwanted horizontal scroll. 

I have 2 flicking instance, 1 is for navigation and the other is for the page content. The two instance are sync on load and when I stop the Page Content Instance, the Navigation Flicking cannot control the Page Content anymore.

The stop() is working fine and I just want to know if there's a way to remove the stop(). So the  Navigation Flicking can control the Page Content Flicking. 

Thanks.

```
onMoveStart={(e: FlickingEvent) => {
    if (scrolled) {
        e.stop()
    }
}}

**Comment by WoodNeck** [comment]
Hello @carlocarpio!
Can you try `disableInput()` after stop then `enableInput()`?

**Comment by carlocarpio** [comment]
> Hello @carlocarpio!
> Can you try `disableInput()` after stop then `enableInput()`?

Thanks for the quick response.

Where can I find the disableInput() and enableInput()? FlickingEvent does not have those props. Thanks.

**Comment by WoodNeck** [comment]
You should take the reference of the Flicking component.
Here's a sample for you :)
https://codesandbox.io/s/react-flicking-examples-xboxz?file=/src/Sample.tsx

**Comment by carlocarpio** [comment]
> You should take the reference of the Flicking component.
> Here's a sample for you :)
> https://codesandbox.io/s/react-flicking-examples-xboxz?file=/src/Sample.tsx

All working fine now. Thanks for the help!

**Comment by WoodNeck** [comment]
Great to hear that :)
I'll close this issue, feel free to reopen it whenever it's needed.
