### ISSUE TITLE
Handling of height adjustment when contents of panel expands.

### ISSUE THREAD

**Issue by carlocarpio** [naver/egjs-flicking#413]
## Description
What's the better way to adjust panel height when contents inside it expandes/collapse?

I'm using resize(), but maybe there's a better way to auto adjust the panel height. Thanks.

**Comment by WoodNeck** [comment]
Hello, @carlocarpio!
Well, if there's no movement included, `resize()` is the best option you can choose for now.
Or, if you want to fit viewport height after movement, there is an `adaptive` option for that case, try that.

If you provide me some actual implementation, I could help you a little more. :)

**Comment by buckets24** [comment]
@WoodNeck i have a question with regards to height adjustment, I have this animation issue when my footer expands and the height of the flicking expands, the animation is laggy when that happens. height animation at the very top of the page is smooth but the height animation at the bottom of the page is laggy. Is this expected? Thanks.

**Comment by WoodNeck** [comment]
@buckets24 Hello!
I'm not seeing the actual page so I'm just guessing, but I think that's not Flicking's issue.
Animating height causes the browser to reflow, so maybe changing the height itself is the cause of the lag.
Can you check whether the page's still laggy when the Flicking is not mounted? (i.e. `new Flicking` is not called?)

**Comment by buckets24** [comment]
@WoodNeck I sorted out the laggy issue when height changes. 
I have a follow up question, I have a collapsible items in the page and it adjust the height of the panel, my concern now is the extra space at the bottom of the page. Is there a way to readjust the height back to the the original height when all collapsible components is closed?

**Comment by WoodNeck** [comment]
@buckets24 
You can try calling `resize()` after your component has closed.
