### ISSUE TITLE
React Flicking: Access of target DOM element in select event or prevent triggering of select event in some cases

### ISSUE THREAD

**Issue by gamtiq** [naver/egjs-flicking#417]
## Description
It seems it is impossible access of target DOM element in `select` event.

I have a use case where panels contain several different interactive elements (for example, text, images and buttons).
When a user clicks on text or image inside a panel, `select` event should be processed.
But when a user clicks on a button, `select` event should be ignored (or bypassed) and only button’s click handler should be processed.
Unfortunately I’ve not found a way to achieve this behavior.
`Select` event handler is always triggered before button’s click event handler (even before capture handler).
There is no way to prevent triggering of `select` event depending of target DOM element.

## Steps to check or reproduce
Use the following code sandbox to check the issue: https://codesandbox.io/s/react-flicking-select-event-target-element-issue-8hop9
Click on an action button.
You will see in console that `select` event handler is run before button’s click handlers.
This is undesired and problematic in my case.

**Comment by WoodNeck** [comment]
Hello, @gamtiq!
Like you've said, looks like there's no way to filter the `select` event  by using current properties of it.
We'll consider adding at least `element` property to reveal which element is clicked, so you can filter that.
