### ISSUE TITLE
Issue problem with the wrapper when the panel is different in height.

### ISSUE THREAD

**Issue by do2bly** [naver/egjs-flicking#427]
## Description
I am using React Flick 3.2.2.
The parent wrapper has a height problem when there are three panels 
with different heights and the adaptive option is true.

This is my react component code.
```
<BoardFlicking
  autoResize={true}
  useOffset={true}
  adaptive={true}
  hanger={0}
  bounce={0}
  anchor={0}
  duration={400}>
  ...
</BoardFlicking>
```

## Steps to check or reproduce
You can see it well when you load it for the first time, 
but an error occurs when a resize event occurs.

![image](https://user-images.githubusercontent.com/49511407/108984297-18222500-76d3-11eb-8c3b-4c553120d4d6.png)
![image](https://user-images.githubusercontent.com/49511407/108984689-8a930500-76d3-11eb-9729-eccac22d2202.png)

![image](https://user-images.githubusercontent.com/49511407/108984355-2a9c5e80-76d3-11eb-8310-67b2bbc50c1d.png)

![image](https://user-images.githubusercontent.com/49511407/108984427-430c7900-76d3-11eb-8498-536cdce11ef8.png)

**Comment by WoodNeck** [comment]
Hello @do2bly!
Looks like the first panel of your UI has a smaller height than the other panels.
`adaptive` option is to set the height the same as the current panel's height. did you mean to do that?

**Comment by do2bly** [comment]
@WoodNeck 
yes, I want the height of the wrapper to be set according to the panel with the largest height.

my application is responsive web. 
I want the wrapper's height to be maintained even if the screen is resized.

but now, when resized browser, the height of the wrapper is set by the height of the first panel.

**Comment by WoodNeck** [comment]
@do2bly 
In that case, you can set `adaptive` to false, as that does resize height to the maximum height of the panels.

**Comment by do2bly** [comment]
@WoodNeck 

The `adaptive` option must be true.
Because we need to detect that the height of the panel changes when swiping on the mobile screen.

![image](https://user-images.githubusercontent.com/49511407/109025178-d6f53980-7701-11eb-9072-8405c292022c.png)

I need to turn on the adaptive option and find a way to keep the wrapper height when resizing.
Is there a way to resolve?

**Comment by WoodNeck** [comment]
In that case, I think you still have to turn the `adaptive` option off as that updates viewport height with same to panel's height below.
You can try calling `resize()` on `moveEnd` event.
But remember it is better to call `resize` at the exact timing that panel's height changes.

```tsx
<Flicking
  onMoveEnd={e => { e.currentTarget.resize(); }}>
  ```
