### ISSUE TITLE
Question about adjusting the "translate" value

### ISSUE THREAD

**Issue by peanutsando** [naver/egjs-flicking#430]
I can control it through `anchor` value.
but if `bound` value is true, `translate` value is specified 0.

Is there a way to control it separately?

I'd like to keep the first and last elements apart.

**Comment by WoodNeck** [comment]
Can you give me some more detailed info about the UI you're trying to achieve?
A single screenshot would be help.

**Comment by peanutsando** [comment]
![image](https://user-images.githubusercontent.com/9045100/109743757-92433400-7c14-11eb-9bd6-dbd16a1e5305.png)

I attach the properties I used.

```
horizontal={true}
infinite={false}
autoResize={true}
hanger={0}
anchor={0}
bounce={600}
bound={true}
gap={8}
duration={1000}
isConstantSize={true}
isEqualSize={true}
moveType={{ type: 'snap', count: moveStep }}
renderOnlyVisible={true}
```

**Comment by WoodNeck** [comment]
What do you mean with the word "first and last elements apart"?
Do you mean you want to add some padding before first panel?
Or, more gap between first and second panel?

**Comment by peanutsando** [comment]
This means that first and last element are separated from the parent element at a consistently interval.
ex) The first and last elements should be spaced about 20px.

When the first element is given padding, it is covered by the padding when scrolling.

I hope it's not covered, is there any other way?

**Comment by WoodNeck** [comment]
In that case, I think you can give some padding to parent element and use `overflow: true` option to visualize covered elements :)

**Comment by peanutsando** [comment]
> In that case, I think you can give some padding to parent element and use `overflow: true` option to visualize covered elements :)

All working fine now. Thanks for the help :)

**Comment by WoodNeck** [comment]
Good! Then I'll close this issue :)
