### ISSUE TITLE
Carousel fires select event on touch devices even if scrolling up/down

### ISSUE THREAD

**Issue by SkylerStearns** [naver/egjs-flicking#432]
## Description
Since the carousel is only detecting if the user is sliding left/right in the carousel, the user can accidentally trigger the 'select event' even if they are scrolling up and down on a touch device, accidentally dragging over the carousel.

## Steps to check or reproduce
1. Go to https://naver.github.io/egjs-flicking/features/events.html on a mobile device. (Flicking example for events)
2. Portrait mode, move carousel up and down, see events. (Move left to right, select will fire. Move up and down and not left to right, select will not fire)
3. Landscape mode, move carousel up and down, see events. (Move left to right, select will fire. Move up and down and not left to right, the page will move and select will fire.)

Notes:
The firing of the select event is both consistent and inconsistent, because the carousel itself is not sliding up and down, but in most cases on mobile, the select event can fire off when using your mobile device, and can cause problems. We use flicking to open a modal depending on the panel selected. While scrolling down on mobile, if the user tries scrolling past the flicking carousel, and drags their thumb over the carousel, the carousel shouldn't fire 'select', but does because it was not able to detect if the user was scrolling up/down. It just knows that the user did click on it, and the carousel didn't move left/right, even when the page moved up/down.

**Comment by WoodNeck** [comment]
Hello @SkylerStearns!
We've received a similar issue like this last week, that the Flicking can move while the page's scrolling.
I'm trying to fix it by preventing Flicking events to trigger while the page is scrolling, I'll tell you when it's done :)

**Comment by SkylerStearns** [comment]
Thanks for the response! Love the package.

**Comment by WoodNeck** [comment]
@SkylerStearns I've just released v3.8.1 that fixes this issue, try that!

**Comment by SkylerStearns** [comment]
@WoodNeck The update looks like it fixed our issue. Thanks again for the quick response and update! I really appreciate it. Have a good rest of your day!
