### ISSUE TITLE
Mobile IOS input tab goes to another screen.

### ISSUE THREAD

**Issue by buckets24** [naver/egjs-flicking#437]
## Description
I used Flicking as screen navigation and I have inputs in some on some of the pages. I turned off the RenderOnlyVisible props because of some requirements in my app. I have an IOS specific issue when input is focused and keyboard is showing then I hit the arrow up or arrow down key in the keyboard, it shows the closest screen to the active screen. It focuses to the closest screens inner elements which triggers Flicking to show the other screens. Is there a way to restrict focusing on other screens when Im on the Active screen while RenderOnlyVisible is OFF?

**Comment by WoodNeck** [comment]
Hello @buckets24!
I think this looks similar to #332, but our log says that it can cause a flickering issue in iOS.

I think you can try adding [tabindex="-1"](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) to all input/anchor elements inside the panels to solve this issue. I've tested on the other environments but not for the iOS so please tell me if that doesn't work.

For the #332 issue, we've guided to set all the inputs in the panels to be `"disable"` and enable the active one on the `moveEnd` event. You can use that if it's applicable.

**Comment by buckets24** [comment]
@WoodNeck Thank you for the quick response. I solved this issue by restricting the scrollLeft and scrollTop. Keep up the good work!
