### ISSUE TITLE
Issue with prev\next methods when bound prop is applied

### ISSUE THREAD

**Issue by matiosfree** [naver/egjs-flicking#442]
## Description
The requirement is to have 4 slides on the screen. These 4 slides should contain 100% of the width. The slides should start from the left side. For that purpose I use prop **bound**. When I click on the Prev\Next button I should see next slide. but the previous should be hidden.  ex.: 0, 1, 2, 3  => click on the NEXT BTN => 1, 2, 3, 4

When I click on the NEXT button first time nothing is happened. When I click on the NEXT button second time only half of the first slide is hidden. when I click on the same button 3th time I see the half ov the second slide, 3th slide, 4th slide, 5th slide and hald of 6st slide.

## Steps to check or reproduce
```tsx
export default function Sample() {
  const flicking = React.useRef<Flicking>(null);
  const [data] = React.useState([0, 1, 2, 3, 4, 5, 6, 7, 8]);
  const [selected, setSelected] = React.useState(0);

  const handlePrevClick = React.useCallback(
    e => {
      if (flicking.current) {
        flicking.current.prev();
      }
    },
    [flicking.current]
  );

  const handleNextClick = React.useCallback(
    e => {
      if (flicking.current) {
        flicking.current.next();
      }
    },
    [flicking.current]
  );

  return (
    <div className="container">
        <button onClick={handlePrevClick}>Left</button>
        <Flicking
          bound
          className="flicking"
          ref={flicking}
          onMoveEnd={e => {
            setSelected(e.index)
          }}
        >
          {data.map(index => (
            <div className="panel" style={{ width: "25%" }} key={index}>
              <div className="anchor" />
            </div>
          ))}
        </Flicking>
        <DotIndicator list={data} selected={selected} />
        <button onClick={handleNextClick}>Right</button>
    </div>
  );
}
```

**Comment by WoodNeck** [comment]
Hello, @matiosfree!
Well, actually this is a common issue in v3 that will be totally solved in Flicking v4.
As all panels can be selected while calling the `prev` and `next`, that happens.
It is awkward to say...but you can bypass that by changing prev/next call depending on your UI.

```ts
  const handleNextClick = React.useCallback(
    e => {
      if (!flicking.current) return;

      if (flicking.current.getIndex() < SOME_INDEX) {
        flicking.current.moveTo(SOME_INDEX);
      } else {
        flicking.next();
      }
    },
    [flicking.current]
  );
```

Flicking v4 will be released within at least June.

**Comment by matiosfree** [comment]
ok, got it. thank you
