### ISSUE TITLE
Safari browser Rendering issue

### ISSUE THREAD

**Issue by peanutsando** [naver/egjs-flicking#444]
## Description
![image](https://user-images.githubusercontent.com/9045100/117766420-84400e00-b26a-11eb-9110-30232b0e0c95.png)
위 이미지와 같이, 간헐적으로 사파리 브라우저에서 렌더링이 깨지는 경우가 발생합니다.
반응형 웹 사이트라서 가로폭이 수치로 지정되는게 아니라 %로 지정 되어있는데요.
혹시 어떤 부분이 원인인지 알 수 있을까요 ?

## Steps to check or reproduce

```js
              viewportTag="div"
              horizontal={true}
              infinite={false}
              autoResize={true}
              hanger={0}
              anchor={0}
              bounce={600}
              duration={1000}
              useOffset={true}
```
와 같이 지정해두었습니다.

**Comment by henrysha** [comment]
Safari + Next.js(SSR) 환경에서 새로고침시 렌더링 이슈가 발생하는걸 확인했는데요, (링크는 아직 피쳐가 배포전이라서 외부공개 링크가 없습니다....)

아무래도 SSR에서 새로고침을 하게 될때 Flicking컴포넌트가 내부 패널의 `width`와 `height`을 제대로 못가져오는 이슈가 webkit 환경 (사파리) 에서 발생하고 있는 것 같습니다. 패널이 80px width만 잡아먹어야하는데, 100%를 다 잡아먹는 현상이 새로고침을 할때 생깁니다.

**Comment by WoodNeck** [comment]
@henrysha 
말씀하신대로 타이밍 이슈 같네요.
새로고침 전후에 패널 크기를 동일하게 설정하는건 어려울까요?
CSS 통해서 그렇게 설정 가능할 경우 해당 방법 시도해보시면 좋을 것 같구요
혹은 이미지 등 로드 이후에 패널 크기가 변하는 케이스인 경우에는, 로드 이후에 `resize` 메소드를 이용해보시면 좋을 것 같습니다.

**Comment by peanutsando** [comment]
답변이 늦었네요. `resize` 메소드 적용 후에 해당 증상은 사라졌습니다.
확인 감사합니다.

**Comment by peanutsando** [comment]
@WoodNeck 

https://game.naver.com/esports
`resize` 메소드 적용 후에도 재발하고 있어서요, SSR에서 width를 정상적으로 가져오지 못할 때 발생하는 것 같네요.
반응형 웹이라 동일한 패널로 적용하긴 어려울것 같습니다.

**Comment by WoodNeck** [comment]
@peanutsando 

페이지 확인해봤습니다.
초기 로드된 html 확인시에, Flicking 영역(`.schedule_flicking`)이 페이지 내에 존재하지 않고 이후에 추가되는 것으로 확인되었는데요
Flicking을 추가하는 스크립트가 `async` 처리되어있기 때문에, 이 js파일과, 스타일을 설정하는 CSS 파일 중 어느 파일이 먼저 로드되느냐에 따라서 해당 이슈가 나타나는 것으로 보입니다.
즉, 해당 이슈는 CSS파일보다 JS파일이 먼저 로드되어 나타나는 이슈라고 보시면 될 것 같구요
테스트시에 해당 이슈가 나타나는 엘리먼트를 렌더링하는 JS파일(https://ssl.pstatic.net/static/nng/esports/c2b8d65d4c457c14af87c3210f9c6a83c2cb5fb8/_next/static/chunks/pages/index-1311a06635cf8d0d96f1.js) 의 async attribute를 제거시 매번 페이지가 정상적으로 로드되는 것을 확인했습니다.

Next.js에서 관련 설정을 찾아보시면 좋을 것 같습니다.

**Comment by peanutsando** [comment]
@WoodNeck 
`defer`를 사용하여 스크립트 로드를 지연해서 적용해 보았는데, 새로고침을 여러번 할 경우에 비슷한 증상이 나타나는 것 같습니다.
기존처럼 2~3개씩 겹치는 경우는 없는것 같습니다.

<img width="1414" alt="스크린샷 2021-06-24 오후 7 51 58" src="https://user-images.githubusercontent.com/9045100/123254139-3f75eb00-d529-11eb-815b-e87b2eafeab5.png">

**Comment by WoodNeck** [comment]
@peanutsando 
제 맥북 환경에서는 아무리 새로고침을 하더라도 해당 이슈가 재현되지 않네요...
혹시 가능하시다면 v4로 업데이트하시는 것을 추천드립니다.
v4에서는 패널 배치시에 `position: absolute` 속성을 사용하지 않기 때문에 해당 이슈가 나타나지 않습니다.
[마이그레이션 가이드](https://naver.github.io/egjs-flicking/docs/migration-from-v3)를 참고 부탁드립니다.
