### ISSUE TITLE
How do I using change in Nuxt?

### ISSUE THREAD

**Issue by Red-Asuka** [naver/egjs-flicking#445]
i'm using now nuxt.js and composition-api
I don't understand the document well.
i use `moveTo` like this, but i don't understand how to use `change`.
how to use `change`? show me exmple plz
```
<flicking
  class="flicking"
  ref="flick"
  :options="{ hanger: 0, anchor: 0, bound: true, zIndex: 10, duration: 500, adaptive: true }"
>
  <div v-for="i in 6" :key="i" class="panel"> </div>
</flicking>

setup() {
    const currentIndex = ref(0)
    const flick = ref()

    const flickingMove = (index: number) => {
      currentIndex.value = index
      flick.value && flick.value.moveTo(currentIndex.value)
    }

    return {
      currentIndex,
      flick,
      flickingMove,
    }
  },
```

**Comment by WoodNeck** [comment]
Hello @Red-Asuka!
You can use it the same way Vue handles events.
```vue
<Flicking
  @change="e => { ... }"
  @move-end="e => { ... }"
  v-on:need-panel="e => { ... }"
>
   {{ ... }}
</Flicking>
```
Also, all event names are renamed to `kebab-case`, following the [Vue event naming convention](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names).

**Comment by Red-Asuka** [comment]
@WoodNeck it works, thanks!
