### ISSUE TITLE
Support for Vue 3.x

### ISSUE THREAD

**Issue by david50407** [naver/egjs-flicking#446]
## Description

Current `@egjs/vue-flicking` package pinned to vue 2.6 and use class component with decorator to implement the wrapper,
this caused Vue 3.x cannot use this package directly, and users should wrap egjs-flicking into Vue 3 component by ourselves.

**Comment by WoodNeck** [comment]
Hello @david50407!
We're preparing for this, I'll notify you when we're finished.

**Comment by moseskamau338** [comment]
waiting...

**Comment by WoodNeck** [comment]
We've just released `vue3-flicking@4.0.0` :)
Feel free to test it and leave a comment here if there is an issue
