### ISSUE TITLE
Align and renderOnlyVisible with SSR

### ISSUE THREAD

**Issue by MaximKondratev** [naver/egjs-flicking#457]
## Description
Flicking v4 is positioned as SSR-ready library. Trying to make it work with SSR i got some questions.

My setup is like 
```tsx
<Flicking
    align={{ panel: '50%', camera: 0 }}
    circular={true}
    renderOnlyVisible={true}
    ...
```

1) Question about align prop. With my setup i have first seen panel is half off the screen.  It seems that this 50% shift is done by `transform: translate` css property which can not be calculated on SSR, so initial markup does not have this shift, but after hydration it gets shifted. Does it mean i can use only "prev" align value on SSR to match markup?

2) Question about renderOnlyVisible prop. I can have 100+ possible panels so i want to render only visible of them. Initial markup from SSR contains every panel, after hydration only visible panels remain. As number of panels is large, i don't want to send markup of all 100+ panels to client. Is it possible to create only **n** panels on SSR like 10? i can slice items array by myself on server and after hydration use full array, but maybe it is possible by flicking?

**Comment by WoodNeck** [comment]
Hello @MaximKondratev!

First, for the `renderOnlyVisible` option,
It actually is needed to render all panels before mounting the Flicking to get the sizes of them.
As it is impossible to get sizes of panels before rendering on the client-side, which is essential to `renderOnlyVisible` but I really understand your concern.
I hope there's a better solution, but I think the best way, in this case, is to load panels asynchronously.
If possible, try adding panels later with the [needPanel](https://naver.github.io/egjs-flicking/docs/api/Flicking#event-needPanel) event.

Second, for the align values in the SSR env,
We're aware of this issue, and preparing a new release with the feature to apply align values before Flicking is mounted.
One solution is like this:
This is a sample code of `vue-flicking`'s new release that applies CSS align styles before the Flicking's gonna be mounted.

```diff
+   if (!flicking) {
+     const align = this.options.align || "center";
+     const alignVal = typeof align === "object"
+       ? (align as { camera: string | number }).camera
+       : align;
+     cameraData.style = `transform: translate(${parseAlign(alignVal)})`;
+   }

    const slots = (this._diffResult && flicking && flicking.initialized)
      ? getRenderingPanels(flicking, this._diffResult)
+     : this._getStyleAppliedSlots();
```

```ts
private _getStyleAppliedSlots() {
  const slots = this._getSlots();
  const align = this.options.align || "center";
  const alignVal = typeof align === "object"
    ? (align as { panel: string | number }).panel
    : align;
  const parsedAlign = `translate(-${parseAlign(alignVal)})`;

  slots.forEach(slot => {
    if (!slot.data) {
      slot.data = {
        style: {
          transform: parsedAlign
        }
      };
    } else {
      if (slot.data.staticStyle) {
        slot.data.staticStyle.transform = parsedAlign;
      } else {
        slot.data.staticStyle = {
          transform: parsedAlign
        };
      }
    }
  });

  return slots;
}
```

Like you see, this will overwrite the style value "transform" of the panels
so in this spec, there's a problem that you can't use CSS transform in panels while it can automatically apply align values.

Other option is :
- Adding CSS class like "flicking-before-mount" or something, so you can apply align values yourself like below
```css
#your-flicking-id.flicking-before-mount {
  transform: translate(CAMERA_ALIGN_VALUE); /* in your case, it will be `transform: translate(0);` */
}

#your-flicking-id.flicking-before-mount .flicking-camera > * {
  transform: translate(-PANEL_ALIGN_VALUE); /* in your case, it will be `transform: translate(-50%);` */
}
```

Which one do you think is better?
Any suggestions will be appreciated.
