### ISSUE TITLE
Flicking#methods page 404

### ISSUE THREAD

**Issue by robjewell-ibotta** [naver/egjs-flicking#467]
## Description
I am not too sure where to bring this issue up, but this page https://naver.github.io/egjs-flicking/docs/using-the-methods/api/Flicking#methods is not available. I found this page linked [here](https://naver.github.io/egjs-flicking/docs/using-the-methods/)

**Comment by WoodNeck** [comment]
Hello @robjewell-ibotta!
Thanks for reporting the issue, I'll fix that asap :)
