### ISSUE TITLE
기존 3.x.x 에서 4.x.x 마이그레이션은?

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#471]
## Description
1. flicking.css 추가
2. viewport와 camera 클래스 및 영역 추가
3. 함수 호출 시 eg.Flicking 아닌 Flicking으로 호출

이정도로 처리하면 되나요? 기존 속성중 gap : -15 를 쓰고
pannel에서 안의 컨텐츠를 margin:0 15px을 줘서 
15px[ ○○○○]15px[○○○]15px[ ○○○○]15px[○○○]15px 
위와 같이 circular false 일때 좌우측 15px남겨서 플리킹 영역을 짰었는데 위와 같이 4버전에서 구현하려면 gap -15대신 어떻게 써야 하나요?

**Comment by WoodNeck** [comment]
Hello @changdongchun!
You can set the `padding` value of the viewport element to replace that.

--- 

안녕하세요.
해당 케이스의 경우 viewport 영역(`.flicking-viewport`)에 padding을 주는 방식으로 구현하시면 동일하게 구현 가능합니다.
마이그레이션 하셔야 할 부분에 대해서는 [마이그레이션 가이드](https://naver.github.io/egjs-flicking/docs/migration-from-v3)를 참고해주세요.

**Comment by changdongchun** [comment]
빠른 답변 감사드려요~
