### ISSUE TITLE
Trying to set up forked flicking for vue 2 development and flicking contributions

### ISSUE THREAD

**Issue by robjewell-ibotta** [naver/egjs-flicking#476]
I've created a [vue 2 project](https://github.com/robjewell-ibotta/flicking-carousel-throttle/pull/1), and I'm currently installing a [forked version](https://github.com/robjewell-ibotta/egjs-flicking) of flicking, which is installed locally on my machine. On my machine, I have followed [these docs](https://github.com/naver/egjs-flicking/blob/master/packages/vue-flicking/CONTRIBUTING.md#local-development) to get set up on the project. I ran `npm install` and then `npm run build` to create a production version of flicking. 

As you can see [here](https://github.com/robjewell-ibotta/flicking-carousel-throttle/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) I attempt to pull in that locally installed setup of Flicking. However whenever I try to run my project locally I see these errors in console:

```
 ERROR  Failed to compile with 2 errors                                       11:45:45 AM

These dependencies were not found:

* @egjs/flicking/dist/flicking.inline.css in ./src/main.js
* @egjs/vue-flicking in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save @egjs/flicking/dist/flicking.inline.css @egjs/vue-flicking
``` 

I have run `npm install --save @egjs/flicking/dist/flicking.inline.css @egjs/vue-flicking`, but I'm still seeing the same error.

Is there something I am not doing correctly? I just want to use the `vue-cli` to create a vue 2 app and pull in my forked copy of flicking so that I can run flicking in a vue project on my machine (MacOS  Big Sur). This way I can contribute to my local forked copy of flicking and run `npm run build` from flicking, which will allow my vue project using flicking to have my flicking code changes.

This will allow me to contribute code to flicking and demonstrate the solution of my contribution with a working vue example.

**Comment by robjewell-ibotta** [comment]
Ok I was able to get around the above errors:
* I updated this line of css `import "@egjs/flicking/dist/flicking-inline.css"; //Supports IE9+, using CSS inline-box`
* I ran `npm run build` from `egjs-flicking/packages/vue-flicking`

However now I'm seeing this error when I go to run my vue app locally, which is pointing to the local fork of flicking:
```
 ERROR  Failed to compile with 1 error                                        12:14:34 PM

 error  in /Users/rob.jewell/code/open-source/forks/egjs-flicking/packages/vue-flicking/dist/flicking.esm.js

Syntax Error: Error: Failed to load plugin '@typescript-eslint' declared in '../../open-source/forks/egjs-flicking/.eslintrc.js#overrides[0]': Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- /Users/rob.jewell/code/toys/flicking-carousel-throttle/__placeholder__.js
Referenced from: /Users/rob.jewell/code/open-source/forks/egjs-flicking/.eslintrc.js
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at _normalizeObjectConfigData.next (<anonymous>)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at _normalizeObjectConfigData.next (<anonymous>)


 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& 15:0-46 26:14-22
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.184:8088&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

```

**Comment by WoodNeck** [comment]
Hello @robjewell-ibotta!
I guess the eslint is searching `@typescript-eslint` from your project folder instead of the folder which fork of Flicking is in?

But normally, in that case, I think eslint shouldn't be applied to the bundled js file.
I think you should find a way to ignore those files in the fork of Flicking while you're linting.
Like, adding the Flicking fork folder to `.eslintignore` or something.

**Comment by robjewell-ibotta** [comment]
When I run `npm run serve` from my vue project which is loading my fork locally [here](https://github.com/robjewell-ibotta/flicking-carousel-throttle/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R11) and [here](https://github.com/robjewell-ibotta/flicking-carousel-throttle/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R12), I see this error:
```
➜  flicking-carousel-throttle git:(fix/animation-already-playing) npm run serve

> flicking-carousel-throttle@0.1.0 serve /Users/rob.jewell/code/toys/flicking-carousel-throttle
> vue-cli-service serve --port 8088

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                        11:11:10 AM

 error  in /Users/rob.jewell/code/open-source/forks/egjs-flicking/packages/vue-flicking/dist/flicking.esm.js

Syntax Error: Error: Failed to load plugin '@typescript-eslint' declared in '../../open-source/forks/egjs-flicking/.eslintrc.js#overrides[0]': Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- /Users/rob.jewell/code/toys/flicking-carousel-throttle/__placeholder__.js
Referenced from: /Users/rob.jewell/code/open-source/forks/egjs-flicking/.eslintrc.js
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at _normalizeObjectConfigData.next (<anonymous>)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at _normalizeObjectConfigData.next (<anonymous>)


 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& 15:0-46 26:14-22
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.117:8088&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

```

If I try to break down the error, I think the error is telling me that my forked flicking dependency is looking for typescript dependencies such as `@typescript-eslint/eslint-plugin` inside of [my vue project](https://github.com/robjewell-ibotta/flicking-carousel-throttle/pull/1) from where I am running `npm run serve`. I think this is what you are also saying here:
> I guess the eslint is searching @typescript-eslint from your project folder instead of the folder which fork of Flicking is in?

I find the error message to be strange because this fork should only be looking at its own dependencies -- and not the dependencies of the project which the dependency is being pulled into. Morever, my forked flicking dependency has all its dependencies installed via `npm run install`. 

When you say:
>Like, adding the Flicking fork folder to .eslintignore or something.


What do you mean exactly? Are you saying that I should enter the path to my vue project inside the `.eslintignore` of my forked flicking project? Or are you saying that in my Vue project I should add a `.eslintignore` and this file will contain a path to my forked flicking project?

**Comment by WoodNeck** [comment]
I meant adding `.eslintignore` in your Vue project. I didn't test it so I can't guarantee it works.
One solution might be installing missing eslint plugins in your Vue project.
Yeah, I know it's a messy solution but I think it's okay for testing.
Sorry but I can't help you further, as It's more of an eslint issue than Flicking.

**Comment by robjewell-ibotta** [comment]
@WoodNeck thank you for your support on this issue. This is [the weird stuff](https://github.com/robjewell-ibotta/flicking-carousel-throttle/pull/1/commits/6cbe19abbdb7f1fe8944ca6fbdf95cc04a617a0f) that I had to do in my vue2 js project locally to get the locally installed dependencies of flicking to move past the above Typescript errors.

Right now I'm seeing a new Flicking error in my vue 2 project when I run `npm run serve` from my vue 2 project:
```
Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

This is somewhat separate than the above original issue so I will close this one for now. 

Maybe I'm not so experienced in Typescript, but I find installing a bunch of typescript dependencies in the Vue2 (normal JS) project that is using flicking to be somewhat strange. 

I will also try the `.eslintignore` suggestion you made. Perhaps also adding either a `tsconfig.eslint.json` or a `tsconfig.json` may be a solution here. As you can probably tell, typescript is not one of my strengths.
