### ISSUE TITLE
Problema em produção que não tem em dev

### ISSUE THREAD

**Issue by WillTbn** [naver/egjs-flicking#477]
I have a production problem that doesn't reproduce in development.
My quick move is configured globally in main.js

I created the card with the help of the bootstrap and I'm using foreach to go through json (json / I won't put it here so it doesn't get big), but the capture is ok. but in development the cards are next to each other as desired, whereas when I run to production with the npm run build, the cards that were previously next to each other (side by side) are one below the other in a single column.

json/ I won't put it here so it doesn't get big;
```
<template>
    <Flicking :options="{ circular: true, defaultIndex: 1}" >
        <div class="mx-5" v-for="(perfil,index) in perfils" :key="index">
            <div class="card" style="width:18rem">
                <div class="card-header container">
                    <div class="row">
                        <div class="col-2 text-center">
                            <b-img :src="perfil.avatar" rounded="circle" width="55rem" height="55rem" alt="Circle image"></b-img>
                        </div>
                        <div class="col ml-3">
                            <h5>{{perfil.user_name}}</h5>
                            <p class="text-muted">{{perfil.avaliation}} avaliações</p>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <p class="card-text text-muted">{{perfil.description}}</p>
                    <span class="badge rounded-pill badge-minfo m-2 text-white">{{perfil.tags}}</span>
                    <span class="badge rounded-pill badge-minfo m-2 text-white">{{perfil.tags}}</span>
                    <span class="badge rounded-pill badge-minfo m-2 text-white">{{perfil.tags}}</span>
                    <div class="text-center">
                        <a href="#" class="card-link text-dark">Ver perfil ></a>
                    </div>
                </div>
            </div>
        </div>
    </Flicking>
</template>
<script>
export default {
    name: "Card",
    data: function(){
        return{
            perfils:[ json / I won't put it here so it doesn't get big; ]
        }
    }
    
}
</script>
```

**Comment by WoodNeck** [comment]
Hello @WillTbn!
Usually, in that case, there must be CSS missing for Flicking.
Check whether the `flicking.css` is loaded on your page.
If not, try adding it. See our [guide](https://naver.github.io/egjs-flicking/docs/quick-start) for how to it locally or globally :)

If it's not the CSS problem, I can help you with it if you give me which env you're using & a reproducible link(to your page or repo)

**Comment by WillTbn** [comment]
Hey, I put the Css files CDN Links in public, that's it. Funny that I used this as the first alternative after creating this issue. I'm glad it worked, I hope it will help those who are new to vue equal to min.

Hugs

**Comment by WoodNeck** [comment]
Glad you solved it 🤗

**Comment by himadrinath** [comment]
@WoodNeck in nextjs when i running in development mode every thing working fine but when i switch to production. css file missing. way?

**Comment by WillTbn** [comment]
This is the css part, here in vue I just called it in index.html in the plublic folder..
When vue.js runs npm run biuld it merges everything into this index.

I don't know how to apply it in next.js, but if it's so try to apply it

` <link rel="stylesheet" href="https://unpkg.com/@egjs/flicking/dist/flicking.css" crossorigin="anonymous" /> <link rel="stylesheet" href="https://unpkg.com/@egjs/flicking/dist/flicking-inline.css" crossorigin="anonymous" />
 `

**Comment by WoodNeck** [comment]
@himadrinath
It works normally on my production build, maybe it's next.js version issue or something?
I searched for similar issues, and found these:
- https://github.com/vercel/next-plugins/issues/177
- https://stackoverflow.com/questions/50149729/next-js-import-css-file-does-not-work
- https://stackoverflow.com/questions/51932288/next-js-stylesheet-is-not-loaded
- https://stackoverflow.com/questions/65627434/css-not-loading-in-production-mode-when-using-nextjs

Try their solutions :)

**Comment by himadrinath** [comment]
@WoodNeck Thanks I will check it out
