### ISSUE TITLE
How to add count in snap option in v4?

### ISSUE THREAD

**Issue by LungiO1** [naver/egjs-flicking#481]
## Description

In v3 there was the option "count" for movetype snap to limit the number of panels to move.
I am trying to upgrade to v4 but cant find the option to do that.

Did I miss this option somewhere? Is it planned to implement snap count again in the future?

**Comment by LungiO1** [comment]
Thanks for your reply.
Is there a estimated time when this feature will be implemented in v4?

**Comment by WoodNeck** [comment]
I'm currently working on this, and It'll be released in mid-August with other new features :)

**Comment by WoodNeck** [comment]
I've added the `count` option in the new release(v4.2.1), please use that :)
