### ISSUE TITLE
Error with NgxFlicking (latest version) on new blank angular project (v12)

### ISSUE THREAD

**Issue by GitHubish** [naver/egjs-flicking#482]
problem in the definition apparently?

```
Error: node_modules/@egjs/ngx-flicking/lib/ngx-flicking.component.d.ts:14:32 - error TS2307: Cannot find module '@egjs/component/declaration/types' or its correspondi
ng type declarations.

14     ready: EventEmitter<import("@egjs/component/declaration/types").DefaultProps<"ready", NgxFlickingComponent>>;
```

**Comment by GitHubish** [comment]
the problem comes from `@egjs/ngx-infinitegrid` (currently **version 3.2.5**). When I add it to the project, the necessary files in the folder `\node_modules\@egjs\component\declaration` are deleted as soon as I add this dependency, especially the famous `types.d.ts` file. 

https://github.com/naver/egjs-infinitegrid/issues/408

**Comment by daybrush** [comment]
@GitHubish 

Would you like to check if it works with `npm ci`? It seems that node_modules is not properly updated.

If that doesn't work, We'll have to update all @egjs/component.

**Comment by GitHubish** [comment]
Thank you for your answer. Unfortunately same problem using `npm ci`. The error is still there :(

it's long / tedious to udpate all the `egjs/components` ?

**Comment by daybrush** [comment]
@GitHubish 

Test `@egjs/ngx-flicking@4.1.2-beta.0`

**Comment by GitHubish** [comment]
@daybrush It works! Thank you!
