### ISSUE TITLE
v4 - Triggers `onMoveEnd` event at initial rendering

### ISSUE THREAD

**Issue by zprime0920** [naver/egjs-flicking#486]
## Description

`onMoveEnd` event is triggered at initial rendering on v4. v3 does not trigger `onMoveEnd` at initial rendering. In my opinion, user did not move anything, so event should not be triggered. Did I miss some configuration? or, is this behavior intended?

## Steps to check or reproduce

See the console log in [this codesandbox](https://codesandbox.io/s/egjsflicking-v4-on-move-end-43kmk?file=/src/App.js)

**Comment by mixed** [comment]
This issue needs the opinion of the member in charge, so it will take some time. The member in charge is on vacation, so I will reply to you next week. :)

**Comment by WoodNeck** [comment]
Hello @zprime0920!
Well, that's not intentional I think we can see it as a bug. I'll fix that :)

**Comment by WoodNeck** [comment]
Hello! I've fixed this in the new release (v4.2.1), please try that :)
