### ISSUE TITLE
ERROR Declaration or statement expected

### ISSUE THREAD

**Issue by robjewell-ibotta** [naver/egjs-flicking#488]
## Description
I'm seeing errors like this in flicking node modules when running `vue-cli-service build`:
```
ERROR in /Users/rob.jewell/code/projects/website/node_modules/@egjs/flicking-plugins/declaration/pagination/renderer/index.d.ts(2,1):
2:1 Declaration or statement expected.
    1 | import Renderer from "./Renderer";
  > 2 | export type { Renderer };
      | ^
    3 |
```

Currently, my project is using:
 "vue": "^2.6.11",
"typescript": "3.7.4"
"@egjs/flicking": "^4.1.0",
"@egjs/flicking-plugins": "^4.1.0",
"@egjs/vue-flicking": "^4.1.0",

Any idea what the issue could be?  Looks like I fixed the error by bumping the project's typescript dependency to `3.9.10`. Is updating Typescript to this version 3.9.10 ok for the flicking dependencies I am using? If just bumping the typescript dependency to `3.9.10` fixes the issue, perhaps there should be a warning about older versions of typescript in this project?

**Comment by WoodNeck** [comment]
Hello @robjewell-ibotta! You're right that it needs typescript dependency updated.
We might have to add a warning about that, thanks for the suggestion.
