### ISSUE TITLE
The slide not working well

### ISSUE THREAD

**Issue by BeratS** [naver/egjs-flicking#491]
https://guides.github.com/features/mastering-markdown/

https://user-images.githubusercontent.com/7864218/126079809-517198c1-4dbd-4ea1-ae7e-e82dae428856.mp4

**Comment by WoodNeck** [comment]
Hello @BeratS!
We're aware of this issue. I'll fix that soon, maybe it needs dependency to be updated though.

**Comment by WoodNeck** [comment]
I've fixed this problem in the new release (v4.2.1), please reopen this issue when if this continues to occur :)

**Comment by BeratS** [comment]
Thank you @WoodNeck for the fix and a quick response.

**Comment by BeratS** [comment]
It's good but occurred again to me that flip that prevents to go to the next slide or previous.

**Comment by WoodNeck** [comment]
@BeratS Can you tell me in which particular case it is?

**Comment by BeratS** [comment]
Just try to move the slides, open the demo page from the site you will see it.
as I am using now for now https://flickity.metafizzy.co/ try make the difference.

**Comment by WoodNeck** [comment]
Yeah, maybe the logic for choosing the current base panel can be improved. Thanks for your opinion!
I'll try to improve that :)

**Comment by WoodNeck** [comment]
@BeratS Okay I was super dumb, and didn't update the demo page with the newest Flicking.
It was using the previous version(4.1.1) and the same thing did happen.
I've just updated the demo page with the latest Flicking. I hope you'll like it now :)

**Comment by BeratS** [comment]
Good Job @WoodNeck , thank you, appreciate your work.

**Comment by WoodNeck** [comment]
Thanks 👍 
I'll close this issue then
