### ISSUE TITLE
Flicking pagination not appearing.

### ISSUE THREAD

**Issue by aknegtel** [naver/egjs-flicking#492]
Hello, I've been trying to implement the pagination plugin in React (Next.js) without success although it seems to me that I've done everything correctly. Maybe there's something I'm missing. 

I'll attach 3 screenshots, the first is the result, clearly without the pagination. The second is the code, where you can see I have implemented it. The third is the inspector where you can see the classes of the flicking-pagination are there, but there is no content in the flicking-pagination div.

[![result](https://user-images.githubusercontent.com/36228067/126310080-8a2fbb6d-e25a-41ab-ace2-39c833a77139.png)](url)

<img width="1369" alt="code" src="https://user-images.githubusercontent.com/36228067/126310265-ab147a31-c14e-494e-ac59-a17a00a807bc.png">

<img width="1257" alt="devtools" src="https://user-images.githubusercontent.com/36228067/126310841-0c6f1820-e20c-4ab9-a926-3a0762ee81f5.png">

Any help would be appreciated, thanks!

**Comment by WoodNeck** [comment]
Hello @aknegtel!
That's weird, I guess it's a timing issue or something?

1. Wasn't there any errors?
2. Can you check it by calling the `update()` after Flicking's initialized, and whether the bullets are generated?

**Comment by aknegtel** [comment]
Hey, thanks for the quick response.

1. No, no errors.
2. Getting an undefined error I guess comes because there are no bullets (?)

<img width="1550" alt="Captura de pantalla 2021-07-20 a las 15 15 43" src="https://user-images.githubusercontent.com/36228067/126330844-65a17dcb-aa7d-4dd3-89cc-3959f4c77488.png">

**Comment by WoodNeck** [comment]
By seeing the log, looks like the plugin's `init` is not called.
It's normally called when the react-flicking's mounted, but some whatever reason that isn't.
Can I get a link to that repo or any reproducible code for this issue?

**Comment by aknegtel** [comment]
@WoodNeck I created a subset of the site including only the page with the example.
I hope it works. Just `npm install` and then `npm run dev`

https://github.com/aknegtel/flicking-xtone

**Comment by WoodNeck** [comment]
I've just tested your demo, and looks like the pagination plugin is re-evaluated and removed when the page's rendered.
Simply, you can fix it like this:

```jsx
  useEffect(() => {
    if (inView) {
      controls.start("visible");
    }
    if (!inView) {
      controls.start("hidden");
    }
    flicking.current.on("ready", (e) => {
      e.currentTarget.addPlugins(new Pagination({ type: "bullet" }));
    });
  }, [inView, controls]);

```

Note that I've removed `plugins` variable in your code.

**Comment by aknegtel** [comment]
Thank you, works!
