### ISSUE TITLE
Dynamic children errors with `Cannot read property 'key' of undefined`

### ISSUE THREAD

**Issue by matthewlein** [naver/egjs-flicking#506]
## Description
Having a dynamic children will cause errors in flicking. Is this meant to be supported? As a workaround, you can generate a key based on the children, so it will mount a new component when children change, but this is not ideal.

## Steps to check or reproduce
In this sandbox, the children are randomly generated every second. If you remove the `key` on `<Flicking>`, it will cause an error pretty quickly.
https://codesandbox.io/s/restless-butterfly-ttl8g?file=/src/App.tsx

**Comment by WoodNeck** [comment]
Hello @matthewlein! Thanks for reporting the bug.
I found that there was a mistake in our `sync` method, which does not properly remove the given panels by the jsx diff so the `undefined` is generated as a ghost panel.
I'll fix this asap :)

**Comment by matthewlein** [comment]
Awesome, glad you could figure it out so quickly
