### ISSUE TITLE
New feature - panelsPerView

### ISSUE THREAD

**Issue by WoodNeck** [naver/egjs-flicking#507]
## Description
By enabling `panelsPerView`, Flicking will force modify panel sizes to show exactly n panels in one screen

**Comment by hellojt9040** [comment]
Am trying to update the value of "panelsPerView" on window resize, but even if the value is changed("panelsPerView" property of Flicking is updated) in the new render cycle, new "panelsPerView" is not reflecting. Need help.

Is there any specific way to update??

**Comment by WoodNeck** [comment]
Hello @hellojt9040!
When the `autoResize` option is enabled, Flicking will automatically call resize when `window.resize` occurs.
You can receive `beforeResize` event of Flicking, then change the `panelsPerView` in it.

Or, you can manually update the panel's sizes by calling
```js
flicking.renderer.updatePanelSize();
```

Choose what you think is better :)
