### ISSUE TITLE
Cannot read property 'currentStyle' of null

### ISSUE THREAD

**Issue by matthewlein** [naver/egjs-flicking#514]
## Description
Locally I have seen this error a few times, and now I'm seeing it occasionally in production error reporting.

I have looked at this almost identical error: https://github.com/naver/egjs-flicking/issues/485 but there are no duplicate reacts or anything like that in package-lock.

## Steps to check or reproduce
This is the code that is erroring. `el` is null or undefined at times.
```
 var getStyle = function(el) {
   return window.getComputedStyle(el) || el.currentStyle;
 };
```

I believe generating a key based on children prevents this error from causing any user problems, but I'm not 100% sure on that. It's a rare error and I haven't figured out a way to reproduce it.

**Comment by WoodNeck** [comment]
Hello @matthewlein!
Can I ask you which env you're using?
Or, can I get a repo URL for the reproduction of the issue? It would be really helpful :)

**Comment by matthewlein** [comment]
Incredibly, I found a reproducible case today in production.

It seems like it has to do with:
- rendering the flicking component with children
- having a duplicate key (by accident)
- possibly having arrows

https://codesandbox.io/s/brave-night-bokrd?file=/src/App.tsx

I can get it to happen by changing the letters in the `items` array, like `["a", "b", "a", "c", "d", "e"];` to `["a", "a", "a", "c", "d", "e"];`

The error message is not identical, but it's happening at the same place in the code. I think it's the same issue.

![Screen Shot 2021-08-12 at 11 05 37 AM](https://user-images.githubusercontent.com/454758/129230240-ebae3fcd-9d2f-4b37-bc8e-a0fda873226c.png)

So that would explain why it's rare, duplicate keys are very unlikely.

**Comment by matthewlein** [comment]
Even changing the heading text will trigger it. So I'd guess it happens in rerendering, not the initial render.

**Comment by WoodNeck** [comment]
That's good. I'm glad you figured out the cause.
I guess it's not an issue then? As the duplicated keys must be avoided under any circumstances.

**Comment by matthewlein** [comment]
I suppose it's up to you. React itself doesn't blow up with an error when you have duplicate keys. It can cause some weird rendering issues sure, but it doesn't cause an unrecoverable error.

My preference would be to not break everything if it happens. 

Although its a good way to find accidental duplicates coming from the database... 😈

**Comment by WoodNeck** [comment]
@matthewlein 
I think I have to discuss it with my team, but in my opinion, to prevent further problems I think Flicking should not work when duplicated keys are detected. Well, throwing a warning or error at least should be a one solution I guess 👍

**Comment by victorsferreira** [comment]
same error occurred with me but keys are not duplicated
if I render an imported component instead of a React Tag, it triggers the error

**Comment by WoodNeck** [comment]
@victorsferreira
Hello, can you provide me with some more explanation for the issue? :)
