### ISSUE TITLE
Attempted import error: 'DIRECTION' is not exported from '@egjs/flicking'. #21

### ISSUE THREAD

**Issue by githuber1112** [naver/egjs-flicking#517]
## Description
anyone can help ?

**Comment by WoodNeck** [comment]
Hello @githuber1112!
Can I ask you which env / code / version of Flicking you're using?

**Comment by githuber1112** [comment]
I am using the latest React Flicking 3.7.3

**Comment by WoodNeck** [comment]
I found out that 3.7.3 was released as `latest` by mistake.
Please re-install Flicking by
```sh
npm i @egjs/flicking@latest
```
and this will fix the issue.
