### ISSUE TITLE
좀 더 다양한 데모가 필요합니다./We need some more diverse demos.

### ISSUE THREAD

**Issue by hiuny** [naver/egjs-flicking#525]
## Description

`swiper.js`를 사용중인데, `@egjs/flicking`으로의 전환을 검토하고 있습니다. 하지만 demo의 개수가 swiper.js에 비해 현저히 적어, @egjs/flicking이 swiper.js를 완전히 대체를 할 수 있을지 아닐지 가늠이 되지 않는 부분이 상당수 있습니다. swiper.js의 demo를 1:1로 매칭하여 제작해주시면 많은 도움이 될 것 같습니다.

**p.s**  
특히 swiper.js의 [virtual slides](https://swiperjs.com/demos#virtual-slides) 기능을 구현할 수 있는지 확인이 필요합니다.

--

I'm using `swiper.js`, but I am considering switching to `@egjs/flicking`. However, the number of demos is significantly smaller than that of swiper.js, so there are many parts where it is not clear whether @egjs/flicking can completely replace swiper.js. It would be very helpful if you create a 1:1 matching demo of swiper.js.

**p.s**  
Specifically, you need to make sure that you can implement the [virtual slides](https://swiperjs.com/demos#virtual-slides) feature of swiper.js.

**Comment by WoodNeck** [comment]
I can't make all demos in swiper.js, but I'm trying to create as much as I can.
For virtual slides, Flicking doesn't offer that feature.
But, you can just create new panels with `needPanel` event and show only part of them with `renderOnlyVisible`
Also, you can use the `panelsPerView` and `noPanelStyleOverride` for performance reason :)
