### ISSUE TITLE
api 참조 문서의 Options 페이지에 default값이 표기되어 있으면 좋을 것 같습니다./It would be good if the default value is indicated on the Options page of the api reference document.

### ISSUE THREAD

**Issue by hiuny** [naver/egjs-flicking#526]
## Description
https://naver.github.io/egjs-flicking/docs/api/Flicking 이 페이지에서 default값을 확인할 수 있긴 하지만, [Options](https://naver.github.io/egjs-flicking/Options) 페이지에는 default값이 명시가 되어 있지 않아서 두 페이지를 왔다 갔다하며 확인해야 하는 불편함이 있습니다. 사소한 것이긴 한데, Options 페이지 내용에도 모든 option들에 대해 default값이 명시되어 있으면 좋을 것 같습니다.

https://naver.github.io/egjs-flicking/docs/api/Flicking Although you can check the default value on this page, [Options](https://naver.github.io/egjs-flicking/Options) The default value is not specified on the page, so it is inconvenient to have to go back and forth between two pages to check. It's a minor thing, but it would be nice if the default values for all options were specified in the Options page as well.

**Comment by WoodNeck** [comment]
Hello @hiuny!
That's a good suggestion :)
Mostly, the first one of each is the default value, but it would be better if it's marked as default.
I should find a way to show it more intuitively

**Comment by hiuny** [comment]
네, 그렇군요~ 그렇다면 Options 페이지 첫 머리에 '처음으로 표기된 것이 default 값임' 이라고 표기만 해놓아도 좋을 것 같습니다.

Yes, that's right~ If so, it would be good to just write 'The first displayed value is the default value' at the beginning of the Options page.
