### ISSUE TITLE
홈페이지에서 API 페이지에서만 한국어 변환이 되는 것 같습니다./It seems that Korean translation is only available on the API page on the homepage.

### ISSUE THREAD

**Issue by hiuny** [naver/egjs-flicking#527]
## Description
[홈페이지](https://naver.github.io/egjs-flicking/)에서 [API](https://naver.github.io/egjs-flicking/docs/api/Flicking) 페이지만 한국어 변환이 되는 것 같습니다. 다른 페이지에 한국어 변환이 없는 것이 스펙이라면 API 페이지에만 언어 변환 UI를 두는 것이 좋을 것 같습니다. (현재 상태는 버그로 인식되기에..)

Only the [API] (https://naver.github.io/egjs-flicking/docs/api/Flicking) page in [Homepage] (https://naver.github.io/egjs-flicking/) is translated into Korean. Seems to. If the specification is that there is no Korean translation on other pages, it would be better to have the language conversion UI only on the API page. (The current state is recognized as a bug..)

**스크린샷1** - Docs 페이지가 한국어로 변환되지 않은 모습  
**Screenshot 1** - Docs page not translated into Korean
![image](https://user-images.githubusercontent.com/2697067/130540061-5fe33277-f7cb-4eba-9727-f78596eb3f7a.png)

**Comment by WoodNeck** [comment]
That's not a bug, but we just don't have the actual Korean translation of that pages.
As that's controlled by the docusaurus template, we can't remove the language change button.
The best way is to actually translate the pages to other languages, I'll try that when I have some time :)

**Comment by hiuny** [comment]
아, 그렇군요! 수고스럽겠지만, API외의 페이지도 한국어로 나오는 것이 best이겠네요~

Oh, I see! Sorry for the trouble, but it would be best if the pages other than the API are also available in Korean~

**Comment by WoodNeck** [comment]
Sure, it's just a matter of time for me to create one :)
