### ISSUE TITLE
홈페이지 API페이지의 항목들이 abc 오름차순으로 정렬되면 좋을 것 같습니다./It would be nice if the items on the homepage API page were sorted in ascending abc order.

### ISSUE THREAD

**Issue by hiuny** [naver/egjs-flicking#528]
## Description
API페이지의 항목들이 abc 오름차순으로 정렬되어 있지 않아서 탐색하기가 불편한 것 같습니다. abc 오름차순으로 정렬되어 있으면 좋을 것 같습니다.

It seems that the items on the API page are not sorted in ascending abc order, so it is inconvenient to navigate. It would be nice to have abc sorted in ascending order.

**스크린샷1** - 홈페이지 API페이지의 항목들.
**Screenshot 1** - Items on the homepage API page.
![image](https://user-images.githubusercontent.com/2697067/130553680-5f456d9f-d87e-4e67-be0b-293800afd349.png)

**Comment by WoodNeck** [comment]
That's a good idea, I should modify our document generator
