### ISSUE TITLE
incompatible with angular 12.2.2

### ISSUE THREAD

**Issue by Parsa-Sedigh** [naver/egjs-flicking#530]
## Description
When I try to update my angular project to 12.2.2 by using `ng update` command, I get:
`
Package "@egjs/ngx-flicking" has an incompatible peer dependency to "@angular/common" (requires "^7.2.0" (extended), 
would install "12.2.2").
Package "@egjs/ngx-flicking" has an incompatible peer dependency to "@angular/core" (requires "^7.2.15" (extended), would 
install "12.2.2").

× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.

`

**Comment by WoodNeck** [comment]
Hello @Parsa-Sedigh!
I found out that our peer dependencies in package.json was not updated.
I've just made a PR that fixes this issue (#532) :)

**Comment by Parsa-Sedigh** [comment]
Thanks!
