### ISSUE TITLE
전후관계의 이벤트 이름의 포맷을 통일하였으면 합니다./I would like to unify the format of the event name in the context.

### ISSUE THREAD

**Issue by hiuny** [naver/egjs-flicking#533]
## Description
통일했으면 하는 이벤트는

- `beforeResize`(전)/`afterResize`(후)
- `willChange`(전)/`changed`(후)

입니다. 이 전후관계 이벤트 이름이 통일되어 있지 않아서 헷갈리기도 하고 유추가 어렵고 모듈의 완성도를 떨어트리는 것 같습니다. window에 `beforeunload`/`unload`이벤트가 있는데 이를 참조하여 각각 아래 처럼 제안드립니다.

- `beforeResize`(전)/`resize`(후)
- `beforeChange`(전)/`change`(후)

---

Events to be unified

- `beforeResize`(before)/`afterResize`(after)
- `willChange` (before)/`changed` (after)

is. Since the names of these context events are not unified, it is sometimes confusing and difficult to infer, and it seems to reduce the completeness of the module. There are `beforeunload`/`unload` events in window.

- `beforeResize`(before)/`resize`(after)
- `beforeChange` (before)/`change` (after)

**스크린샷1** - Event 목록  
**Screenshot 1** - Event List
![image](https://user-images.githubusercontent.com/2697067/130724504-b2cb489f-2b80-4536-b836-ab5f4fb0f988.png)

**Comment by WoodNeck** [comment]
Thanks for the suggestion. There's actually a reason for the name difference.
While the `resize` event happens immediately from `beforeResize` to `afterResize`, `change` event has some term between `willChange` and `changed`, which actually can be interpreted as `animationStart` and `animationEnd`.

But if that's still confusing, we'll consider changing them on the next major version :)

**Comment by hiuny** [comment]
아~ 동기/비동기의 차이가 있었군요. 동기의 경우는 `before`, 비동기의 경우는 `will`로 명명이 되었나 보네요. 접두어 만으로 동기/비동기의 구분을 하는 것이 일반적인지 아닌지 잘 모르겠지만, 사용자가 이 구분을 이해하기 쉽게 api 참조 문서에 설명을 보강해주셔도 좋을 것 같습니다. 다만 이 경우에도 change이벤트의 전후 이름은 `willChange`/`change`로 하는 것은 어떨지 의견드립니다.

---

Ah, there is a difference between synchronous/asynchronous. It seems to be named `before` in the case of synchronous and `will` in the case of asynchronous. I'm not sure whether it is common to distinguish between synchronous/asynchronous only with prefixes, but I think it would be good to reinforce the explanation in the api reference document to make this distinction easier for users to understand. However, even in this case, I would like to advise you on how to change the names before and after the change event to `willChange`/`change`.

**Comment by WoodNeck** [comment]
Good, I'll discuss it with our team :)
