### ISSUE TITLE
state 변경이 화면에 늦게 반영됩니다

### ISSUE THREAD

**Issue by yang-sw** [naver/egjs-flicking#538]
## Steps to check or reproduce

https://codesandbox.io/s/new-hill-lrqoe?file=/src/DemoComponent.tsx

플리킹 내부의 버튼을 클릭하면 현재 누른게 아닌 직전에 누른 state로 화면이 변경됩니다.
v4 꼭 쓰고싶은데 확인 부탁드립니다..!

**Comment by WoodNeck** [comment]
Hello @yang-sw!
Found out that this is a bug because Flicking uses old(removed) element.
I've just made a PR that fixes this issue :)

**Comment by WoodNeck** [comment]
I've released a new version (v4.2.5) that fixes this issue. Please try that :)
