### ISSUE TITLE
Autoplay Bug React (Slides once, then stops)

### ISSUE THREAD

**Issue by daleSOCI** [naver/egjs-flicking#545]
### Discussed in https://github.com/naver/egjs-flicking/discussions/544

<div type='discussions-op-text'>

<sup>Originally posted by **daleSOCI** September  1, 2021</sup>
I've tried implementing autoplay in React, and I've followed the ultra basic source from the [Plugins docs](https://naver.github.io/egjs-flicking/Plugins). Here's a sandbox link: https://codesandbox.io/s/quirky-brown-hf593?file=/src/App.js

For some reason it autoplays from slide one to two, then stops working. Am I missing something here?</div>

**Comment by WoodNeck** [comment]
Ref #544
