### ISSUE TITLE
Video player control issue in the flicking panel.

### ISSUE THREAD

**Issue by do2bly** [naver/egjs-flicking#551]
## Description
We are using the `@egjs/react-flicking 3.2.1` version of Flicking.
I experienced an issue where flicking slides when controlling the see bar of the video player in the flicking panel.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/49511407/132787568-2da7d87e-6b46-4c3f-a99e-a9582031a324.gif)

I think delegate flicking events. Can you give me advice?

**Comment by WoodNeck** [comment]
Hello @do2bly!
Can you add an event handler on the slider element?
Adding event handler with a call of `stopPropagation()` at `touchstart` and `mousedown` can resolve this issue I guess

**Comment by do2bly** [comment]
@WoodNeck 
Is there a sample code or example that I can refer to?

**Comment by WoodNeck** [comment]
@do2bly 
It's simple.
```js
const targetEl = document.querySelector("css-selector-to-the-video-bar-el");

targetEl.addEventListener("mousedown", e => {
  e.stopPropagation();
});
```
