### ISSUE TITLE
Cannot scroll when vertical with bound is true 

### ISSUE THREAD

**Issue by chiquitta** [naver/egjs-flicking#552]
Hi, I want to use Vertical and set Bound is true, but I found that it cannot scrollable.
Please help, Thanks.

**Comment by chiquitta** [comment]
> Hi, I want to use Vertical and set Bound is true, but I found that it cannot scrollable.
> Please help, Thanks.

Sorry, I realize that it need to manual setting circular=false, then it will work perfectly

**Comment by WoodNeck** [comment]
Hello! Glad you solved this issue :)
I'll close this issue then, feel free to reopen it when you think it's needed.
