### ISSUE TITLE
Horizontal scroller has problems?

### ISSUE THREAD

**Issue by nikitafloy** [naver/egjs-flicking#553]
## Description
Hello! I use: https://naver.github.io/egjs-flicking/Demos#horizontal-scroller

But i have a lot of problems:
1) Scroller is vertical, but i expect it only horizontal
2) I have horizontal scroll when use this example (bottom page)
3) Elements aren't hidden under the inner block
4) This I have on my site:
![Снимок](https://user-images.githubusercontent.com/31541586/133708403-ca42aed5-0d82-4efc-8ca7-2baee7557b01.PNG)

And many examples, which i use - only vertical scroll for me
Where am I wrong?)

## Steps to check or reproduce
https://codesandbox.io/s/objective-brattain-psj2k?file=/src/App.j

**Comment by WoodNeck** [comment]
Hello @nikitafloy!
You should add our CSS file to your site.
```js
import @egjs/react-flicking/dist/flicking.css";
```

**Comment by nikitafloy** [comment]
> Hello @nikitafloy!
> You should add our CSS file to your site.
> 
> ```js
> import "@egjs/react-flicking/dist/flicking.css";
> ```

Yes, this work perfect with my example, but not with my current project 😂
I'll check my css styles, thanks🤝🏻

**Comment by nikitafloy** [comment]
Ok, i get problems with functional components:
https://codesandbox.io/s/agitated-panini-gvw25

**Comment by nikitafloy** [comment]
Ok, problem in webpack)
It works for me: https://github.com/webpack/webpack/issues/6571

**Comment by ohienstephen** [comment]
> Ok, problem in webpack) It works for me: [webpack/webpack#6571](https://github.com/webpack/webpack/issues/6571)

can seem to make my work. how did you fix this exactly
