### ISSUE TITLE
The problem occurs when switching from the PC screen to the mobile screen.

### ISSUE THREAD

**Issue by shinyuna** [naver/egjs-flicking#554]
## Description

PC 화면에서 개발을 하다가 모바일 뷰를 확인하고 싶어 개발자 도구의 디바이스 툴로 모바일 화면을 확인 할 때 스크롤이 먹지 않거나 
Unhandled Rejection (FlickingError): Position "413.48033148631026" is not reachable. 이런 에러가 발생합니다. 

## Steps to check or reproduce

https://user-images.githubusercontent.com/19729134/133914394-c9c308ac-581b-494b-8831-4e1d758c0dda.mov

**Comment by WoodNeck** [comment]
Hello @shinyuna!
That's because the input types are being changed when the mobile mode is turned on / off.
Please refresh the page if it happens.
As this won't happen in the real end-user situation, we won't fix this issue for now.
