### ISSUE TITLE
Angular: Rendering with SSR fails with 'document is not defined' 

### ISSUE THREAD

**Issue by nkrass** [naver/egjs-flicking#555]
## Description
While developing with ngx-flicking version 4.3.0 and using SSR and packaging with webpack fails with 'document is not defined'
in LinearCamera.Camera._checkTranslateSupport in server bundled (dist/server.js).
Angular 12.2.2
Default angular bundler
 
## Steps to check or reproduce
`<ngx-flicking [hideBeforeInit]="true" [firstPanelSize]="'200px'" [options]="{ gap: 10, moveType: 'freeScroll' }"><div class="panel"></div><div class="panel"></div></ngx-flicking>`

**Comment by WoodNeck** [comment]
Hello @nkrass!
I've just tested ngx-flicking on Angular universal, and had the same issue as you.
I made a PR that fixes this issue(#557), and it will be released at the next version :)

**Comment by WoodNeck** [comment]
Hello! I've just released @egjs/ngx-flicking v4.3.1 that fixes this issue. Please try that :)
