### ISSUE TITLE
Can't drag to next panel on first page load

### ISSUE THREAD

**Issue by Frostype** [naver/egjs-flicking#556]
I'm using Vue 2 and on first page load I'm unable to drag to the next panel, but if i refresh the page or even resize the browser window, it then works. How can i fix this?

**Comment by Frostype** [comment]
This is appearing in the console:

_[Vue warn]: Property or method "onMoveEnd" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property._

Is this causing the issue?

**Comment by Frostype** [comment]
Resolved by setting panel width

**Comment by HugoCastelli** [comment]
Hi, how to set panel width ?
