### ISSUE TITLE
on PC...

### ISSUE THREAD

**Issue by Lumia1108** [naver/egjs-flicking#56]
플리킹 ui 쓰면 PC에서 볼때 이렇게 보입니다.
If I use Flicking ui , it looks like this below picture on PC

![d](https://user-images.githubusercontent.com/20782897/33512526-b08e66e2-d775-11e7-8143-c1a4c2cf35bd.JPG)

**Comment by netil** [comment]
@Lumia1108, in most cases this issue is related on element's height.
Check if the height values is correctly applied.
