### ISSUE TITLE
Failed to execute 'getComputedStyle'

### ISSUE THREAD

**Issue by dukesx** [naver/egjs-flicking#561]
## Description
Error comes on Next js 11.1 , Using default config.

Full error: 
```
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'
```

Picture: 
![err](https://user-images.githubusercontent.com/5988991/137184907-a8e1d15e-e1b5-4a43-8c3c-7b2420d40f99.png)

## Steps to check or reproduce
1. Install v4.3.0
2. No plugins
2. Next js 11.1
3. Use default config from this page: https://github.com/naver/egjs-flicking/blob/master/packages/react-flicking/README.md
4. make sure to use it in a "pages" component

**Comment by victorsferreira** [comment]
did you manage to find a solution for this one?

**Comment by adarshaacharya** [comment]
@dukesx what was the solution for this, facing same problem :)
