### ISSUE TITLE
Any plans to support resize when rotated?

### ISSUE THREAD

**Issue by fed-gren** [naver/egjs-flicking#564]
## Description

I set the autoResize option to true to resize the panel when rotated, but it will behave unintentionally if the address bar size is changed in safari. Are there any plans to add an interface that actually calls resize on rotate?

**Comment by WoodNeck** [comment]
Thanks for the suggestion @fed-gren 👍!
As it is impossible to separate resize events triggered by address bar resize, I think it would be a nice approach to add support for using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) for the container element.

I don't sure when it's possible to add one, but I'll do sure work on this as it looks pretty promising for an environment like mobile.
