### ISSUE TITLE
Nuxt.js static site not displaying component correctly

### ISSUE THREAD

**Issue by lazaroofarrill** [naver/egjs-flicking#573]
## Description
the component works on dev mode but not in static mode. Items appear stacked on top of each other.

## Steps to check or reproduce
```
<flicking
        :plugins="plugins"
        :options="{ circular: circular, moveType: 'snap', inputType: ['touch', 'mouse', 'pointer'], align: 'prev' }"
        :viewportTag="'div'"
        :cameraTag="'div'"
        ref="flicking">
        <slot></slot>
      </flicking>
```

 "nuxt": "^2.15.7",
   "@egjs/vue-flicking": "^4.3.1",

**Comment by FollowJack** [comment]
For everyone that faced this problem
In nuxt.config.js

  css: [
    '@egjs/flicking/dist/flicking.css',
    '@egjs/flicking/dist/flicking-inline.css',
  ],
