### ISSUE TITLE
Cannot read properties of null (reading 'show')

### ISSUE THREAD

**Issue by eatdesignlove** [naver/egjs-flicking#576]
## Description
Hello, 
installed this package for the project I was working on, but i have difficulty to proceed the work due to the following error in the development mode.

I'm not sure if it's a problem with my development environment or an internal error in the package! Please review it.

![스크린샷 2021-11-03 오전 10 09 11](https://user-images.githubusercontent.com/10573105/139980428-4673fadd-3bb3-43be-a137-39a9ab5cc325.png)

## Steps to check or reproduce
1. npx create-react-app my-app (react @17.0.2)
2. npm install @egjs/react-flicking (@4.4.0)
3. import Flicking component in App.js 
4. npm run start (Development mode)

**Comment by WoodNeck** [comment]
Hello @eatdesignlove!
I've found out that this is a bug triggered when you're in React's `StrictMode` in the new version of react-flicking.
I'll fix this asap, until then you can either disable `StrictMode` or downgrade our module to v4.3.2 :)

**Comment by eatdesignlove** [comment]
@WoodNeck 
Thank you for answering so fast! 🙏
