### ISSUE TITLE
Vue3 installation docs do not seem to work

### ISSUE THREAD

**Issue by gtidevs** [naver/egjs-flicking#578]
## Description
I have included the CDN for Vue3 in my jsFiddle below and I copy pasted the instructions from the demos and it does not work. Please advise on how to get this working. I may be doing something wrong but I am not sure what it is.

## Steps to check or reproduce
https://jsfiddle.net/pf67nxe1/

**Comment by WoodNeck** [comment]
Hello @gtidevs!
I've just checked your fiddle, and looks like you're using the Flicking for vanilla JS not Vue3.
You should install `@egjs/vue3-flicking`, not `@egjs/flicking`
Flicking currently offers cjs & esm module for Vue3, which means you should use an additional bundler like webpack or rollup to use it.
Normally, if you use Vue3 with [vue-cli-service](https://cli.vuejs.org/guide/cli-service.html#using-the-binary) it will do that for you.

**Comment by gtidevs** [comment]
Hi @WoodNeck thank you very much for your response. Is there a CDN link for `vue3-flicking`? I do not have server access to use yarn or npm to install via command line.

**Comment by WoodNeck** [comment]
I think it's hard to use vue3-flicking without bundlers.
But at least you can try it with the current Flicking(`@egjs/flicking`) you're using.

```html
<div id="wrapper" class="flicking-viewport">
  <div class="flicking-camera">
    <span class="button mr-2 is-white">🍎 Apple</span>
    <span class="button mr-2 is-white">🍉 Watermelon</span>
    <span class="button mr-2 is-white">🥝 Kiwi</span>
    <span class="button mr-2 is-white">🍎 Apple 2</span>
    <span class="button mr-2 is-white">🍉 Watermelon 2</span>
    <span class="button mr-2 is-white">🥝 Kiwi 2</span>
    <span class="button mr-2 is-white">🍎 Apple 3</span>
    <span class="button mr-2 is-white">🍉 Watermelon 3</span>
    <span class="button mr-2 is-white">🥝 Kiwi 3</span>
  </div>
</div>
```

```js
app.mount("#main");

// Create new vanilla.js Flicking
const flicking = new Flicking("#wrapper", { moveType: "freeScroll", bound: true });
```

As it is just using a vanilla.js Flicking, it will not respond to the internal panel(element) and options change.
