### ISSUE TITLE
Unhandled Rejection (TypeError): this._getPanelAlign is not a function

### ISSUE THREAD

**Issue by ababurak92** [naver/egjs-flicking#579]
## Description
Hello i wanted to try it but i'm getting error.

### Error : 

`  
/node_modules/@egjs/react-flicking/dist/flicking.esm.js/ReactRenderer</__proto._collectPanels
src/react-flicking/ReactRenderer.ts:50
Unhandled Rejection (TypeError): this._getPanelAlign is not a function
47 | }
  48 | 
  49 | protected _collectPanels() {
> 50 |   const align = this._getPanelAlign();
     | ^  51 |   const children = this._reactFlicking.reactPanels;
  52 | 
  53 |   this._panels = children.map((panelComponent, index) => new ReactPanel({`

### Code what i used 

import React  from 'react'
import Flicking, { MoveEvent, WillChangeEvent } from "@egjs/react-flicking";

const Try = () =>{
    return(
        <Flicking
            viewportTag = "div"
            cameraTag = "div"
            align = "center"
            onMove = {(e: MoveEvent) => {}}
            onWillChange = {(e: WillChangeEvent) => {}}
            horizontal = {true}
            circular = {true}
        >
            <div>panel 0</div>
            <div>panel 1</div>
            <div>panel 2</div>
        </Flicking>
    )
}
export default Try;

`"@egjs/flicking-plugins": "^4.2.2",
    "@egjs/grid": "^1.6.0",
    "@egjs/react-flicking": "^4.4.0",
    "@egjs/react-grid": "^1.6.0",`

**Comment by WoodNeck** [comment]
Hello @ababurak92!
That happens when dependencies mismatch, can you re-install the react-flicking?
You should uninstall `react-flicking` package and reinstall it.
if that doesn't work, you can try removing all the `node_modules` & `package-lock.json`.

**Comment by ababurak92** [comment]
Hello,
Already i did it and i try it again but same result.I'm newbie sorry, i wanna use it but what i try its not worked.Can you give me some suggestions for find problem ?

**Comment by WoodNeck** [comment]
Normally, that function should not be in the react-flicking's v4.4.0, which I've tested already.
I think there's some issue with the version of module's you're using.
Can you show me what actual version you're using by checking the `package.json` in `/node_modules/@egjs/react-flicking`?

**Comment by ababurak92** [comment]
Hello,
Yes that correct i'm using 4.3.2 because i was getting the error in the (below)link and i applied solution.After that i started to get this error.
https://github.com/naver/egjs-flicking/issues/576

Unhandled Rejection (TypeError): this._el is null

**Comment by WoodNeck** [comment]
I've just released a new version (v4.4.1) that fixes that issue, please try that :)

```sh
npm install @egjs/react-flicking@latest
```
