### ISSUE TITLE
[Vue] Couldn't separate card-panel at v-for 

### ISSUE THREAD

**Issue by lem0n43** [naver/egjs-flicking#580]
## Description

I use flicking at v-for like this, (_first, second, third is component and arrList is Map()_)

```
<Flicking
      :options="{
        circular: true,
        align: 'center',
        horizontal: true,
      }"
      :plugins="plugins"
      @changed="updateTransform"
    >
<div v-for="[key] of arrList" :key="key" class="card-panel" >
          <first
            v-if="key === 'one'"
          ></first>
          <second
            v-else-if="key === 'two'"
          ></second>
          <third
            v-bind:value="show(key)"
            v-on:value="show(key)"
          ></third>
        </div>
</Flicking>
```

However, flicking's panel doesn't recognize that each component according to the key is an independent panel. It recognizes <div v-for~></div> as one panel. I try to write class="card-panel" at each component not <div v-for~>, but result is same. 

I want to make the panel to be divided according to each key.
How can I solve this?

**Comment by WoodNeck** [comment]
Hello @lem0n43!
I've just tested a slightly modified version of your example, which uses Map, and it worked fine on both vue-flickings(vue-flicking, vue3-flicking)

I need a more explanation for this to solve it, can you give me some more detailed information about this?
Like, which version of Vue you're using, what `arrList` looks like, and how it's changed.

Or, just give me a link to the actual file(if it's possible) would be fine :)

My test code was:
```js
list = new Map([["a", 0], ["b", 1], ["c", 2], ["d", 3]]);
```

```vue
<flicking class="flicking" :options="{ renderOnlyVisible: true, circular: true }">
  <div v-for="[key, val] of list" :key="key" class="panel">
    {{ val }}
  </div>
</flicking>
```

**Comment by lem0n43** [comment]
Hello @WoodNeck !
My Vue version is 2.6.11 and arrList looks like
`arrList = [ key : suggestion Idea code , value: Info about key(ex, What that idea mean, Idea Name..)]`
But I only used "key" at that flicking. and arrList are in store.

cardState is also the map like arrList, but it looks like
`cardState = [ key : suggestion Idea code , value: waiting/fail/success]`
Both cardState and arrList are in computed.


My whole code in this .vue is like this. Is it possible to show Flicking <div v-for> </div> with <div></div> together at same time?
```
<Flicking
      :options="{
        circular: true,
        align: 'center',
        horizontal: true,
      }"
      :plugins="plugins"
      @changed="updateTransform"
    >
<div v-for="[key] of arrList" :key="key" class="card-panel" >
          <waiting 
            v-if="cardState.get(key) === 'waiting'"
          ></waiting >
          <fail 
            v-else-if="cardState.get(key) === 'fail'"
          ></fail >
          <access 
            v-bind:value="showCard(key)"
            v-on:value="showCard(key)"
          ></access >
 </div>
<div class="card-panel">
     <addNew v-bind:showeVCInfoDialog="showeVCInfoDialog"
        v-on:showChange="showChange"
     ></addNew>
</div>
<div slot="viewport" class="flicking-pagination"></div>
</Flicking>

<script>
import access from './access.vue'
import fail from './fail.vue'
import waiting from './waiting.vue'
import addNew from './addNew.vue'
import { Flicking } from '@egjs/vue-flicking'
import { Pagination } from '@egjs/flicking-plugins'
import '@egjs/flicking-plugins/dist/pagination.css'

export default {
 data(){
  return(){
   plugins: [new Pagination({ type: 'bullet' })],
   showeVCInfoDialog: false,
  }
},
components: {
access,
fail,
waiting,
addNew,
},
computed{
 arrList(){
    return  this.$store.state.myMapChangeTracker && this.$store.state.arrList 
 },
cardState(){
 return  this.$store.state.myMapChangeTracker && this.$store.state.cardState
}
method:{
    showCard(key){
       return this.$store.state.cardState.get(key)==='success'
    },
    showChange(change,msg,target){
    ....
    },
  ........
},
}
</script>
```

**Comment by lem0n43** [comment]
To @WoodNeck
I found it! It just my component problem.
Thank you for your help and for creating a awesome API. 👍

**Comment by WoodNeck** [comment]
@lem0n43 
Glad you fixed it! I'll close this issue, feel free to reopen it :)

**Comment by FollowJack** [comment]
> To @WoodNeck I found it! It just my component problem. Thank you for your help and for creating a awesome API. 👍

Can you tell how you fixed this? I also have my components stacked up and dont know why.
