### ISSUE TITLE
ViewportSlot outside of Flicking element for the Pagination plugin in React

### ISSUE THREAD

**Issue by daleSOCI** [naver/egjs-flicking#582]
I'm just wondering if there's a way to move the viewport slot outside of the flicking element, like so: 

```
<Flicking
                                className={styles.slider}
                                circular
                                plugins={plugins}>
                                {slides.map((slide, index) => (
                                    <div className={styles.slide} key={`slide-${index}`}>
                                        <div className={styles.slide_copy}>
                                            <RichTextArea html={slide.copy} />
                                        </div>
                                        <div className={styles.slide_image}>
                                            <SEOImage img={slide.image} sizes={[400, 300]} className="w-100" />
                                        </div>
                                    </div>
                                ))}
                            </Flicking>
                            <ViewportSlot>
                                <div className="flicking-pagination"></div>
                            </ViewportSlot>
```

Currently, with the overflow hidden on the slider wrapper, I can't move the pagination element to the side of the slider. Normally, I'd just add padding to the side, and position the pagination bullets within the padding, but we need a drop shadow on the slider container making that method not work. It's all pretty stupid, and hard to explain, but I've realized the only way to do this is by moving the bullets outside. I can't find an example of this, or any options that might make it possible. So I'm wondering if there's an option I'm not seeing, or if I need to just tell the designer we need to get rid of the drop shadow.

**Comment by davidhorm** [comment]
I was just trying to figure out the same thing. I got it to work by leaving the `<ViewportSlot>` inside of `<Flicking>` per the demo, and the moved the bullets by adding this style:

```css
.flicking-pagination {
    position: relative;
    bottom: -16px;
    height: 24px;
}
```

But I don't know if that'll solve your drop shadow needs.

**Comment by WoodNeck** [comment]
Hello @daleSOCI!
As the `ViewportSlot` is for placing non-panel elements in the Flicking wrapper, you don't have to use it if you're placing it outside of Flicking.
And, as the pagination items are designed to be placed inside of Flicking in our CSS, you can change them by overriding our CSS.
Or you can give a different class for pagination wrapper, which makes it not affected by our plugin CSS.

I've made a simple demo for placing the pagination outside of Flicking, it's made with vanilla JS but the same thing can be applied on the React also. Please check the `CSS` section! (I've added some background color for each section to visualize them)
- https://codepen.io/woodneck/pen/gOxewae

I just placed the wrapper outside of the Flicking wrapper, I couldn't guess where should it be placed.
If you let me know which particular UI you're creating, I can give you some more detailed examples of it.

**Comment by WoodNeck** [comment]
Anyway, I think we need some more examples on our demo page & maybe more classes in our plugin's CSS file for displaying the wrapper outside of Flicking viewport.

**Comment by daleSOCI** [comment]
@WoodNeck Thanks so much. Sorry, didn't get an email notification for this reply and got sidetracked, but this does help a lot, and did solve my problem. Only thing I needed to adjust was the setup for the plugins array due to NextJS having an undefined `document`. I just needed to throw the plugin initialization in a lifecycle hook though to get past that. 

```
const [plugins, setPlugins] = useState([]);

useEffect(() => {
    setPlugins([new Pagination({ type: 'bullet', parentEl: document.querySelector('#slider') }), new AutoPlay({ duration: 2000, direction: "NEXT", stopOnHover: true })]);
}, []);
```
