### ISSUE TITLE
Fade plugin won't work with renderOnlyVisible [vue3-flicking]

### ISSUE THREAD

**Issue by hiendv** [naver/egjs-flicking#585]
## Description
Hi,
Fade plugin tries to modify the original panel style but the diffResult won't carry them so the `opacity` was never actually set for Vue elements.

## Steps to check or reproduce
Sorry for missing the repo. I'm in the middle of something. Will provide soon if it's not clear for you.

**Comment by WoodNeck** [comment]
Hello @hiendv!
I've found that vue3-flicking is not getting the latest panel element, so the fade plugin was updating the old elements.
I raised a PR(#586) that fixes this issue, I'll leave a comment here when it's merged & released :)

**Comment by WoodNeck** [comment]
I've just released vue3-flicking `v4.4.1` that fixes this issue, please try that!
