### ISSUE TITLE
In Next js, Cannot read properties of undefined (reading 'nativeElement')

### ISSUE THREAD

**Issue by gusrb3164** [naver/egjs-flicking#598]
## Description
Next js Link를 통해서 같은 페이지의 다른 id로 이동하는 경우에 발생하는 버그입니다.

Bug that occurs when moving to another id on the same page through Nextjs Link.

![image](https://user-images.githubusercontent.com/34272561/144359793-33902226-47bd-4d78-a196-677aee0169ec.png)
### Simple code
```tsx
import Flicking from '@egjs/react-flicking'
import Card from 'component/Card'

const CardSwiper = ({ card, id }: any) => {
  const { data: cards } = useQuery(`/card/${id}`) // react query

  return cards && cards.length > 0 ? (
    <Flicking>
      {cards.map((card) => (
        <div>
          <Card card={card} />
        </div>
      ))}
    </Flicking>
  ) : (
    <></>
  )
}
```
### 아래 조건이 모두 해당될 때 발생합니다.
1. sample/:id 의 페이지 첫 진입시 id에 따라 api fetching으로 가져온 데이터를 기준으로 swiper 내부 노드를 렌더링함 (ex: get api/sample/:id)
2. 1번 페이지에서 Next Link를 통해 id가 다른 sample/:id 로 이동 (ex: sample/1 -> sampel/2)

## Tried
1. 다른 페이지에서 sample/:id 진입하는 경우, url을 직접 입력해서 이동하는 경우에는 발생하지 않습니다.
2. Next Link를 통해 이동하기 전에 해당 데이터를 undefined나 null로 초기화 후에 이동하는 경우는 발생하지 않습니다. 하지만 뒤로가기를 누르면 다시 발생합니다.

**Comment by WoodNeck** [comment]
Hello @gusrb3164!
I've found out that there was a logical mistake in our element syncing code, so I've raised a PR to fix it.
I'll leave a comment here after releasing a fix of it :)

**Comment by hyeon-9yu** [comment]
@WoodNeck 
Thank you for your quick check and response! :)

**Comment by gusrb3164** [comment]
@WoodNeck 
Thank you for your quick check and response! :)

**Comment by WoodNeck** [comment]
@gusrb3164 
I've just released a new version that fixes this issue :) (@egjs/react-flicking v4.4.3)
Please try the latest version
