### ISSUE TITLE
네이버 모바일웹에서 처럼 패널 내부에 스크롤 해야하는 객체가 있을 때는 어떻게 처리 해야하나요?

### ISSUE THREAD

**Issue by dol2156** [naver/egjs-flicking#602]
![Screenshot_1](https://user-images.githubusercontent.com/15097841/147053633-531270c9-d14b-404b-bba5-370f91ba7271.png)
네이버 모바일웹에서 처럼 패널 내부에 스크롤 해야하는 객체가 있을 때는 어떻게 처리 해야하나요?

**Comment by WoodNeck** [comment]
안녕하세요.
네이티브 스크롤 사용시에는 상위 Flicking엘리먼트로 전달되는 이벤트 버블링을 막아주시면 됩니다.

```js
// touchstart, touchend 동일
el.addEventListener("touchmove", evt => {
  evt.stopPropagation();
})
```

**Comment by dol2156** [comment]
> 안녕하세요. 네이티브 스크롤 사용시에는 상위 Flicking엘리먼트로 전달되는 이벤트 버블링을 막아주시면 됩니다.
> 
> ```js
> // touchstart, touchend 동일
> el.addEventListener("touchmove", evt => {
>   evt.stopPropagation();
> })
> ```

답변 감사드립니다 ^^
