### ISSUE TITLE
moveType:Snap Count 옵션 추가 

### ISSUE THREAD

**Issue by n0ch4t** [naver/egjs-flicking#606]
Sanp Option에 Count 옵션을 추가할 수 있는것으로 검색되는데
어떤 방식으로 추가하는지 알 수 있을까요?
문서에는 작성이 되어있지 않은듯 합니다..

**Comment by WoodNeck** [comment]
Hello @n0ch4t! 
You can do it like this:
```js
new Flicking("#el", {
  moveType: ["snap", { count: 5 }]
});
```
