### ISSUE TITLE
Circle and bound if  there are fewer slides than viewport

### ISSUE THREAD

**Issue by lna1989** [naver/egjs-flicking#607]
## Description
If circular:true and bound:true with the number of slides less than the width/height viewport bound: true option does not work (But in theory, the circular option turns from true to false in this case)

## Steps to check or reproduce
[codesandbox](https://codesandbox.io/s/flicking-circulart-and-bound-t83no?file=/src/App.vue)

**Comment by WoodNeck** [comment]
Hello @lna1989!
Both are physically impossible, as they can't fill the viewport area if the sum of panel sizes is smaller than the viewport size.
So we're turning off such options to prevent graphical glitches.
The only solution is to clone the panel elements. We did that in the previous major version(v3), but we're not doing this automatically in newer versions for element consistency (like, to prevent events from the cloned elements)

Maybe the `bound` can be improved, like restricting the scrollable area to 0, but I think `circular` can't without graphical glitches so we have to leave it as is.
If you're aware of panel/viewport sizes, you can try cloning the panel elements.

**Comment by lna1989** [comment]
Hello @WoodNeck! 
I mean the case when circle is actually turned off, even though the option is enabled. I.e. fliking determines that the viewport is not fully filled and turns off the circle() option:

> WARNING
If the sum of the panel sizes is too small, circular will not be enabled.
This is because Flicking doesn't clone panel elements for the performance and to prevent other issues.
You can check this with circularEnabled property of Flicking.
To enable circular mode, all panels should pass the below condition
Sum of panel sizes - panel size >= viewport size

In the same case, we can enable the binding: true , since the circle is actually disabled

**Comment by WoodNeck** [comment]
That's interesting. You mean you want to enable `bound` for the case when `circular` can't be enabled?

**Comment by lna1989** [comment]
> That's interesting. You mean you want to enable `bound` for the case when `circular` can't be enabled?

@WoodNeck Absolutely righ, attached a real case where it can be useful
![Peek 2022-01-13 09-51](https://user-images.githubusercontent.com/49455662/149273554-242648c1-17f2-4e04-a252-dac5ef880750.gif)
In theory, I can check the option on my side and send circle to false, and bound to true, but I think this is not the most interesting solution, since flicking already knows how to send circle to false.

**Comment by WoodNeck** [comment]
Now I fully understood the situation, thanks for the detailed explanation.

I think I can add an option for that, named like `circularFallback` as using `bound` for fallback is not intuitive in this case I think.
With that option, it can work like either the normal slider or `bound`-applied slider when the `circular` can't be applied.

I'll work on it asap, give me a couple of days to make this feature & tests.
I'll leave a comment here after that feature is released :)

**Comment by WoodNeck** [comment]
I've just released a new version that fixes this issue :)
Install with `@latest` tag to use the new option `circularFallback`

```
{ circularFallback: "bound" }
```

**Comment by lna1989** [comment]
@WoodNeck It works perfectly, thank you for your hard work!
