### ISSUE TITLE
Sync plugin error: FlickingError: Position "XXXX.XXXXXXXXX" is not reachable.

### ISSUE THREAD

**Issue by lna1989** [naver/egjs-flicking#608]
## Description
The Sync plugin is broken on the demo stand and my implementation also behaves inadequately in some cases.

## Steps to check or reproduce on demo stand

1. Wait for the page to load
2. Start moving the flicking0 slider slider with thumbs (https://naver.github.io/egjs-flicking/Plugins/#sync)
3. To see errors in the console, after which the slider synchronization behavior breaks
![Peek 2022-01-13 12-14](https://user-images.githubusercontent.com/49455662/149292185-d0e3d72a-507c-401f-9ddd-230327a60f3a.gif)

## Steps to check or reproduce from my case

1. Open CodeSandbox: https://codesandbox.io/s/flicking-sync-error-1-ng8w6?file=/src/App.vue
2. Wait for the page to load
3. Click on arrow - Everything should be fine, no errors and the active thumb is highlighted with a blue outline.
4. Start move slider with mouse/touch - slider crashed
![Peek 2022-01-13 13-07](https://user-images.githubusercontent.com/49455662/149299584-fa7f2919-4dc4-44cf-b481-192e360338f9.gif)

Additional info: 
mainOptions: {
        panelsPerView: 1,
        circular: true,
        autoResize: true,
      },
      thumbsOptions: {
        circular: true,
        autoResize: true,
        align: "center",
      },

**Comment by WoodNeck** [comment]
Hello @lna1989!
Looks like our plugin is broken from the recent updates of Flicking.
I've just created a [PR](https://github.com/naver/egjs-flicking-plugins/pull/32) to fix this.
I'll leave a comment here after it's released :)

**Comment by WoodNeck** [comment]
I've just released a new version of @egjs/flicking-plugin (v4.2.3), please try that!

**Comment by lna1989** [comment]
It works great, thank you very much!
