### ISSUE TITLE
renderOnlyVisible 옵션 활성화 시 resize 크기 조절 문제

### ISSUE THREAD

**Issue by n0ch4t** [naver/egjs-flicking#609]
renderOnlyVisible 옵션을 사용 시에 
screen size가 변화하거나 모바일기기에서 회전을 할 경우 슬라이드가 망가지는것 같습니다.

혹시 이를 감지하여 복구 시키거나 정상화 시킬 방법이 있나요 ?

circular: true,
renderOnlyVisible: true,
moveType: ['snap', { count: 1}]

**Comment by cc00010** [comment]
Same issue.
Installed version: `4.5.1`. Tested on Safari and Firefox.

When `renderOnlyVisible` is `false`:

https://user-images.githubusercontent.com/92562933/152633103-969989ab-9e8a-4b62-b40a-9e07f5e4d946.mov

When that property is `true`:

https://user-images.githubusercontent.com/92562933/152633112-b62f1643-c8bb-4cf6-a30d-0697412b0597.mov

**Comment by WoodNeck** [comment]
Hello @cc00010!
I've found out that issue occurs because vue-flicking is having wrong reference of elements.
Created #618 for fixing that :)

**Comment by WoodNeck** [comment]
@egjs/vue-flicking@4.5.2 will fix this :)

**Comment by cc00010** [comment]
I can confirm the issue has been fixed. Thanks @WoodNeck!

**Comment by n0ch4t** [comment]
works perfectly.
