### ISSUE TITLE
undefined 'constructor' in SvelteKit

### ISSUE THREAD

**Issue by raafirivero** [naver/egjs-flicking#612]
## Description
I'm getting this error in Terminal running Flicking with SvelteKit / vite:
`Cannot read properties of undefined (reading 'constructor')
TypeError: Cannot read properties of undefined (reading 'constructor')
    at eval (/node_modules/@egjs/flicking/dist/flicking.esm.js?v=2bef5244:8176:24)`

## Steps to check or reproduce
The carousel actually runs on my dev site, but I still get the issue in the terminal. Any ideas here?

**Comment by WoodNeck** [comment]
Hello! I've just released a new version that fixes this issue :)
Install the latest(v4.5.1) version to fix this
