### ISSUE TITLE
How to prevent POSITION_NOT_REACHABLE Error?

### ISSUE THREAD

**Issue by jexists** [naver/egjs-flicking#614]
## Description

How to prevent POSITION_NOT_REACHABLE Error?
Pagination 플러그인을 사용할때 에러가 생기는 것 같은데 처음에 이미지 받는 타이밍때문에 생기는 건지,
페이지가 선택이 안되있을 경우 에러가 생기네요.,

![image](https://user-images.githubusercontent.com/54986331/150712956-829755aa-d7ad-4ed9-96f5-1e3d299cfa43.png)

**Comment by WoodNeck** [comment]
Hello @jexists!
Can you provide me with a demo that reproduces this error?

**Comment by jexists** [comment]
https://rebbit.net/products/6788
you can change the number if error will not appear.

**Comment by WoodNeck** [comment]
The first thing I found was Flicking's `currentPanel` is set to `null`.
I'm pretty sure that this is the cause of the error, but I can't guess why it is.
Please provide me with some more information, especially the code where you set your panels.

**Comment by jexists** [comment]
HTML Code
`
    <ngx-flicking class="flicking product_view_flicking"
      [options]="{ align:'prev', bound: true, moveType:'snap'}" [plugins]="plugins">
      <div flicking-panel *ngFor="let image of product.image; let i = index" class="flicking_item">
        <img [src]="image" alt="image"
          onerror="this.onerror=null;this.src='../../../assets/images/no-image.png'; this.style='object-fit: contain;'" />
      </div>
      <div in-viewport class="flicking-pagination rect"></div>
    </ngx-flicking>
`

TS Code
`
export class ProductViewComponent implements OnInit {
  @ViewChild('flick') flick: NgxFlickingComponent;
  public plugins: Plugin[] = [new Pagination({ type: 'bullet' })];
}
`

**Comment by WoodNeck** [comment]
I found out that the Pagination plugin was the cause, and created a PR that fixes it.
I'll leave a comment here after it's merged & released :)
