### ISSUE TITLE
extraordinary behavior with NextJS

### ISSUE THREAD

**Issue by arcticneko** [naver/egjs-flicking#615]
"@egjs/react-flicking": "3.8.0
When rendering horizontal slider with SSR (Next JS), flicking initializes slides in browser vertically (which is not ok) and then re-render them immediately horizontally (which is ok).
Thus flashing happens.

All sliders are set to a constant width in px.

props are: {...{
 align: "prev",
 bound: true,
 adaptive: true,
 infinite: true,
 hanger: 0,
 anchor: 0,
 duration: 500,
 gap: 16,
}}

How to prevent this vertical-horizontal re-rendering?

**Comment by WoodNeck** [comment]
Hello @arcticneko!
That's fixed in the 4.0+ by using an additional CSS file.
If you can't update Flicking version for any reason, please check these issues:
#349 #457

**Comment by arcticneko** [comment]
Hello @WoodNeck !
Thanks for a prompt answer!
