### ISSUE TITLE
Cannot manipulate DOM when `renderOnlyVisible` is enabled (vue2)

### ISSUE THREAD

**Issue by cc00010** [naver/egjs-flicking#617]
## Description

I tried to directly manipulate the DOM by doing: `panel.element.classList.add('something')`, but it didn't work. After that I tried to remove `renderOnlyVisible` to see if it works without that property. I don't know why/how but it worked as expected!

BTW I noticed this #585 . I think it's related to my issue.

Version: `4.5.1`

**Comment by WoodNeck** [comment]
Same to #609, I've just created #618 to fix this issue.
Thanks for reporting!

**Comment by WoodNeck** [comment]
Fixed in @egjs/vue-flicking v4.5.2
