### ISSUE TITLE
Flicking 구현 오류 질문드립니다

### ISSUE THREAD

**Issue by holicAZ** [naver/egjs-flicking#620]
안녕하세요. 
Vue3에서 Flicking을 사용중입니다.
개발환경은 vscode를 사용하고 있습니다. vscode 상에서 run serve로 실시간 실행을 해보면 아래와 같이 정상적으로 
Flicking 사이즈와 Autoplay, circular 등 플러그인과 옵션이 정상적으로 동작합니다.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/59554748/152917316-2471d917-c4c6-43cf-9c20-342bb9deae47.gif)

하지만 build를 통해 실제 배포를 진행해 보면 아래와 같이 Flicking 사이즈도 상이하며, 어찌저찌 사이즈를 맞춘다 한들 
Flicking Camera의 translate 속성 값이 위와 다르게 설정되어 panel 사이가 보이는 등 Autoplay가 원하는 바와 다르게 동작합니다. 
또한 circular, gap (gap은 위에서도 적용되지 않음) 등 전혀 적용이 되지않은 모습입니다. 
도무지 해결할 수 없습니다... 발생 이유와 해결 방법이 궁금합니다...! 
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/59554748/152917773-ee75e241-38f4-4393-829b-0cfbe9a20338.gif)

**Comment by WoodNeck** [comment]
Hello @holicAZ!
I think our CSS(`flicking.css`) is missing in your final build.
Check this issue: #477
And this: https://stackoverflow.com/questions/58088758/no-css-files-when-running-vue-cli-service-build-watch

**Comment by holicAZ** [comment]
Thank you for the comments. But I added a meta tag to the header and wrote the Flicking CDN code globally, but the same problem still occurs.🥲

**Comment by WoodNeck** [comment]
@holicAZ 
I think then Flicking element's class name is being distorted somehow on build.
Can you check what's the actual classes Flicking element has, and the actual class names inside CSS included on the build?

**Comment by WoodNeck** [comment]
Glad to help, but you should include only one CSS file to use.
Use `flicking-inline.css` only if you're willing to support IE9.
