### ISSUE TITLE
Circular doesn’t work on horizontal false

### ISSUE THREAD

**Issue by s-hren** [naver/egjs-flicking#623]
## Description

When horizontal is false and circular is true, circular doesn’t work.

**Comment by WoodNeck** [comment]
Hello @SI-86!
I've just tested combining both options, and it works in my case.
Can you provide more information?

**Comment by malangfox** [comment]
Hello @samhren.

circular option may not work if the size of the Flicking viewport is large enough. [You can check the exact conditions in our document.](https://naver.github.io/egjs-flicking/Options#circular)
When creating flicking in the horizontal direction, the size of the viewport only extends to the maximum screen length.
However if you create flicking vertically, the size of the Flicking viewport will continue to grow vertically, creating a scroll.

It seems that the circular option didn't work as the vertical length the Flicking viewport is not set.
You may be able to solve this problem by setting the height of the Flicking. [Check out the demo we made.](https://codesandbox.io/s/flicking-angular-horizontal-circular-e5udo7?file=/src/app/app.component.html)
