### ISSUE TITLE
Add  rtl, ltr direction support

### ISSUE THREAD

**Issue by yaman3bd** [naver/egjs-flicking#625]
I really like how simple the package is
but I was searching in the docs to find if it does support rtl direction but I could not find
if it does support rtl can how to do that?
if not is it possible to add this feature?
thanks.

**Comment by WoodNeck** [comment]
Hello @yaman3bd!
We're not supporting rtl at the moment.
I'd like to add that feature, but it might take a long time.
I'll add that on our roadmap, thanks for the suggestion!
