### ISSUE TITLE
vue3-flicking not working with Vue3 + vite

### ISSUE THREAD

**Issue by Kotoriii** [naver/egjs-flicking#629]
## Description
I get the error below. Flicking does not render at all.
```
Flicking.ts:171 Uncaught TypeError: Cannot read properties of undefined (reading '_control')
    at get (Flicking.ts:171:38)
```

## Steps to check or reproduce
- Install vue3-flicking with yarn
- Add a very simple component
- Vue 3.2.31 and Vite 2.8.4

I tried adding flicking to optimizeDeps and it didn't work either

```
<template>
  <Flicking>
    <div>1</div>
    <div>2</div>
  </Flicking>
</template>

<script>
import Flicking from "@egjs/vue3-flicking";

export default {
  components: {
    Flicking
  },
}
</script>
```

**Comment by WoodNeck** [comment]
Hello @Kotoriii!
Looks like Vite or somewhere redefines `Object.defineProperty` so the error occurs.
I've create a PR(#631) that fixes this issue :)

**Comment by Roxas92** [comment]
Not sure if it helps fixing the issue, but I have the same problem with Vue CLI, so it don't think this issue is exclusive for Vite. I'm using `vue@3.2.11` with `@vue/cli-service@5.0.1`.

**Comment by WoodNeck** [comment]
@Kotoriii 
I've just released a new version that fixes this, please try that :)
