### ISSUE TITLE
pagination gets broken by moveType "strict"

### ISSUE THREAD

**Issue by bb-in-hoodie** [naver/egjs-flicking#632]
### What I wanted
- when swiping the panels: only slide a single panel at a single swipe
- when clicking a pagination button: move to a panel no matter how far the target panel is away from the current one

### What actually happens
- `moveType: snap`
  - ✕ swiping: it slides infinitely
  - ✓ clicking pagination: moves to a clicked panel as expected
- `moveType: strict`
  - ✓ swiping: it only slides to a prev/next one as expected
  - ✕ clicking pagination: even though pagination looks alright, the panels never slides more than 1 panel at a time

![2022-03-10_01-flicking_strict](https://user-images.githubusercontent.com/12558317/157578625-8c8bee79-b33e-4ba4-83f9-6bfaee75f0ce.gif)
:-:
with moveType strict, pagination gets broken

## Steps to check or reproduce

apply pagination and set `moveType` as `'strict'`

**Comment by WoodNeck** [comment]
Hello @bb-in-hoodie!
Thanks for reporting! I've created a PR that fixes this: #633

**Comment by WoodNeck** [comment]
@bb-in-hoodie 
I've just released a new version that fixes this, please try that :)

**Comment by bb-in-hoodie** [comment]
It works as expected in the newest version. Thanks a lot :)
