### ISSUE TITLE
How to use it without specifying picture size in pixels?

### ISSUE THREAD

**Issue by GeorgyLevin** [naver/egjs-flicking#634]
I want to show only 1 image at the time. I want it to use all width of container, and automatically adjust height to respect image proportions. And i don't want to specify width and height in pixels for each picture, as page has to be adaptive.
I tryed this:
```
<Flicking :options="{panelsPerView: 1, adaptive: true}">
	<div v-for="i in 8" :key="i">
		<img :src="i + '.jpg'"/>
	</div>
</Flicking>
```
But its not working. It allways shows Images collapsed to size 0x0px unless i specify pxel size.
Please help me!

**Comment by WoodNeck** [comment]
Hello @GeorgyLevin!
Try `resizeOnContentsReady` :)

**Comment by WoodNeck** [comment]
In that case, I think the CSS applied in the <div> element prevents height calculation of the img elements.
Your div element probably always have height equal to 100% not regarding the actual contents height.
Try adding `height: fit-content`, or set `align-items: flex-start` to flicking-camera element

Here's some examples:
- https://codepen.io/woodneck/pen/eYyZpmd
- https://codepen.io/woodneck/pen/MWryaje

**Comment by GeorgyLevin** [comment]
> In that case, I think the CSS applied in the <div> element prevents height calculation of the img elements. Your div element probably always have height equal to 100% not regarding the actual contents height. Try adding `height: fit-content`, or set `align-items: flex-start` to flicking-camera element
> 
> Here's some examples:
> 
> * https://codepen.io/woodneck/pen/eYyZpmd
> * https://codepen.io/woodneck/pen/MWryaje

Thank you!

**Comment by WoodNeck** [comment]
I'll close this issue to mark it as resolved, please reopen it if the issue still remains!
