### ISSUE TITLE
API 문서 사이트 링크 오류 제보

### ISSUE THREAD

**Issue by sungunjo** [naver/egjs-flicking#636]
## Description
![스크린샷 2022-03-22 오전 10 17 23](https://user-images.githubusercontent.com/41507479/159388514-d06ca577-1f5b-44bd-83ac-e1d40266dcef.png)

공식 홈페이지 하단부에 API 카테고리 이동 링크가 options로 연결되어있습니다.

**Comment by WoodNeck** [comment]
Hello @sungunjo!
Thanks for the report! I'll fix that asap :)
