### ISSUE TITLE
슬라이드 re-rendering 방법

### ISSUE THREAD

**Issue by sk31park** [naver/egjs-flicking#652]
## Description

현재 nuxt 2.x.x 버전에서 flicking을 사용중에 있습니다.
(아래코드 참조),

data.list.option 값을 변경했을떄 다시 슬라이드를 re-render 해주고 싶습니다.
key 속성을 통해 구현해보려고 했지만 key 값이 변해도 flicker는 다시 렌더링 되지 않더라구요.

가장 나이스한 방법을 알려주시면 감사합니다.

```
<Flicking :options="data.list.option" :plugins="plugins" :key="`${data.list.option}${data.list.plugins}${data.list.value}`">
...
```

**Comment by WoodNeck** [comment]
@sk31park님 안녕하세요.
key 변경시에는 기본적으로 인스턴스가 전부 새로 생성되기 떄문에, 옵션이 변경되더라도 다시 렌더링되지 않는다면 Nuxt 등 다른 이유가 있지 않을까 합니다.
vue-flicking을 이용하여 비슷한 경우를 테스트해봤는데요, 다음과 같은 코드에서 정상적으로 옵션 변경 / 패널 변경이 정상적으로 동작하는 것을 확인했습니다.

```vue
<template>
  <div>
    <flicking class="flicking flicking0" :key="val" :options="options">
      <div v-for="idx in array" :key="idx" class="panel0"><div class="anchor"></div></div>
    </flicking>
    <button @click="onClick">Click</button>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class Align extends Vue {
  public val = 0;
  public options = { moveType: "freeScroll" };
  public array = [0, 1, 2, 3, 4];

  public onClick() {
    this.val = 1;
    this.options = { moveType: "snap" };
    this.array = [5, 6, 7];
  }
}
</script>
```

key값이 실제로 변경되어 Flicking 인스턴스가 새로 생성되는지 먼저 확인해보셨으면 좋겠구요,
그렇지 않다면 재현 가능한 데모를 codesandbox 전달해주시면 제가 확인해보고 답변을 드릴 수 있을 것 같습니다.

P.S.
Flicking이 현재 모든 옵션 변경에 대해서 대응하고 있지는 않기 때문에, 특정 옵션 변경의 경우 반영되지 않을 수 있습니다.

**Comment by sk31park** [comment]
답변 감사합니다.
확신을 주신 덕분에 세밀히 점검할 수 있었고 보니까 key 값에 object 값을 넣었는데,
해당 object를 string으로 변경하지 못하여 생긴 오류였습니다.

string으로 변경하여 집어넣고 실험하니 제대로 re-rendering 하는 것을 볼 수 있네요.
다시한번 답변 감사드립니다. 🙇‍♂️
