### ISSUE TITLE
리액트 중첩 슬라이드 구조 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by eunhye8767** [naver/egjs-flicking#657]
## Steps to check or reproduce

<img width="611" alt="스크린샷 2022-04-20 오후 6 15 18" src="https://user-images.githubusercontent.com/74218759/164195443-3c4d1c14-2e69-499a-acd4-b35f660e0113.png">

1차 슬라이드 내에 과일 카테고리처럼 2차 슬라이드를 적용했을 때
과일 카테고리 부분을 슬라이드하면 1차 슬라이드와 같이 움직여 집니다..

리액트에서 어떻게 적용을 해줘야 할까요...?

**Comment by WoodNeck** [comment]
@eunhye8767 님 안녕하세요.
현재 관련 옵션을 준비하고 있구요 (https://github.com/naver/egjs-axes/pull/181)
기반 컴포넌트에서는 작업이 마무리되었으나 아직 Flicking에는 적용되지 않아 해당 기능을 사용하실 수 없습니다.
일정이 명확하게 정해지진 않은 터라, 언제까지 가능할지 말씀드리기는 어려울 것 같습니다.

**Comment by malangfox** [comment]
안녕하세요. @eunhye8767 님.
Flicking의 4.7.0 버전부터 Flicking 내부에 Flicking이 위치할 때의 동작이 개선되어 더 이상 상위 Flicking을 함께 움직이지 않습니다.
Flicking 내부에 Flicking이 존재할 때 동작을 정의하는 방법에 대해서는 [nested](https://naver.github.io/egjs-flicking/Options#nested) 문서 및 [구현 예시](https://naver.github.io/egjs-flicking/Demos#nested-flickings) 참고하실 수 있습니다.

**Comment by eunhye8767** [comment]
감사합니다 ! 확인해보겠습니다 :)

**Comment by eunhye8767** [comment]
> 안녕하세요. @eunhye8767 님. Flicking의 4.7.0 버전부터 Flicking 내부에 Flicking이 위치할 때의 동작이 개선되어 더 이상 상위 Flicking을 함께 움직이지 않습니다. Flicking 내부에 Flicking이 존재할 때 동작을 정의하는 방법에 대해서는 [nested](https://naver.github.io/egjs-flicking/Options#nested) 문서 및 [구현 예시](https://naver.github.io/egjs-flicking/Demos#nested-flickings)를 참고하실 수 있습니다.

감사합니다! 재확인해보겠습니다 :)
