### ISSUE TITLE
Flicking Plugins Sync 문의

### ISSUE THREAD

**Issue by ana59** [naver/egjs-flicking#666]
## Description

안녕하세요:-)
일전에 미디엄을 통해 기술 구현 관련해서 문의를 드렸었습니다!
보내주신 데모파일이 많은 도움이 되었습니다ㅠㅠ

제가 아래 코딩 테스트 중인데요 <br>
https://codepen.io/james-jung/pen/gOvOyop

위 codepen 파일에서 #flick1 클릭하면 #flick0가 슬라이드 되게끔 하고 싶습니다!
그런데 작동을 안하네요ㅠㅠ
이 상태에서 제가 추가로 설정해야하는게 있을까요?

도움 주셔서 감사합니다!

**Comment by WoodNeck** [comment]
@ana59 님 안녕하세요

addPlugins 하실때 array가 아닌 상태로 주시면 됩니다 :)

```diff
-flicking0.addPlugins([new Flicking.Plugins.Sync()])
+flicking0.addPlugins(new Flicking.Plugins.Sync())
```

**Comment by ana59** [comment]
오...! 해결되었습니다! 도움주셔서 감사합니다:)
