### ISSUE TITLE
Flicking 슬라이드 위치 값, 중첩 슬라이드 문의

### ISSUE THREAD

**Issue by ana59** [naver/egjs-flicking#667]
## Description

안녕하세요:) 플러그인 사용시 도움주셔서 감사드립니다.
문의가 있어 문의 남깁니다!

작업파일: https://codepen.io/james-jung/pen/gOvOyop <br><br>

**1. 슬라이드 시 스크롤 위치 유지 되는 현상**
문제점: 슬라이드 콘텐츠를 아래로 스크롤 하다 다음 슬라이드로 넘기면, 위치가 그대로 유지되어 중간부터 보이는 현상이 발생합니다.
저는 위치가 초기화 되어서 다시 맨 위로 위치가 이동되었으면 좋겠거든요ㅜㅜ
따로 설정할 수 있는 옵션이 있을까요?

**2. 슬라이드 높이 값 auto height 설정**
슬라이드마다 높이 값이 모두 다릅니다. 높이 값에 맞게끔 스크롤 되었으면 좋겠는데요
이를 구현하기 위해 vertical 클래스를 추가했고 스크립트에 아래 옵션을 넣었습니다.
horizontal:true, adaptive:true, renderOnlyVisible:true
그런데 이렇게 하니 슬라이드 될 때마다 새로고침되어 깜빡이는 현상이 생깁니다..
깜빡 거리지 않고 사용하긴 어려울까요? 다른 옵션이 있을지요?

**3. 중첩 슬라이드**
현재 제가 사용중인 작업 파일에서 중첩 슬라이드 구현도 가능할까요?

감사합니다:)

**Comment by WoodNeck** [comment]
@ana59 님 안녕하세요.

1. 이건 아마 2번 해결하시게 되면 자연스럽게 해결될 수도 있을 것 같구요, 그렇지 않다면 이벤트 핸들러 추가해서 해결하는 방법이 있을 것 같습니다. 패널 내부에 스크롤 영역이 있다면, `willChange` 이벤트에 맞춰서 `scrollTo`를 호출해주시면 될 것 같구요

2. 현재 제공해주신 데모의 경우 현재 저희 데모 페이지의 CSS를 사용하고 계셔서 패널의 크기가 200px로 고정되어 있는데요, 그게 문제가 되서 `adaptive`가 정상적으로 동작하지 못하고 있습니다. `adaptive` 만 남기시고 나머지는 제거하시면 좋습니다~
만약 여전히 패널 크기가 작다면 `flicking-panel` CSS에 `align-self: flex-start` 혹은 `height: max-content`를 추가해주시면 됩니다.

3. 중첩 슬라이드는 현재 개발 진행중이라 당장은 사용하실 수 없구요, 배포되면 사용 가능하실 것 같습니다.

**Comment by ana59** [comment]
넵 도움주셔서 감사드립니다:-)

**Comment by malangfox** [comment]
안녕하세요. @ana59 님.
Flicking의 4.7.0 버전부터 Flicking 내부에 Flicking을 배치하실 수 있게 되며 말씀을 남겨주신 3. 번의 중첩 슬라이드의 구현이 가능해졌습니다.
4.7.0 버전부터는 하위 엘리먼트에 배치한 Flicking을 스크롤할 때 상위 엘리먼트에 배치한 Flicking은 스크롤되지 않으며 하위 플리킹이 첫/마지막 Panel에 도달하면 상위 플리킹을 움직일지에 대한 여부도 설정이 가능합니다.
Flicking 내부에 Flicking이 존재할 때 동작을 정의하는 방법에 대해서는 [nested](https://naver.github.io/egjs-flicking/Options#nested) 문서 및 [구현 예시](https://naver.github.io/egjs-flicking/Demos#nested-flickings)를 참고하실 수 있습니다.

**Comment by ana59** [comment]
오....! 너무 감사합니다 살펴보겠습니다^^
