### ISSUE TITLE
Flicking components with horizontal drag block vertical drag

### ISSUE THREAD

**Issue by gbyesiltas** [naver/egjs-flicking#673]
## Description
Flicking components with horizontal drag block vertical drag on mobile. I believe this happened after 4.6.3 or 4.7.0

## Steps to check or reproduce
Go to the [demo on the flicking website](https://naver.github.io/egjs-flicking/Demos) on mobile (or on a mobile viewport on the devtools) and try to drag vertically by starting your drag on the flicking component. It won't cause a vertical scroll.

**Comment by malangfox** [comment]
Hello @gbyesiltas.
We have checked the inappropriate behavior you left behind.
This issue will be fixed in the next patch. We will notify you after the problem you reported is corrected.
Thank you for reporting!

**Comment by gbyesiltas** [comment]
> Hello @gbyesiltas.
> We have checked the inappropriate behavior you left behind.
> This issue will be fixed in the next patch. We will notify you after the problem you reported is corrected.
> Thank you for reporting!

Thank you! :)

**Comment by WoodNeck** [comment]
@hyeon-9yu 
I believe this happened after [4.7.0](https://github.com/naver/egjs-flicking/releases/tag/4.7.0), so you can either:
- use 4.6.x instead
```sh
npm i @egjs/flicking@~4.6.0
```
- Add the following CSS to the `.flicking-viewport` element
```css
.flicking-viewport {
  touch-action: pan-y !important;
}
```

Fix will be made after https://github.com/naver/egjs-axes/pull/185

**Comment by hyeon-9yu** [comment]
> @hyeon-9yu I believe this happened after [4.7.0](https://github.com/naver/egjs-flicking/releases/tag/4.7.0), so you can either:
> 
> * use 4.6.x instead
> 
> ```shell
> npm i @egjs/flicking@~4.6.0
> ```
> 
> * Add the following CSS to the `.flicking-viewport` element
> 
> ```css
> .flicking-viewport {
>   touch-action: pan-y !important;
> }
> ```
> 
> Fix will be made after [naver/egjs-axes#185](https://github.com/naver/egjs-axes/pull/185)

Thank you for help!
I've been using the 4.4.3 version of react-flicking since before, so I don't know why it's happening.
And I tried the method you provided, but it seems that the same issue still occurs in IOS.

**Comment by WoodNeck** [comment]
@hyeon-9yu
Did you try downgrading the version to 4.6.x?
If not, please try that way instead. We'll fix this asap in the next version :)

**Comment by malangfox** [comment]
@gbyesiltas 
We have released Flicking 4.7.1 that fixes this issue.
Try using version 4.7.1 and leave a message if you encounter any problems.

**Comment by gbyesiltas** [comment]
> @gbyesiltas
> We have released Flicking 4.7.1 that fixes this issue.
> Try using version 4.7.1 and leave a message if you encounter any problems.

Great, thank you :)

**Comment by limonte** [comment]
4.7.1 doesn't work as well :/

**Comment by gbyesiltas** [comment]
> 4.7.1 doesn't work as well :/

Hmm, 4.7.1 did work for me @limonte

**Comment by malangfox** [comment]
> > 4.7.1 doesn't work as well :/
> 
> Hmm, 4.7.1 did work for me @limonte

Can you check whether the touch-action css property of an element that uses horizontal flicking is automatically set to pan-y?
If you are using the ios Safari browser, this problem will be fixed in the next patch.

**Comment by limonte** [comment]
v4.7.2, still doesn't work Chrome on iPhone

**Comment by limonte** [comment]
v4.9.0 works fine 👍
