### ISSUE TITLE
egjs-flicking plugin 사용 시 문의드립니다.

### ISSUE THREAD

**Issue by ana59** [naver/egjs-flicking#676]
## Description

안녕하세요! egjs-flicking 플러그인을 유용하게 잘 사용하고 있습니다:)
몇가지 문의가 있어 이슈를 남겨봅니다.

보내드리는 Codepen 데모파일을 확인해주시면 감사하겠습니다ㅜㅜ
https://codepen.io/james-jung/pen/gOvOyop

1. 루프를 사용했고, 스와이프 시 메뉴6에서 메뉴1 콘텐츠가 보이고, 메뉴1에서 콘텐츠6이 보이는 현상이 있습니다..!
옵션 값이 잘못 되었을까요?

2. json을 통해 외부 데이터를 불러오면 새로고침 후 첫 메뉴버튼을 클릭 시 콘텐츠 잘림 현상이 있습니다. 메뉴버튼을 한번 더 클릭하면 그제서야 높이값이 늘어납니다! 해결 방법이 있을까요? Codepen 파일에서는 해당 현상이 안나타나네요…

<br>
개발자는 아닌지라 잘 만들어주신 플러그인을 다루는데에 시간이 좀 걸리네요ㅎ<br>
감사합니다:)

**Comment by WoodNeck** [comment]
@ana59님 안녕하세요
1. 저희 컴포넌트 버그로 보입니다. 제쪽에서도 두 번째 패널에서 마지막 패널로 이동할 때 해당 현상이 재현되네요.
해당 이슈는 수정 후 알려드리겠습니다.
당장은 한 번에 하나만 패널이 넘어가는 형태로 제약하여 이슈를 어느정도 방지하실 수도 있습니다.
`moveType: "strict"`를 사용하시면 됩니다.

2. 이건 말씀하신 "새로고침"이 정확히 어떤건지 확인이 필요할 것 같긴 한데요,
외부 데이터를 불러와서 내부 패널의 높이 변경시 Flicking은 이를 감지하지 못합니다.
외부 wrapper의 크기 변화는 감지하나, 성능상의 문제로 내부 패널의 높이 변화는 감지하지 않기 때문입니다.
외부 데이터를 불러와서 내부 패널의 높이가 변경 이후에 `resize` 메소드를 호출해보시면 좋을 것 같습니다.

**Comment by ana59** [comment]
네 감사합니다!

1. 말씀하신 <code class="notranslate">moveType: "strict"</code> 를 데모파일에서도 사용했는데요! 
<code class="notranslate">circular:  true</code> 또는 <code class="notranslate">horizontal: true; adaptive: true</code>기능과 함께 사용하면 이슈가 되는 것 같습니다ㅜㅜ
수정되면 알려주세요 ㅎㅎ

2. 그렇군요 알려주신 방법대로 해보겠습니다~

**Comment by ana59** [comment]
@WoodNeck님 네 감사합니다!

1. 말씀하신 <code class="notranslate">moveType: "strict"</code> 를 데모파일에서도 사용했는데요! 
<code class="notranslate">circular:  true</code> 또는 <code class="notranslate">horizontal: true; adaptive: true</code>기능과 함께 사용하면 이슈가 되는 것 같습니다ㅜㅜ
수정되면 알려주세요 ㅎㅎ

2. 그렇군요 알려주신 방법대로 해보겠습니다~

**Comment by ana59** [comment]
@WoodNeck님 답변이 늦었습니다!
답변 주신대로 최신 버전 설치하니 가지고 있던 문제들이 모두 해결되었습니다:)
다른 플러그인으로 대체해야하나 고민이 많았는데ㅜㅜ 빠르게 해결점을 알려주신 덕분에 유용하게 사용 할 수 있을 것 같습니다. 
감사합니다!
