### ISSUE TITLE
iOS 15 (safari) not able to drag/swipe

### ISSUE THREAD

**Issue by duncandejong** [naver/egjs-flicking#677]
## Description
On iOS 15 it is not possible to drag/swipe.
(tested on safari and chrome)

## Steps to check or reproduce
Open the [website](https://naver.github.io/egjs-flicking/) on your iPhone

**Comment by WoodNeck** [comment]
Hello @duncandejong!
I could reproduce this issue also on my iPad, we'll fix this asap.
Please use v4.6.x until then! The only difference is you can't use the `nested` in that version.

```sh
npm i @egjs/flicking@~4.6.0
```

**Comment by duncandejong** [comment]
Thanks for your quick reply, that fixed it!

**Comment by malangfox** [comment]
Hello @duncandejong.

Flicking 4.7.2 patch has been released, which fixes the problem that Flicking did not work in Safari browser in iOS environment.
Please try version 4.7.2 and let us know if you run into any problems.

**Comment by malangfox** [comment]
It has been confirmed that problems occur in the iOS environment even after version 4.7.2.
If you use version 4.7.3, this problem will be resolved.

If you still encounter this issue after version 4.7.3, please let us know.

**Comment by duncandejong** [comment]
Thank you so much @malangfox, I tested it, and works :-)
