### ISSUE TITLE
How can I see the showcase code

### ISSUE THREAD

**Issue by ChenWeihua123** [naver/egjs-flicking#699]
## Steps to check or reproduce

![image](https://user-images.githubusercontent.com/33150900/177307226-5b1d3381-3b45-4c44-8b50-7bfeb7d8bc5f.png)

**Comment by malangfox** [comment]
Hello @ChenWeihua123.

Currently there are no sample code for showcases in the documentation.
However you can check the implementation at [showcases](https://github.com/naver/egjs-flicking/tree/master/docs/src/showcases) folder in our repository.
I think this might be helpful.
