### ISSUE TITLE
nested flicking에서 동시 swipe 되는 문제

### ISSUE THREAD

**Issue by gusrb3164** [naver/egjs-flicking#704]
## Description

https://user-images.githubusercontent.com/34272561/177922955-7231641c-f924-424c-9f2c-9fd0a98a55a3.mov

모바일은 잘 작동하나 PC에서는 내부 flicking을 드래그 할 때, 밖의 flicking까지 swipe 되는 문제가 발생합니다.

## Steps to check or reproduce

1. version: @egjs/react-flicking": "^4.8.1"

2. <https://naver.github.io/egjs-flicking/Demos#nested-flickings> demo는 PC에서 잘 작동합니다. demo와 영상에 나오는 flicking의 차이는 flicking-camera에 직접 display: flex 속성을 준 것입니다.

**Comment by malangfox** [comment]
안녕하세요 @gusrb3164 님.

남겨주신 현상의 원인을 파악하고자 겪고 계신 문제를 재현하는 [데모](https://codepen.io/malangfox/pen/NWYNbmM)를 만드는 과정에서 flicking-camera에 display: flex 를 추가해보았는데요, 인라인 스타일과 css 양쪽 모두 display: flex 를 적용해보아도 해당 현상의 재현이 이루어지지 않았습니다.
flicking-camera에 적용된 flex 외의 다른 발생 조건이 있는 것으로 추정되는데요, 혹시 문제가 발생한 코드를 보다 자세히 확인해볼 수 있을까요?

**Comment by gusrb3164** [comment]
우선 flicking horizontal 옵션이 잘 작동하지 않는 알수없는 이슈가 있어서 styled-components와 Swiper라는 컴포넌트로 자체 flex 속성을 주는 방식으로 custom 하여 사용하고 있습니다.

```tsx
export interface SwiperProps extends Omit<Partial<FlickingProps>, 'plugins'>, Partial<FlickingOptions> {
  containerStyle?: CSSProperties
  margin?: string
  swiperRef?: RefObject<Flicking>
  }
}

const Swiper: React.FC<SwiperProps> = ({ swiperRef, margin, containerStyle, children, horizontal = true, pluginOption, ...props }) => {
  return (
    <Container
      pagination={pluginOption?.pagination}
      margin={margin}
      style={{ overflowX: pluginOption?.pagination ? undefined : 'hidden', padding: '10px 0', ...containerStyle }}
      vertical={!horizontal}>
      <Flicking
        ref={swiperRef}
        {...props}>
        {children}
      </Flicking>
    </Container>
  )
}

export default Swiper

interface ContainerProps {
  vertical: boolean
  margin: string | undefined
}

const Container = styled.div<ContainerProps>`
  position: relative;
  > div {
    > div {
      display: flex;
      ${({ vertical }) => vertical && 'flex-direction: column'}
      > div {
        ${({ margin }) => margin && `margin: ${margin}`}
      }
    }
  }
`

```

### 가장 상위 flicking 컴포넌트는 아래와 같습니다.

```tsx
<Swiper
        moveType="strict"
        containerStyle={{ padding: 0 }}
        renderOnlyVisible
        defaultIndex={tabIdx}
        swiperRef={swiperRef}
        onVisibleChange={onSwiperVisibleChange}
        onMoveEnd={onSwiperMoveEnd}
        onWillChange={onSwiperWillChange}>
        <S.TabContainer isScrollDown={isScrollDown}>
          <Near isEnabled={visibleTabIdxs.includes(0) && !isMovingByClickedTab} />
        </S.TabContainer>
        <S.TabContainer isScrollDown={isScrollDown}>
          <New isEnabled={visibleTabIdxs.includes(1) && !isMovingByClickedTab} />
        </S.TabContainer>
        <S.TabContainer isScrollDown={isScrollDown}>
          <Hot isEnabled={visibleTabIdxs.includes(2) && !isMovingByClickedTab} />
        </S.TabContainer>
        <S.TabContainer isScrollDown={isScrollDown}>
          <Free isEnabled={visibleTabIdxs.includes(3) && !isMovingByClickedTab} />
        </S.TabContainer>
        <S.TabContainer isScrollDown={isScrollDown}>
          <Now isEnabled={visibleTabIdxs.includes(4) && !isMovingByClickedTab} />
        </S.TabContainer>
        <S.TabContainer isScrollDown={isScrollDown}>
          <Sinjum isEnabled={visibleTabIdxs.includes(5) && !isMovingByClickedTab} />
        </S.TabContainer>
        <S.TabContainer isScrollDown={isScrollDown}>
          <Tarot isEnabled={visibleTabIdxs.includes(6) && !isMovingByClickedTab} />
        </S.TabContainer>
        <S.TabContainer isScrollDown={isScrollDown}>
          <Saju isEnabled={visibleTabIdxs.includes(7) && !isMovingByClickedTab} />
        </S.TabContainer>
</Swiper>
```

### 내부 컴포넌트에 존재하는 flicking 컴포넌트는 아래와 같습니다.

```tsx
<Swiper align="prev" margin="0 0.6rem">
        {cards?.pages[0].cards.map((card) => (
          <div>
            <NewEvaluationCard card={card} />
          </div>
        ))}
</Swiper>
```

---

### 아래 사진은 상위 flicking의 css 입니다.

1. flicking-viewport

![image](https://user-images.githubusercontent.com/34272561/177938609-8d8fe428-0607-45a6-81ab-4add583a5e16.png)

2. flicking-camera

![image](https://user-images.githubusercontent.com/34272561/177938821-0d80914f-123e-43cf-b669-113b6954e68a.png)

### 아래 사진은 내부 flicking의 css 입니다.

1. flicking-viewport

![image](https://user-images.githubusercontent.com/34272561/177939130-a78982cd-cabf-4ca9-b290-d709c2671931.png)

2. flicking-camera

![image](https://user-images.githubusercontent.com/34272561/177939193-3e8743f0-4e7d-495d-af08-f8e6dc46ffdf.png)

**Comment by malangfox** [comment]
남겨주신 내용을 확인하였으며, 이와 유사한 환경에서 해당 현상의 재현 및 수정이 완료된 이후 연락을 남기도록 하겠습니다.
또한 `horizontal` 옵션이 원활하게 작동하지 않는 경우에 대해서도 자세한 상황을 남겨주실 수 있다면 유사한 사례가 있는지 확인을 거쳐보겠습니다.

**Comment by hyeon-9yu** [comment]
감사합니다. 
horizontal 문제 같은 경우는 swiper 동작 자체에 문제는 없으나,
horizontal인 경우에 panel의 display가 'block'속성으로 인해 배치가 제대로 안돼서 발생한 문제점이였던것으로 파악됩니다.

**Comment by gusrb3164** [comment]
@malangfox 
제가 위쪽에 ^4.8.1로 작성했었는데 실제 작동버전이 4.6.0 이였습니다.
이슈가 발생하는 버전이 4.6.x 버전으로 생각되는데 4.7.0 부터는 해당 이슈가 발생하지 않습니다.
그 사이에 해결될 수 있었던 변경점이 있을까요?

**Comment by malangfox** [comment]
이슈에 남겨주신 `nested` 옵션은 Flicking 4.7.0 버전부터 지원하기 시작한 옵션입니다.
4.7.0 이상 버전에서 원활하게 작동한다면 버그로 분류하지 않아도 될 것 같습니다.

**Comment by gusrb3164** [comment]
그렇군요 버그가 아니였고 버전에 대해 제대로 확인하지 못했네요 죄송합니다.
