### ISSUE TITLE
Production build looks different than development build

### ISSUE THREAD

**Issue by 42savage** [naver/egjs-flicking#708]
## Description
Flicking carousel looks different on development build than on production build.
When on dev something like flex direction is in row like it should be, but on prod its like on column.

## Steps to check or reproduce
At first check how it looks like on development build, then check the production build.
Im talking about
![image](https://user-images.githubusercontent.com/47255032/179366862-479d10a1-62c9-4263-8cd8-b42b692c7208.png)

![image](https://user-images.githubusercontent.com/47255032/179366831-d330c24c-f992-4dae-be7e-3a47037e78f4.png)

Link to codesandbox: https://codesandbox.io/s/kind-murdock-3bmuyh

edit: I found out that the reason of that is problem with importing flicking css styles
 import '@egjs/vue-flicking/dist/flicking.css'

**Comment by malangfox** [comment]
Hello @42savage.

The issue you reported appears to be similar to these issues.
Please check this issues and tell me if the issue doesn't resolve.
- https://github.com/naver/egjs-flicking/issues/573
- https://github.com/naver/egjs-flicking/issues/654 ( A translator might be required to check this issue. )
- https://github.com/naver/egjs-flicking/issues/680
