### ISSUE TITLE
내부 `onChange` 처리시 Cannot read properties of null (reading 'offsetX') 예외가 발생하는 문제

### ISSUE THREAD

**Issue by async3619** [naver/egjs-flicking#709]
## Description

현재 개발중인 웹사이트에서 특정 DOM swipe를 시도할 때, `onMoveStart` 이벤트를 이용하여 해당 DOM 오브젝트가 특정 조건에 만족되면 `e.stop()` 메서드를 이용하여 swipe를 취소하는 구현을 시도했습니다.

구현은 러프하게 표현하자면 다음과 같습니다:

```ts
private handleMoveStart = (e: MoveStartEvent<Flicking>) => {
    if (
        !e.axesEvent.inputEvent ||
        !("srcEvent" in e.axesEvent.inputEvent) ||
        !(e.axesEvent.inputEvent.srcEvent instanceof TouchEvent)
    ) {
        return;
    }

    const path = e.axesEvent.inputEvent.srcEvent.composedPath();
    for (const target of path) {
        if (!(target instanceof HTMLElement)) {
            continue;
        }

        if (target.classList.contains("no-swipe")) {
            e.stop();
        }
    }
};
```

해당 구현이 이 이슈에 영향을 주는지는 파악할 수 없었으나, `axisEvent`의 `inputEvent` 속성이 null 인 상태로 `onChange` 이벤트를 처리하는 도중 문제가 발생하는 것으로 보여집니다.

![chrome_xLJxMYFc68](https://user-images.githubusercontent.com/5947388/179674788-f6097910-9749-4a54-9654-c82c27a64a28.png)

## Steps to check or reproduce

PC 환경에서 크롬 개발자 도구를 통해 모바일 환경으로 접근하여 빠른 속도로 이동 처리를 하려 할 때 이 문제가 발생했습니다.

**Comment by dontwan** [comment]
Here the same problem in a Vue project when I try to call the `moveTo` function in a watcher;

```ts
  @Ref('tab-controller')
  private tabController!: Flicking

  @VModel({type: Number, default: 0})
  private activeIndex!: number

  @Watch('activeIndex')
  private async watchActiveIndex() {
    if (this.tabController.index !== this.activeIndex) {
      await this.tabController.moveTo(this.activeIndex)
    }
  }
```

I also got the same error as @async3619 described
![Schermafbeelding 2022-07-22 om 15 14 46](https://user-images.githubusercontent.com/24223904/180446803-6ee647e9-d6b7-47ad-95bc-02d7ae70e5bd.png)

**Comment by malangfox** [comment]
Hello @async3619 .

We've checked this error occur if we try to move the Flicking in a way other than the native event while the Flicking is in the holding state.
The reason for the error when @dontwan uses `moveTo` seems to be that Flicking, which was in the holding state, tried to move through `moveTo` instead of a native event.

We will contact you when a version that fixes this issue is released. Thank you!

**Comment by malangfox** [comment]
@async3619 @dontwan 

Version 4.9.2 has been released, which resolves this issue.
Please try newest version and let us know if you encounter any other issues.

**Comment by async3619** [comment]
@malangfox really appreciate it

**Comment by async3619** [comment]
I think we should close this and I'll check out this would release works well though some tests and make a new issue when we find problems
