### ISSUE TITLE
Flicking 과 Grid를 같이사용할때 문제

### ISSUE THREAD

**Issue by jinpark0625** [naver/egjs-flicking#712]
## Description

https://naver.github.io/egjs-flicking/Demos#grid
여기에 나와있는 Demo처럼 구현했을때 리액트에서 에러가 발생합니다.
<img width="535" alt="스크린샷 2022-07-27 오전 12 13 10" src="https://user-images.githubusercontent.com/69961780/181159806-33c2f9c8-d00b-40fc-8597-4dfe473c604f.png">
<img width="1219" alt="스크린샷 2022-07-27 오전 12 13 32" src="https://user-images.githubusercontent.com/69961780/181159840-62ae271e-9cab-4e2b-9a3d-4dcc398da150.png">

**Comment by WoodNeck** [comment]
@jinpark0625님 안녕하세요.
데모 코드를 확인해보시면, FrameGrid를 직접 사용하는 대신 일반 엘리먼트를 렌더링한 뒤 new FrameGrid() 와 같은 방식으로 초기화하는 것을 보실 수 있는데요
이는 Ref Forwarding이 되지 않은 경우 컴포넌트를 패널로 사용할 수 없기 때문입니다.

다음 가이드를 확인해주세요.
- https://naver.github.io/egjs-flicking/docs/quick-start (React 탭을 누르시면 됩니다)

하단의 Bypassing 부분을 보시면 이를 해결하는 방법이 나와있는데요
가장 간단한 방법은 FrameGrid 상단에 \<div\> 엘리먼트를 부모 엘리먼트로 하나 추가해주시면 됩니다.
