### ISSUE TITLE
virtual 옵션의 caching 전략이 무엇인가요?

### ISSUE THREAD

**Issue by minnsane** [naver/egjs-flicking#713]
```
flickingOptions = {
    panelsPerView: 3,
    circular: true,
    virtual: {
      cache: true,
      panelClass: 'panel',
      renderPanel: (panel: any) =>
        `<img src="https://dummyimage.com/200x200/ddd/000&text=panel${panel.index}"></img>`,
      initialPanelCount: 10,
    },
  };
```

위와 같은 옵션으로 virtual을 사용했을 때, panel 내부에서 그리는 이미지는 한번 다운로드 받으면 캐싱된다고 생각을 했는데요.
플리킹을 넘길 때, 어떤 때는 새로 이미지를 받아오지 않고, 또 어떤 때는 새롭게 받아옵니다.
<img width="724" alt="스크린샷 2022-07-28 오후 5 21 20" src="https://user-images.githubusercontent.com/17758538/181458423-5246c7b7-37d9-4cf9-81ff-fa6a3720be69.png">

캐싱 기간이나 갯수에 대한 policy가 있는걸까요?

**Comment by WoodNeck** [comment]
@minnsane님 안녕하세요.

virtual의 cache 옵션의 경우 엘리먼트를 캐시하는 것이 아닌, render 메소드를 통해 렌더링된 이전의 innerHTML 정보를 저장합니다.
- https://naver.github.io/egjs-flicking/docs/api/Flicking#virtual

render 메소드 내부에서 시간이 오래 걸리는 작업을 할 경우 cache 옵션을 사용하시면 이전 innerHTML 정보를 그대로 사용하실 수 있기 때문에 약간의 성능 향상을 기대할 수 있습니다.

말씀하신 이미지의 경우 브라우저가 캐시를 처리하며, Flicking에서 따로 처리하진 않습니다.
확인하실 때 네트워크 탭의 Disable Cache를 체크하셨거나, 혹은 요청하는 URL의 패러미터가 일부 변경되었을 경우 이미지를 다시 로드하기 때문에 위와 같은 현상이 나타난 것으로 생각됩니다.

**Comment by minnsane** [comment]
감사합니다!
