### ISSUE TITLE
React에서 Flicking Event사용시 setState 변경이 안되는 문제

### ISSUE THREAD

**Issue by kooinsung** [naver/egjs-flicking#716]
## Description

https://naver.github.io/egjs-flicking/docs/api/Flicking#events 문서에 있는 Event를 사용해서 state를 변경할려고 했으나 state 변경이 안되는군요 🤔 
원인 파악을 계속 해보았으나, 파악을 못하여서 이렇게 이슈를 남깁니다.

## Steps to check or reproduce

https://codesandbox.io/s/egjs-flicking-v4-on-move-end-forked-x3rfrd

**Comment by malangfox** [comment]
안녕하세요 @kooinsung 님.

남겨주신 재현 코드를 포크해서 [useState를 사용하는 예제](https://codesandbox.io/s/egjs-flicking-v4-on-move-end-891kwx)로 확인을 거친 결과 state의 변경은 정상적으로 이루어지는 것으로 확인이 됩니다.
하지만 state가 변경된 이후에도 기존에 등록된 이벤트 핸들러 함수 내에서 state가 변경되기 전 값으로 작동하는 오류가 저희 족 컴포넌트에서 확인되었습니다.

위 내용에 대해서는 예제 상단의 버튼을 눌러 state 변화 로그를 추가할 때와 패널을 움직여서 state 변화 로그를 추가하려 할 때, 패널을 움직이면 로그가 초기화되는 현상을 확인해보실 수 있습니다.
남겨주신 데모에서도 마찬가지로 위 현상으로 인해 holding이 초기 상태로만 로그가 남았던 것 같네요.

이 오류가 수정된 버전이 배포된 이후 연락을 남기도록 하겠습니다. 오류를 확인해주셔서 감사합니다.

**Comment by kooinsung** [comment]
> 안녕하세요 @kooinsung 님.
> 
> 남겨주신 재현 코드를 포크해서 [useState를 사용하는 예제](https://codesandbox.io/s/egjs-flicking-v4-on-move-end-891kwx)로 확인을 거친 결과 state의 변경은 정상적으로 이루어지는 것으로 확인이 됩니다. 하지만 state가 변경된 이후에도 기존에 등록된 이벤트 핸들러 함수 내에서 state가 변경되기 전 값으로 작동하는 오류가 저희 족 컴포넌트에서 확인되었습니다.
> 
> 위 내용에 대해서는 예제 상단의 버튼을 눌러 state 변화 로그를 추가할 때와 패널을 움직여서 state 변화 로그를 추가하려 할 때, 패널을 움직이면 로그가 초기화되는 현상을 확인해보실 수 있습니다. 남겨주신 데모에서도 마찬가지로 위 현상으로 인해 holding이 초기 상태인 false로만 로그가 남는 오류가 발생한 것 같네요.
> 
> 이 오류가 수정된 버전이 배포된 이후 연락을 남기도록 하겠습니다. 오류를 확인해주셔서 감사합니다.

빠른 답변 감사합니다! @malangfox 
추가 질문 드려봅니다. 제가 처리하고 싶은 로직은 `onChanged`에서 처리를 하고 싶은 상황입니다. (기존 v3에서는 onChange에서 처리)
[예제](https://codesandbox.io/s/egjs-flicking-v4-on-move-end-forked-x3rfrd?file=/src/App.js:516-525)에서 보면 holdStart handler에서 holding의 상태를 true로 변경했는데, handleChanged handler에서는 holding의 상태가 false로 찍히고 있습니다. 
onChanged에서의 state 변경감지는 어떻게 처리가 필요할까요?

**Comment by malangfox** [comment]
위 오류가 수정될 경우 onChanged에서 사용하실 이벤트 핸들러 내부에서 정상적으로 최신의 state 값을 사용하실 수 있습니다.
오류가 수정된 버전이 배포되고 나면 이슈 본문에 작성하여주신 데모의 경우 react-flicking의 버전을 올리기만 하여도 holding 상태의 변경이 올바르게 감지될 것입니다.

**Comment by kooinsung** [comment]
아하! 확인 감사합니다!
혹시 실례가 안된다면... 배포 주기가 어떻게 되는지 알수 있을까요?

**Comment by malangfox** [comment]
버그 수정의 경우 진행 중인 작업들이 마스터 브랜치에 머지되고 나면 가능한 빠른 시일 내에 패치로 나가고 있습니다.
이슈를 남겨주신 현상에 대해서도 이번 주 혹은 다음 주 중으로 해결 후 배포가 이루어질 것 같습니다.

**Comment by malangfox** [comment]
남겨주신 이슈가 해결된 react-flicking 4.9.3 버전이 배포되었습니다.
4.9.3 버전을 사용하여보시고 문제가 지속될 시 이슈를 남겨주세요.

**Comment by kooinsung** [comment]
> 남겨주신 이슈가 해결된 react-flicking 4.9.3 버전이 배포되었습니다.
4.9.3 버전을 사용하여보시고 문제가 지속될 시 이슈를 남겨주세요.

감사합니다!
4.9.3버전 적용해 보고 특이사항이 있을 경우 다시 이슈 업해보겠습니다.
