### ISSUE TITLE
React Flicking: 데이터 갱신 문제

### ISSUE THREAD

**Issue by leye195** [naver/egjs-flicking#719]
## Description

패널 데이터 목록을 api를 통해 불러오고 일정 간격으로 새로운 데이터들로 교체하고자 하며
데이터가 갱신되기 이전까지는 `circular: true` 옵션을 통해 이전 데이터를 계속 보여주고자 합니다.

데이터 갱신시 데이터가 의도와 다르게 다른 값이 노출되는 이슈가 발생하게 되는데 혹시 배널 데이터 변경을 감지 혹은 변경될 경우 index 값을 변경 할 수 있는 방법이 있을까요?

![image](https://user-images.githubusercontent.com/30601503/185788977-5d91cf5a-c243-417f-977e-805d7112a908.png)

## Steps to check or reproduce

https://codesandbox.io/s/cocky-diffie-vd0e4z?file=/src/App.js

**Comment by malangfox** [comment]
안녕하세요 @leye195 님.

남겨주신 현상에 대해 확인을 거쳐보았으며 데이터가 갱신된 이후 인덱스가 잘못 설정되는 경우는 renderOnlyVisible 옵션이 활성화되었을 때 발생하는 오류로 추정됩니다.
이 현상의 자세한 원인을 확인하며 오류를 수정하는 중에는 renderOnlyVisible 옵션을 비활성화시켜서 [일시적으로 문제를 해결할 수 있을 것 같습니다.](https://codesandbox.io/s/flicking-circular-update-data-ytyp83?file=/src/App.js)
)
이슈가 해결된 패치가 배포될 시 연락을 남기도록 하겠습니다.

감사합니다.

**Comment by malangfox** [comment]
@leye195 

`renderOnlyVisible` 옵션이 비정상적으로 작동하던 것은 훅 내부에서 패널 목록을 갱신할 때 패널 목록이 올바르게 갱신이 이루어지지 않던 오류로 인해 발생하던 것으로 확인되었습니다.
남겨주신 이슈가 해결된 react-flicking 4.10.1 버전이 배포되었습니다. 4.10.1 버전을 이용하여보시고 문제를 겪으시게 된다면 이슈를 남겨주세요.
