### ISSUE TITLE
ngx-flicking 천천히 패닝할때 패닝완료된 후에 패널 넘어가거나 돌아가지 않고 멈춰있는 현상이 있습니다.

### ISSUE THREAD

**Issue by minnsane** [naver/egjs-flicking#721]
## Steps to check or reproduce

**패키지버전**
- "@egjs/ngx-flicking": "4.9.2"

**flicking option**
- duration: 150
- align: 'prev'
- panelsPerView: 1
- renderOnlyVisible: true

**재현코드**
https://codesandbox.io/s/panning-stop-wmydx0

**특징**
- 천천히 패닝동작을 할 때, 패닝이 완료된 후에도 그대로 정지되어있는 현상이 있습니다.
- 첨부동영상
https://user-images.githubusercontent.com/17758538/185887501-a1ee701f-2ec1-4140-b9b6-9f875d93da40.mov

감사합니다!!

**Comment by minnsane** [comment]
@malangfox 안녕하세요~
천천히 패닝할 때 뿐 아니라, 패닝 축이 대각선일 때 해당 현상 더 재현이 잘 되는것을 발견하였습니다!
검토에 도움이 되셨으면 하는 마음에 첨부합니다.

https://user-images.githubusercontent.com/17758538/186084332-cf49183a-841d-4028-99a8-f24baa41817c.mov

**Comment by minnsane** [comment]
@malangfox 
안녕하세요~~ 알려주신 workaround는 이미지에 잘 적용할 수 있었습니다.
다만, 패널 안에 a 태그가 있는 경우, `pointer-events: none`을 적용하기가 어려운데요. 
혹시 이 경우에 적용할 수 있는 방법도 있을까요?

**Comment by malangfox** [comment]
남겨주신 이슈는 이미지의 드래그로 인해 발생하는 오류이므로 위 방법 외에도 이미지의 드래그만을 막는 방법을 사용해서 해결될 수 있을 것 같습니다.
혹시 패널 안에 a 태그가 있는 경우가 이미지 영역 내부에 a 태그가 자리잡고 있는 형태일까요? 적용이 어려운 예시를 남겨주시면 확인해보겠습니다.

**Comment by malangfox** [comment]
안녕하세요. 이슈를 남겨주신 현상이 해결된 ngx-flicking 4.9.3 버전이 배포되었습니다.
최신 버전을 이용하여보시고 문제를 겪게 되신다면 연락을 남겨주세요.

**Comment by minnsane** [comment]
@malangfox 4.9.3에서 확인하였습니다. 감사합니다!
