### ISSUE TITLE
Move 동작을 취소할수있는 방법 문의

### ISSUE THREAD

**Issue by Jonir227** [naver/egjs-flicking#725]
## Description

안녕하세요. 플리킹을 이용해서 서비스 구현을 하고있습니다.

화면을 롤링하는 카드를 계속 보여주면서 원하면 좌우로 이동할수있게 하는 ui를 만드려고하는데요. ([참고](https://influencercenter.naver.com/brandconnect/intro))

이동중에 인덱스 변경이 불가능해서 해당 기능 없이 일단 출시가 나간상태입니다 ㅠ

moveTo에 duration을 준 상태에서 천천히 움직이고있을때 다른 인덱스로 이동하려고하면 에러가 발생하고있는데요.

혹시 이동중에 이동을 취소하거나 강제로 다른 패널로 이동할수있는 방법이 있을까요?

현재 버전 3을 사용하고있고, 4에서 가능하다면 버전업헤서 적용할 계획입니다.

## Steps to check or reproduce

v4 를 사용해서 간단하게 현재 구현된 방식대로 구현해보았습니다.

예제: https://codesandbox.io/s/modern-field-hjpqf0?file=/src/App.tsx

**Comment by malangfox** [comment]
안녕하세요 @Jonir227 님.

`moveTo` 를 통해 패널이 이동하며 애니메이션이 재생 중일 때 다른 애니메이션을 새로 재생하거나 사용자가 직접 패널을 조작하는 기능은 현재 지원하고 있지 않습니다.
그러나 이후의 버전에서 재생 중인 애니메이션을 중지시키거나 목적지를 변경할 수 있는 메서드를 지원하는 것을 검토하여보고 있으며, 추후에 관련 기능이 도입된 버전이 배포될 시 이용하실 수 있도록 연락을 남기도록 하겠습니다.

**Comment by Jonir227** [comment]
@malangfox 님 확인 감사합니다!  작업에 참고하도록 하겠습니다! 고맙습니다.

**Comment by malangfox** [comment]
@Jonir227 
재생 중인 애니메이션을 중단시키는 `stopAnimation` 메서드와 재생 중인 애니메이션의 목적지를 변경하는 `updateAnimation` 메서드가 추가된 4.10.0 버전이 배포되었습니다.
이동 중에 이동을 취소하는 방법으로 `stopAnimation` 을 이용하여보시고 문제를 겪으시게 된다면 이슈를 남겨주세요.
