### ISSUE TITLE
An error occurs when constructing a Flicking module

### ISSUE THREAD

**Issue by UYEONG** [naver/egjs-flicking#73]
## Description

An error occurs when constructing a Flicking module

## Steps to check or reproduce

I'm using webkacp v3.10.0, Typescript v2.6.2 and the code is as follows:

```js
import * as Flicking from "@egjs/flicking";
const flicking = new Flicking(this.wrapper);
```

Error message:

![2018-01-16 5 29 55](https://user-images.githubusercontent.com/1321707/34980919-4e48fe56-fae9-11e7-8f34-c32a417da135.png)
![2018-01-16 5 30 01](https://user-images.githubusercontent.com/1321707/34980924-4fa79f8c-fae9-11e7-8158-249e1b793463.png)

Axes refer to `/outjs/` when it's a `module`. However, `index.js` of `/outjs/` seems to be generated from `PanInput` and it can't be referenced as a static property of `Axes`.

Fix code. but side-effects are expected So I won’t give you a PR.
```js
// Flicking.js(@egjs/flicking)
import Axes, {PanInput} from "@egjs/axes";
```

**Comment by sculove** [comment]
@UYEONG #72 issue is resolved, the issue will be resolved automatically.

**Comment by UYEONG** [comment]
@sculove OK. Thanks!
