### ISSUE TITLE
Swipe only one photo

### ISSUE THREAD

**Issue by kazvaggos** [naver/egjs-flicking#732]
## Description
Hello team,
As we are migrating to Vue 3, we are trying to migrate Vue-Flicking from v3 to v4.10.0.
We noticed that in version 4, when swiping fast in mobile, more than one photos are changing. Is there a way when swiping, to change only one photo instead, in order for us to work like v3?

**Comment by malangfox** [comment]
Hello @kazvaggos.

You can prevent moving more panels due to the user's fast swipe speed by setting the [deceleration](https://naver.github.io/egjs-flicking/Options#deceleration) option.
Can you check the behavior after setting this option high enough for the UI you want to use?

**Comment by WoodNeck** [comment]
Try `moveType: "strict"`

**Comment by kazvaggos** [comment]
Awesome! Worked! Thanks a lot team :D
