### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by maddestscooter** [naver/egjs-flicking#733]
When I am trying to navigate through the slides using the tab key, the slides outside of viewport do not seem to be accessible.

Is this because accessibility is not properly supported by the slider or is this an issue with my code?

**Comment by malangfox** [comment]
Hello @maddestscooter.

Flicking does not support focusing behavior through the tab key, that causes scrolling which conflicts with how we apply `transform` style property to move the panel.
If you are looking for a way to move the panel position when a specific key is pressed, we recommend using the method from Flicking such as `prev` and `next`.

**Comment by malangfox** [comment]
Since there is no further comment, we will close the issue.
