### ISSUE TITLE
egjs-flicking 3.7.0에서 moveType:"freeScroll" 일때 버튼을 이용한 제어

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#737]
## Description
var 스크롤변수 = $("영역아이디").egFlick({
	circular:false,
	deceleration:.0024,
	moveType:"freeScroll",
	bounce:15,
	gap:-15,
	bound:true
});

$("영역페이징아이디 .pagen_prev").on("click",function(){
	스크롤변수.prev();
})

$("영역페이징아이디 .pagen_next").on("click",function(){
	스크롤변수.next();
})

와 같이 구성하였는데요

이번에 좌우버튼을 추가해달라는 요청이 있어서 기존 freescroll에 버튼 기능을 추가 해보려고 하는데

우선 freeScroll이다 보니 next및 prev가 한개씩 동작하다보니 화면 보여지는 다음게 움직이는게 아니라

| 0 1 2 3  | 4 5 6

화면폭에 0,1,2,3이 보이고 4가 보이려면 next를 두번 더 눌러줘야 가고 화면 끝까지 이동했을때는 next버튼이 사라져야 하고

반대로 처음일 경우에는 이전 버튼을 감추고 싶은데 freeScroll에서 가능할까요?

**Comment by malangfox** [comment]
안녕하세요 @changdongchun 님.

남겨주신 내용을 기반으로 [데모](https://codepen.io/malangfox/pen/YzLbLbj)를 만들어보았는데요, 좌우 버튼을 이용한 제어에서 필요로 하시는 기능들이 포함되어 있는지 확인하여보시면 좋을 것 같습니다.

우선 `moveType: "freeScroll"` 에서 이전/다음 버튼을 이용해서 패널을 움직이는 구현은 남겨주신 내용과 같이 `prev()` 와 `next()` 를 이용하여 가능하며 만약 버튼의 동작에 다른 규칙을 추가하고 싶은 경우 대신 `moveTo` 메서드를 사용해서 특정한 패널로 이동하게끔 설계하여보시면 되겠습니다. 
남겨주신 예시에서 화면에 0, 1, 2, 3이 보이는 상태에서 4가 보이려면 next를 두 번 더 눌러주게끔 해야 하는 동작이 정확히 어떤 내용인지 자세히 알 수 있다면 위 데모를 그에 맞게 보완해보겠습니다.

또한 현재 패널 위치에 따라 이전/다음 버튼을 보이지 않게 하는 구현은 Flicking의 현재 Panel 인덱스가 변경될 때 발생하는 `change` 이벤트를 통해 가능합니다. 이벤트에서 새로 설정된 Panel의 인덱스를 `getPanelCount()`와 비교해서 마지막까지 도달했는지 여부를 확인 후 버튼의 표시 여부를 설정하면 되겠습니다.

안내드린 내용 중 추가적으로 궁금하신 부분이 있거나 더 필요한 구현이 있으시다면 편히 코멘트를 남겨주세요.

**Comment by changdongchun** [comment]
이전 버전 문의라 반즘은포기하고 있었는데 정확한 답변 감사드립니다.
