### ISSUE TITLE
[react-flicking] PanelsPerView does not update

### ISSUE THREAD

**Issue by PhiCross5** [naver/egjs-flicking#742]
## Description

- On react, changing the `panelsPerView` property during runtime does not affect the corresponding `panelsPerView` property on the object that backs the `<Flicker />` component.
- On the other hand, preparing a `Ref` and setting `flicker.current.panelsPerView` resizes the component automatically.
- The property itself works if you keep it hardcoded, it just happens that the underlying state of the component doesn't follow the property.

## Steps to check or reproduce

- 1) Set up a `create-react-app` project 
- 2) Replace the `<App/>` tag with this `<FT />` tag (rename the import on `index.js` as well):
```
import * as React from 'react'
import { useRef } from 'react'

import Flicking from '@egjs/react-flicking'
import "@egjs/react-flicking/dist/flicking.css"

function FT(){
	const sample_panel = [1,2,3];
	const [nPans, setNPans] = React.useState(2)

	const theFlicking = useRef(null)

	return (
		<div style={{width:"100%",height:"100%"}}>
			<button style={{
				width:"270px", 
				backgroundColor:"#335FE1", 
				textAlign:"center",
				color:"#E9DAE2",
				fontWeight:"bold",
				fontSize:"60px" }}
 
				//change panels-per-view on clicking the button.
				onClick={() => {
					console.log("toggle clicked.")

					//using temporary variable for new panel count
					let marau=1
					if(theFlicking.current.panelsPerView==1){
						marau = 2
					}
					else{
						marau = 1
					}
					//none of these change the panels.
					theFlicking.current.forceUpdate()
					theFlicking.current.resize()

					//setting the variable directly on the class works.
					theFlicking.current.panelsPerView=marau

					//reset index directly.
					theFlicking.current.moveTo(0)

					console.log("toggle button clicked, Flicking.panelsPerView is now " + theFlicking.current.panelsPerView)
				}}>
		TOGGLE</button>
				<h5>panelsPerView react property is now {nPans}</h5>
				<Flicking
					//React ref to call methods and set properties.
					ref={theFlicking}

					//Changing this property on the component does not change the corresponding property on the javascript object.
					panelsPerView={nPans}

					align="prev"
					onChanged={() => {
						if (nPans==2){
							setNPans(1)
						}
						else{
							setNPans(2)
						}
					}}
				>
					{sample_panel.map((e, i) => 
						<div className="flicking-panel" key={i} ><div width="100%"><h2>{e}</h2></div></div>)
					}
				</Flicking>
		</div>
	)
}

export default FT;
```
If you set things up correctly, hitting up the development server (usually `localhost:3000`) shows a test page.
- 3) Click the "TOGGLE" button at the top of the page. It sets the property directly on the Flicker object, which then resizes the panels to match.
- 4) Flick on the Flicker. Everytime the index changes, the `nPans` state variable toggles between 1 and 2, thus changing the `panelsPerView` property on the JSX element, but the Flicker object does not resize the panels to match.

## some additional details
- calling `resize()`, `forceUpdate()`, one or both, they don't trigger panel resize.

**Comment by malangfox** [comment]
Hello @PhiCross5.

This issue has been confirmed as a bug with our component.
Thanks for the detailed reproduction procedure.

We will contact you when a patch that fixes the bug is released.

**Comment by malangfox** [comment]
@PhiCross5 

react-flicking 4.10.3 has been released, which fixes this issue.
Try using version 4.10.3 and let us know if you encounter any problem.
