### ISSUE TITLE
[vue-flicking] export type { RenderingStrategy, NormalRenderingStrategyOptions } build error

### ISSUE THREAD

**Issue by WerhwolfXII** [naver/egjs-flicking#744]
## Description

After installing the plugin on a vue 2 project, the build was failing with some error
![image](https://user-images.githubusercontent.com/117442918/199944800-866b66eb-a62d-42c9-8468-5ab364640d44.png)

## Steps to check or reproduce
- Install the plugin using `npm install --save @egjs/vue-flicking`
- Stop the project build if there is a active one (or relaunch docker containers)
- Build fails with error

**Comment by malangfox** [comment]
Hello @WerhwolfXII.

This could be an error that occurs when using a typescript version that cannot use the `export type` syntax.
It seems to be resolved by changing the version of typescript, and we would like to check the version of typescript you are using.

**Comment by WerhwolfXII** [comment]
Thanks for your answer @malangfox 

![image](https://user-images.githubusercontent.com/117442918/201636689-930f8aec-d0a6-4ad1-a8bd-af3b5ed284f4.png)
Here is my typescript version. I tried to update it to newer versions, but the plugin was still not working

**Comment by malangfox** [comment]
`export type` has been added in [typescript 3.8](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/), you might use typescript version 3.8 or higher.
Since `"typescript": "~3.5.3",` may not install versions 3.6 or higher. can you try changing the version of typescript to be installed?

**Comment by malangfox** [comment]
Since there is no further comment, we will close the issue.
