### ISSUE TITLE
npm install error in root directory

### ISSUE THREAD

**Issue by yongilkim01** [naver/egjs-flicking#752]
## Description

While doing npm install in the root directory, I saw that the husky module was causing problems. Of course, this may not be the problem, but once the log is displayed as below.

## Steps to check or reproduce

code: sudo npm install

result:
<img width="640" alt="스크린샷 2022-11-18 오전 12 25 38" src="https://user-images.githubusercontent.com/101537874/202487222-87d4a5f4-de15-4f57-a8b3-e9fd490c4e12.png">

**Comment by malangfox** [comment]
Hello @yongilkim01.

I would like to check if there are any additional error messages during this error.
Can we check is there any other error messages?

**Comment by yongilkim01** [comment]
![image](https://user-images.githubusercontent.com/101537874/206138486-058a47d0-65ba-43a9-a4b6-26dbb43d549a.png)
Sorry, I'm currently working on a desktop, not a laptop, so I'm only updating the issue now.
If you do yarn install on your current laptop, the log will appear, and the issue below seems to be related.
#746

**Comment by WoodNeck** [comment]
It looks like the node-sass and node version is mismatching in your environment.
- https://www.npmjs.com/package/node-sass#user-content-node-version-support-policy

You can try:
- Update `node-sass` version to `v8.0`+, and check whether the `build:css` script works.
- Or, downgrade your node version. Flicking env is tested on node `v16.16.0`.

**Comment by malangfox** [comment]
Since there is no further comment, we will close the issue.
