### ISSUE TITLE
I got this Type Error with @egjs/ngx-flicking

### ISSUE THREAD

**Issue by biondiBagasta** [naver/egjs-flicking#760]
@egjs/component/declaration/types.d.ts
```
(type parameter) T in type EventTriggerParams<T, K extends EventKey<T>>
Type 'T' does not satisfy the constraint 'EventMap'.ts(2344)
types.d.ts(10, 40): This type parameter might need an `extends EventMap` constraint.

```

Angular Version: 15

**Comment by malangfox** [comment]
Hello @biondiBagasta.

We would like to know more about the environment which this error occurs.
Are you getting these errors when building your Angular application? 
Also, we would like to know which version of typescript you are using.

**Comment by malangfox** [comment]
This seems to happen in our component when using typescript 4.8 or higher.
You can temporarily avoid the error by adding `"skipLibCheck": true` to tsconfig.json.
We will leave a comment when a version fixes this issue is released.
