### ISSUE TITLE
cirular option makes screen flickers

### ISSUE THREAD

**Issue by jho951** [naver/egjs-flicking#773]
## Description

i use Flicking library in **next JS** project , when i use **circular option** and it makes screen flickers, when first rendered.
when commenting out **circular option**, it is not flicking.
 but circular option is absolutely necessary. is there way to not flicking?

## Steps to check or reproduce
[https://www.galmaetgil.kr/](url)

![스크린샷 2023-01-06 오후 3 31 57](https://user-images.githubusercontent.com/109015067/210943935-ef9a107f-236d-4f3e-8af3-feafd607198e.png)
>> these image slide is used circular option
![스크린샷 2023-01-06 오후 3 31 18](https://user-images.githubusercontent.com/109015067/210944087-6d5b2986-af5a-4969-b6cc-1ad3458e924d.png)
>> these image is my code

**Comment by malangfox** [comment]
Hello @jho951.

Thank you for leaving detailed reproduction.
When I checked the website you attached, I saw that the first panel set on Flicking was replaced with another panel right after the page loaded.

Have you ever made an implementation related to this?
If not, does the first panel quickly change to the next panel only when the circular option is enabled?

**Comment by jho951** [comment]
i appreciate fot your reply. 
I haven't implemented anything special, and only when the circular option is set to true, the next picture flickers quickly during first rendering.

**Comment by jho951** [comment]
페이지를 처음 렌더링할 때  저장된 다음 인덱스의 사진이 깜빡거리는 이슈가 있습니다.  코드 상으로 위 사진의 옵션 이외의 것은 사용하지 않았습니다. 디버깅 과정 중 'circular' 옵션을 주석 처리 시 깜빡이는 이슈가 없어집니다. 이 라이브러리는 처음 적용해 보았고, 'circular' 옵션 자체에서 발생하는  것입니까? 아니면 추가적인 옵션 설정이 필요한 것인가요?

**Comment by WoodNeck** [comment]
@jho951

I've checked the issue, and it appears that there was a timing error while applying the CSS transform during the SSR rendering process.
We've raised a PR to fix this. I'll leave a comment after deploy :)

**Comment by malangfox** [comment]
@jho951

@egjs/flicking 4.10.6 with the issue fixed and packages for each framework have been released.
Try the latest version of the package you are using and file an issue if you encounter additional problems.
