### ISSUE TITLE
Pagination Plugin 사용중에 클릭시 위치 에러

### ISSUE THREAD

**Issue by jexists** [naver/egjs-flicking#774]
## Description
pagination bullet 타입 플로그인을 사용중인데
스크롤로 넘겼다가 bullet 첫번째 것을 누르면 첫번째 이미지가 나와야하는데 다른이미지가 나오네요. 
문서에서는 기본설정이 없는것같은데 문제가 뭔지 모르겠네요

## Steps to check or reproduce

```html
    <ngx-flicking [plugins]="plugins" [options]="{ circular: true, moveType: ['strict', { count: 1 }]}" #flick>
      <div flicking-panel *ngFor="let image of product.image; let i = index" class="flicking_item">
        <img [src]="image" alt="image" />
      </div>
      <div in-viewport class="flicking-pagination rect"></div>
    </ngx-flicking>
```

```typescript
import { Plugin } from "@egjs/ngx-flicking";
import { Pagination } from "@egjs/flicking-plugins";

export class ProductViewComponent implements OnInit, OnDestroy {
  @ViewChild('flick') flick: NgxFlickingComponent; 
  public plugins: Plugin[] = [new Pagination({ type: 'bullet'})];
.......
}
```

**Comment by malangfox** [comment]
안녕하세요 @jexists 님.

남겨주신 이슈를 재현하고자 동일한 옵션과 플러그인을 사용해서 *ngFor로 여러 Panel을 사용하는 [데모](https://codesandbox.io/s/flicking-bullet-pagination-github-774-3hseyv?file=/src/app/app.component.html)를 작성해보았습니다.
데모 상에서 좌/우 Panel로 드래그를 한 뒤 첫 번째 bullet을 눌렀을 때 남겨주신 현상은 재현되지 않는 것으로 보이는데요,
혹시 첨부드린 데모에서 이슈를 재현해보실 수 있다면 저희가 재현 절차를 보다 자세히 알 수 있을까요?

**Comment by jexists** [comment]
데모에서 비슷하게 작성했을경우에 현상이 재현되지 않네요..
다른 외부작용때문에 그런것같은데 아래 링크 참고부탁드립니다.
https://4mation.net/product/7418

**Comment by jexists** [comment]
moveType: ['strict', { count: 1 }] ->  moveType:'snap' 이걸로 변경할 경우에는 이슈가 안생기네요.
moveType이 strict일 경우에 생기는 것같습니다.

**Comment by malangfox** [comment]
남겨주신 페이지를 확인해보았으며, Flicking의 camera 엘리먼트가 동작하는 영역과 Pagination이 클릭으로 작동하는 영역이 중복되어 Pagination을 클릭할 때 Flicking에서도 입력이 함께 발생해서 정상적으로 동작하지 않는 현상으로 추정됩니다.
혹시 해당 현상을 보다 정확히 파악하기 위해 Flicking의 camera 엘리먼트의 영역과 겹치지 않게 Pagination 엘리먼트를 배치했을 때도 이슈가 재현되는지 확인이 가능할까요?

**Comment by jexists** [comment]
Flicking의 camera 엘리먼트의 영역과 겹치지 않게 Pagination 엘리먼트를 배치를 할려고 하는데
.flicking-viewport에 style에 overflow:hidden 들어있어서
.flicking-pagination이랑 camera영역이 겹치지 않게 배치하기가 힘든것같네요.
style로 잠시 겹치지 않게 했을 경우에도 같은 이슈가 재현되는거 같아요.

**Comment by WoodNeck** [comment]
@jexists 
이슈 확인해봤는데요, #632 이슈랑 같은 케이스가 아닐까 합니다.
페이지 확인시에 4.4.2 버젼을 사용하고 계신걸로 확인되는데요, 버젼업 해보시고 테스트해보실 수 있을까요?
해당 이슈는 `v4.5.1`에서 픽스되었습니다.

**Comment by jexists** [comment]
버전업했더니 이슈 없습니다. 감사합니다.
