### ISSUE TITLE
Unwanted scroll jump when clicked during sliding

### ISSUE THREAD

**Issue by plrs9816** [naver/egjs-flicking#776]
## Description
~~Unwanted scroll jump when clicked during sliding~~
~~슬라이드 중 클릭 시 의도치 않은 스크롤 점프 현상~~

~~Scroll jumps to unexpected position when click event occurs during sliding, especially when dragged fast.~~
~~It can lead to bad UX since this situation will likely appear on mobile clients.~~
~~드래그 후 손을 떼서 슬라이드가 넘어가는 도중 클릭 이벤트가 발생 시, 특히 드래그를 빠르게 했을 때 예상치 못한 곳으로 스크롤이 튀는 현상이 있습니다.~~
~~모바일에서 이런 유저 이벤트가 발생할 가능성이 크며 부정적인 UX를 의도할 수 있습니다.~~

See #777 for detail.

When click event occurs during sliding, animation should end with position moving smoothly to the nearest slide.
Would be nice to have some sort of 'spring' physics for slide stopping when mousedown.
슬라이드가 넘어가는 도중 클릭 이벤트가 발생 시, 손을 떼면 가장 가까운 슬라이드로 부드럽게 움직이며 애니메이션이 종료되어야 합니다.
슬라이드가 mousedown에 의해 멈출때 스프링 물리효과가 있으면 더 좋을 것 같습니다.

## Steps to check or reproduce
Go to any demo and click during sliding.
아무 데모에서 슬라이드 도중 클릭

**Comment by malangfox** [comment]
Hello @plrs9816.

We have checked the original behavior when a click occurs while moving a panel.
It seems that the behavior you suggested is more appropriate than the original behavior.

We will review the pull request you have left.
Thank you for your contribution!
