### ISSUE TITLE
Can't resume for stopped position with that timer from autoplay plugin

### ISSUE THREAD

**Issue by ansrlm** [naver/egjs-flicking#778]
## Description
Thank you in the beginning for using flicking autoplay plugin, there is some issue.
After first initialization of autoplay plugin, I just want to stop & restart with some interval.
But when I stop, autoplay plugin has to be located initial timer (0).
Is there a way to treat the case like below?

## Steps to check or reproduce
AS-IS
```
Duration(5 sec)

-Plugin.Start
-> Panel at 0 index

-After 7sec
-> Panel at 1 index

-Plugin.Stop
-> Panel at 1 index

-Plugin.Start
-> Panel at 1 index

-After 4sec
-> Panel at 1 index
```

Want TO-BE
```
Duration(5 sec)

-Plugin.Start
-> Panel at 0 index

-After 7sec
-> Panel at 1 index

-Plugin.Stop
-> Panel at 1 index

-Plugin.Start
-> Panel at 1 index

-After 4sec
-> Panel at 2 index
```

**Comment by malangfox** [comment]
Hello @ansrlm.

Our AutoPlay plugin does not directly support the feature you left.
However, I made a [demo](https://codepen.io/malangfox/pen/oNyxzvB) that implemented the Want TO-BE you left.
You could use an implementation like the above.

We will further discuss whether this case of use is supported as an option for AutoPlay later.
Thank you for leaving your suggestions.

**Comment by ansrlm** [comment]
WFM!

Thanks for help, I'll adjust as what you made.
