### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'slot.key')

### ISSUE THREAD

**Issue by taidaid** [naver/egjs-flicking#781]
## Description

I don't have many details for you sadly. I've seen this error 6 times in my Sentry logs, 3 times in the past month. All I really have for you is the info below. I hope it helps, please let me know if there's anything more I can provide.

## Steps to check or reproduce

Running:
```json
    "@egjs/flicking-plugins": "4.6.0",
    "@egjs/vue-flicking": "4.10.4",
```

![image](https://user-images.githubusercontent.com/39394303/216002161-9961d4ea-4032-4920-b4f6-bcff37f83d31.png)

![image](https://user-images.githubusercontent.com/39394303/216002537-d79e0f87-8d2e-4ad3-9225-f73cbdd7059a.png)

**Comment by WoodNeck** [comment]
Hello @taidaid!
It's an easy fix by filtering the slots, but I can't tell if the problem is in `getRenderingPanels` or `_getSlots`.
So, I'm guessing that fix would stop the error, but the rendered element would likely not be the desired result.
I would like to know if you could give me some more information to reproduce the issue, such as the rendering function you're using.

**Comment by taidaid** [comment]
Hello @WoodNeck , thanks for the quick response.

I'm not sure where I can get the exact info you need. Hopefully this helps

```vue
      <VueFlicking
        ref="vueFlickingEl"
        :options="{
          moveType: 'snap',
          horizontal: true,
          align: 'prev',
          bound: true,
          circular: false,
          preventClickOnDrag: true,
          defaultIndex: 0,
          disableOnInit: !isMobile && !isTablet,
          renderOnlyVisible: true,
        }"
        :viewport-tag="'div'"
        :camera-tag="'div'"
        class="product-card-container__image-slider"
        @ready="initializeVueFlicking"
        @changed="updatePositions"
      >
        <ProductCard
          v-for="product in products"
          v-bind="product"
          :key="product.id"
          :active-currency="activeCurrency"
          :locale="locale"
          v-on="$listeners"
        />
      </VueFlicking>
```

**Comment by WoodNeck** [comment]
I tried to reproduce this issue but I couldn't.
I think `getRenderingPanels` is giving the wrong values, which might be the cause of this issue and #783, but I can work on it once after reproducing the issue.
If you find a way to reproduce the issue, could you please let me know?

**Comment by taidaid** [comment]
Ok @WoodNeck , thanks for the quick investigation. I have only 2 reports of this issue after using your library for over a year, so I would classify it as a very low-occurrence bug. Thanks for all the hard work! :grin: If I learn more about it, I'll be sure to update this.

**Comment by WoodNeck** [comment]
@taidaid Thank you! We'd really appreciate it if you could :)

**Comment by taidaid** [comment]
Hello again, I'm guessing this is related to the same bug, so here's my Sentry info on a new occurrence:
```
TypeError Array.map(<anonymous>) 
Cannot read properties of undefined (reading 'toggle')
```

![image](https://user-images.githubusercontent.com/39394303/223333044-3a1b15d9-5e3e-4c91-9879-d6a7e11383c1.png)


![image](https://user-images.githubusercontent.com/39394303/223332806-61b18b82-f6db-47de-a585-3c61889473f2.png)
