### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.markForShow')

### ISSUE THREAD

**Issue by taidaid** [naver/egjs-flicking#783]
## Description

Sadly I don't have a lot of info for you again. 

```json
    "nuxt": "2.15.8",
    "@egjs/flicking-plugins": "4.6.0",
    "@egjs/vue-flicking": "4.10.4",
```

## Steps to check or reproduce

![image](https://user-images.githubusercontent.com/39394303/216891580-be21bf2c-4d0b-49fa-aea7-15e9fedd633e.png)
---
![image](https://user-images.githubusercontent.com/39394303/216891603-efaaf51c-1c5a-4ec7-aaec-4ef920d10f1d.png)

**Comment by WoodNeck** [comment]
This seems to be the same bug as issue #781, I'll manage it together in that issue.
