### ISSUE TITLE
Rendering images outside of viewport slows down a little bit on first try

### ISSUE THREAD

**Issue by SquidAnan** [naver/egjs-flicking#784]
## Description
I built a responsive photo slideshow using Nuxt + Flicking. Here's the link: https://squidanan.github.io/
When I slide it, it would get stuck for like 0.5 seconds on every photo that hasn't been displayed in the viewport. But after they have appeared once in the viewport, everything is smooth.
I thought it was because client side hasn't downloaded the images, but by checking the Network in DevTools I believe the images are downloaded. And the DOM of the panels seem to be rendered as well. I don't understand why they still get stuck on first try.
I use `renderOnlyVisible: false`, and didn't use lazy loading. I'm not even sure this is Flicking's problem.
Is there anything I didn't know that would cause this behavior? I would like the photos to be "completely rendered" before I slide them.

The Vue code looks like this:
```HTML
<Flicking class="h-full w-full overflow-hidden" ref="flicking" @changed="update_photo_number"
    :options="{panelsPerView: 1, renderOnlyVisible: false}">
    <div class="absolute h-full w-full flex items-center justify-center">
        <nuxt-img />
    </div>
    <div class="absolute left-[100%] h-full w-full flex items-center justify-center">
        <nuxt-img />
    </div>
    <div class="absolute left-[200%] h-full w-full flex items-center justify-center">
        <nuxt-img />
    </div>
    <div class="absolute left-[300%] h-full w-full flex items-center justify-center">
        <nuxt-img />
    </div>
    <div class="absolute left-[400%] h-full w-full flex items-center justify-center">
        <nuxt-img />
    </div>
</Flicking>
```

## Steps to check or reproduce
https://squidanan.github.io/
You could slide the photos by dragging or clicking the buttons.

Thanks!

**Comment by malangfox** [comment]
Hello @SquidAnan.

First, we want to check the environment where this issue occurs.
We would like to know which mode you're using nuxt, it may be an issue in our component that happens in server-side rendering.
We also want to check the behavior when using the normal img tag instead of nuxt-img.

It would be helpful if we can check the full implementation of the demo you provided!

**Comment by SquidAnan** [comment]
Thanks for helping me!
Full implementation: https://github.com/SquidAnan/nuxt-photo-slideshow
I also tried using normal <img> and got the same result.

**Comment by SquidAnan** [comment]
I found another problem: on Firefox if I don't add draggable="false" on each image, Flicking would not work. It would act like it's "too heavy" to drag.
And surprisingly, after adding draggable="false", Firefox does not have the problem I mentioned in this issue, but Edge and Chrome still does.
Browser version: Edge 110.0.1587.50 / Firefox 110.0 / Chrome 110.0.5481.104

**Comment by SquidAnan** [comment]
I reduced the image size and satisfied with the result now.
If you still want to see the issue I put it in: https://squidanan.github.io/deprecated

**Comment by malangfox** [comment]
@SquidAnan
I have found the cause of the performance issue you are experiencing and would like to share it with you.

The default style for vue-flicking that you can import and use, `@egjs/vue-flicking/dist/flicking.css`, applies `will-change: transform;` to the flicking-camera element.
This optimizes the element's transform to avoid the issue you had.
I think you can prevent this issue in the future by applying the above style to the flicking-camera element.

**Comment by SquidAnan** [comment]
Unfortunately, I don't really see the optimization after applying `will-change: transform` to flicking-camera. It still gets stuck for a moment. Did you try it out and really see the optimization?
And also, `will-change` is an attribute supported by browsers, right? I suppose that does not require importing `@egjs/vue-flicking/dist/flicking.css` ?
Thanks for your help!

**Comment by malangfox** [comment]
I reverted to the commit before reducing the image sizes in your repo and applied the style to the flicking-camera element to see the performance improvement.
This was also checked by adding the style directly in the dev tool at https://squidanan.github.io/deprecated/.
Also, you are not required to import flicking.css.

**Comment by SquidAnan** [comment]
Okay I see. Thanks for your help!

**Comment by oioioiio** [comment]
Hey @malangfox & @SquidAnan 
I had the same issue and used this to solve the issue:

`
.flicking-camera img,
.flickking-camera a {
  user-drag: none;
  -webkit-user-drag: none;
  user-select: none;
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
}
`
