### ISSUE TITLE
순환 플리킹에서 getVisiblePanels 문의 드립니다.

### ISSUE THREAD

**Issue by memori80** [naver/egjs-flicking#787]
## Description

eg.flicking: 3.8.3
react: 16.13.1

문의1.
순환플리킹으로 생성하고 화면을 로딩(defaultIndex: 0) 하면
왼쪽 패널(화면 바깥으로 나가서 오른쪽만 살짝 보이는 패널)은 getVisiblePanels()에 안나오는데 이게 맞는건가요? 
패널을 한번 이동시킨 후에는 getVisiblePanels()에 3개가 나오게 되고요.

문의2.
플리킹 판에 있는 이미지를 lazyloading하려고 하는데요.
처음에는 판을 3개만 만들고, 동적으로 패널을 붙이는 방식이 나을까요?
좋은 방식이 있다면 가이드 부탁 드립니다.
혹시 4.x에는 이미지 lazyloading 기능같은것이 있는지도 궁금합니다.

**Comment by malangfox** [comment]
안녕하세요 @memori80님.

첫 번째로 남겨주신 문의인 `getVisiblePanels` 에서 화면 내에 있는 패널을 인식하지 못하는 현상은 구현 상 의도되지 않은 현상으로 보입니다.
초기 위치 계산이 잘못되었을 가능성이 있으므로 유사한 환경을 재현해주실 수 있다면 데모를 확인해보자 합니다.

또한 패널 내부의 이미지를 lazy loading 하는 기능은 4버전에서도 별도로 지원하고 있지 않습니다.
3버전과 4버전에서 공통적으로 사용할 수 있는 lazy loading 방법으로는 문의를 남겨주신 내용처럼 패널을 이후에 추가하시거나, 
`visibleChange` 이벤트가 발생했을 때 패널 내부의 이미지가 lazy loading 되도록 구현해보시면 좋을 것 같습니다.

**Comment by malangfox** [comment]
별도의 추가적인 코멘트가 없어 이슈를 닫아두도록 하겠습니다.
