### ISSUE TITLE
안녕하세요 

### ISSUE THREAD

**Issue by miseon920** [naver/egjs-flicking#792]
## Steps to check or reproduce

기본 html에서 써볼려고 해서  

    <script src="https://unpkg.com/@egjs/flicking/dist/flicking.pkgd.min.js" crossorigin="anonymous"></script>
    <script src="https://naver.github.io/egjs-flicking-plugins/release/latest/dist/plugins.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/@egjs/flicking/dist/flicking.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://naver.github.io/egjs-flicking-plugins/release/latest/dist/flicking-plugins.css">

이런식으로 쓰고  데모사이트에 있는 대로 만들고 

const flicking = new Flicking(".slide", {
                panelsPerView: 2,
                align: "prev",
                circular: true,
                bound: true,
                renderOnlyVisible: true
 })
이렇게도 쓰고

flicking.addPlugins(new AutoPlay({ duration: 2000, direction: "NEXT", stopOnHover: false }));

자동재생도 하고 싶어서 이렇게도 썻는대
왜 오류가 뜰까요?ㅠㅠ

프레임워크가 아닌 html 에서는 사용할 수 없는것일까요?

![image](https://user-images.githubusercontent.com/34021077/227893137-d59bbb0d-75a5-45ee-ad9b-e321316f81ad.png)

이렇게 자꾸 뜨고 되지가 않아요
ㅠㅠ 또 저는 .slide 저 클래스로 여러개 만들고 싶은대 한개만 작동하는거 같기도합니다.
플러그인을 달기전에는 오류가 안뜨는대 달고 나면 오류가 뜨고요..
여러개가 아니라 한개만 작동합니다 슬라이더가 ㅠㅠ

**Comment by malangfox** [comment]
안녕하세요 @miseon920님.

아래 구현 예시와 같이 `Flicking.Plugins.AutoPlay` 를 이용해보시면 정상적으로 플러그인을 이용하실 수 있을 것 같습니다.

```ts
const flicking = new Flicking("#flick");
flicking.addPlugins(new Flicking.Plugins.AutoPlay({ duration: 1000 }));
```

바닐라 JS 환경에서 AutoPlay 플러그인을 사용하는 [데모](https://codepen.io/malangfox/pen/OJwvaqx) 또한 준비해보았는데요, 원하시는 구현에 참고가 될 수 있다면 좋겠습니다.

또한 남겨주신 이슈 내용상 .slide 라는 클래스명을 사용하는 Flicking을 다수 생성하시기를 희망하는 것으로 보입니다.
이 부분 또한 위 데모에서 서로 다른 id로 구분해서 다수의 Flicking에 AutoPlay 플러그인을 사용하는 부분을 확인해보시면 될 것 같습니다.

**Comment by miseon920** [comment]
답변너무 감사합니다! :)
