### ISSUE TITLE
Little bug on the Quick Start doc for Vue@3

### ISSUE THREAD

**Issue by aitsimon** [naver/egjs-flicking#793]
## Description

On the Docs for Vue@3 in order to import the css style it has been written that the path is this one: 
`@import url("node_modules/@egjs/vue-flicking/dist/flicking.css");`
When the correct path in this case should be: 
`@import url("node_modules/@egjs/vue3-flicking/dist/flicking.css");`
This diference is the **3** in the path. This little change can be very useful for many people. Thanks in advance for considering this issue.
Source:
https://naver.github.io/egjs-flicking/docs/quick-start
## Steps to check or reproduce
![image](https://user-images.githubusercontent.com/98778142/228175610-43a0c161-1bd1-45c0-954c-38d9555a9a86.png)
![image](https://user-images.githubusercontent.com/98778142/228176063-403d001b-2105-4f67-ad2b-75456975ac93.png)

**Comment by malangfox** [comment]
Hello @aitsimon.

We appreciate you for finding this misspelled path in our documentation!
We'll make sure to fix this as soon as possible.

Thank you for your contribution!

**Comment by aitsimon** [comment]
Thanks to you all for this active maintenance of a great library.
