### ISSUE TITLE
[@egjs/react-flicking] setStatus 를 이용할 때, index 값이 0으로 업데이트가 안됩니다. 

### ISSUE THREAD

**Issue by always-awake** [naver/egjs-flicking#795]
## Description
환경
```
"@egjs/react-flicking": "4.10.6",
"react": "^17.0.1",
```

아래 코드를 이용해, Status의 `index` 값을 업데이트 해주고자 합니다. 
index 값은 `number` 타입이라, number 타입으로 설정해주고 있었는데, `0` 인 경우에만 설정한 index 값의 패널로 이동하지 않았습니다.
```
    if (flicking?.initialized) {
      flicking?.setStatus({
        ...flicking?.getStatus(),
        index: 0,
      })
    }
```

임의로 `${0}`와 같이 string 설정해주었을 때, 잘 동작했습니다. 확인부탁드립니다

**Comment by malangfox** [comment]
안녕하세요 @always-awake 님.

이슈를 남겨주신 현상은 저희 컴포넌트에서 발생하는 버그로 확인되었습니다.
추후 해당 현상이 수정된 패치의 배포를 마친 뒤 코멘트를 드리도록 하겠습니다.

감사합니다.

**Comment by malangfox** [comment]
이슈를 남겨주신 현상이 수정된 @egjs/flicking 4.10.7 및 @egjs/react-flicking 4.10.9 버전이 배포되었습니다.
최신 버전의 패키지를 이용하여보시고 문제를 겪게 되시는 경우 이슈를 남겨주세요.
