### ISSUE TITLE
Flicking option 값 문의

### ISSUE THREAD

**Issue by Siihyun** [naver/egjs-flicking#800]
## Description

안녕하세요. 우선, 좋은 라이브러리 만들어주셔서 감사드립니다.
react-flicking을 사용중인데요.

아래 예시 이미지처럼 뷰포트에 총 3개의 카드를 노출하고 싶습니다. (현재 active된 카드 + 양 옆에 prev, next item 일부)
![image](https://user-images.githubusercontent.com/44644821/232835786-7c359b74-4c56-41df-ab04-be14afc0cf6c.png)

1) 어떤 옵션을 통해 설정할 수 있을까요?
2) 혹시 양 옆에 카드(prev, next Item)가 몇 %(혹은 px) 보일지도 설정할 수 있을까요?

시도해본 방법으로는 panelsPerView option을 써봤으나 원하는 결과를 얻지 못했습니다.

감사합니다.

**Comment by malangfox** [comment]
안녕하세요 @Siihyun 님.

`align: "center"` 로 설정된 Flicking에서 좌우 Panel이 차지하는 공간은 옵션 대신 Panel의 스타일을 통해 설정하실 수 있습니다.

이슈에 남겨주신 내용처럼 좌우 카드가 viewport 너비의 일정 %만 표시되게끔 하는 방법으로 각 Panel의 width를 일정 %로 설정한 [데모](https://codepen.io/malangfox/pen/ExdgvJZ)를 만들어보았는데요, Panel의 width는 50%로 설정하였고 margin은 5%로 설정되어 있어 좌우 Panel의 너비 중 15%만 미리 노출되는 모습을 확인하실 수 있습니다.

위 구현을 참고하여보시고 만약 더 궁금하신 부분이 있다면 코멘트를 남겨주세요.

**Comment by Siihyun** [comment]
@malangfox 님, 빠른 답변 감사드립니다!! 🙇‍♂️
Panel에 직접 스타일을 줘서 제어할 수 있군요!

하나만 더 질문드리고 싶습니다.

제가 밤-아침 사이 이것저것 해보다가 panelsPerView에 소숫점 옵션(ex: 1.1)을 주고, Panel들에 margin-right를 줘서 비슷한 효과를 구현했는데요. 이 방식이 내부적으로는 동일하게 동작 하는걸까요?

소스코드 첨부합니다.

![image](https://user-images.githubusercontent.com/44644821/232968721-d7ebafd5-f958-4576-bd33-9c1654b19428.png)

**Comment by malangfox** [comment]
Panel의 크기를 `panelsPerView` 값에 맞게끔 조정하는 내부 로직상 `panelsPerView` 를 소숫점 값으로 설정해도 동일한 구현이 가능하지만 이는 해당 옵션의 의도된 동작은 아니며 `panelsPerView` 에는 정수 값을 사용하는 것을 권장드립니다.

이슈에 남겨주신 구현은 Panel의 스타일을 설정하는 방법이 가장 적합해보입니다.

**Comment by Siihyun** [comment]
넵, 말씀하신 방향으로 해결하였습니다! 
답변 정말 감사드립니다! 이슈는 클로즈 하도록 하겠습니다 🙇‍♂️
