### ISSUE TITLE
ngx-flicking is not compatible with Angular v16.

### ISSUE THREAD

**Issue by wen9218** [naver/egjs-flicking#807]
## Description
Hi, thanks for the great lib @egjs/ngx-flicking.
I am using ngx-flicking v4.10.7 (the latest version) and I upgreade my angular project to v16.
But NgxFlickingModule is not compiled properly.
![image](https://github.com/naver/egjs-flicking/assets/57497730/926289f6-8a4d-4c21-be7c-f4480b1f4e84)

Even though compile is successful by force, NgxFlickingModule has issue with platformBrowserDynamic
![image](https://github.com/naver/egjs-flicking/assets/57497730/2303a6d6-59c5-475b-ae89-1fa9178904b4)

I think 2 issues are related to each other and I would be thankful if you check and resolve the issue.

## Steps to check or reproduce
Try to use @egjs/ngx-flicking under angular v16

**Comment by born2net** [comment]
Hi and thank you got a great project.
we also can't use the project with Angular 16, any ETA? thank you!
Sean

**Comment by malangfox** [comment]
Hello @wen9218 @born2net.

We ahve released version 4.10.8-beta.0 of @egjs/ngx-flicking to make ngx-flicking compatible with the latest version of Angular.
Please try the above beta version and let us know how it works in your environment.

**Comment by wen9218** [comment]
Hi, @malangfox , I check v4.10.8-bata.0. It resolved compile and rendering issue. So, it is compatible with ng v16. :)
But, ngx-flicking directives such as flicking-camera, flicking-panel are not working in v4.10.8-bata.0, so styles are broken.
Please check directives in updated version.
Thanks

**Comment by malangfox** [comment]
@wen9218

I've released a version of @egjs/ngx-flicking 4.10.10-beta.0 that fixes broken style.
Can you try the above version and check if it resolves the issue?

**Comment by nk6** [comment]
Version 4.10.10-beta.0 fixes the broken styles in our project. Thanks!
