### ISSUE TITLE
ngx-flicking v4.5.1 is not working with Angular v12

### ISSUE THREAD

**Issue by abhinavakhil** [naver/egjs-flicking#811]
## Description

I was using ngx-flicking v4.5.1 with angular v12 in my project, it was working fine until ngx-flicking released a new version a few days back.

Currently, it is throwing this error whenever I run my app.
![image](https://github.com/naver/egjs-flicking/assets/31372157/c5b43b8d-506c-4404-9296-796fcb6e65a6)

Please suggest a solution to fix this issue without upgrading the angular version. Thanks

**Comment by daybrush** [comment]
@abhinavakhil 

Try use `@egjs/ngx-flicking@4.10.11-beta.0`

**Comment by malangfox** [comment]
Hello @abhinavakhil.

Since Angular 12 is out of LTS support, our latest packages do not support Angular v12.
You may be able to use Flicking up to version 4.10.6 in Angular v12. 
However, we recommend upgrading your Angular version to use the latest packages.

**Comment by abhinavakhil** [comment]
Okay, Thanks
