### ISSUE TITLE
"typescript": "5.1.3" + "@egjs/vue3-flicking": "4.10.8", TypeError: Cannot read properties of null (reading 'refs')

### ISSUE THREAD

**Issue by UmKilYong** [naver/egjs-flicking#813]
It does not occur in typescript 5.0.2, but this issue has occurred since upgrading to typescript 5.1.3.

**Comment by daybrush** [comment]
@UmKilYong 

May I know the error trace log?

**Comment by UmKilYong** [comment]
@daybrush 
Please refer to the attached file
![스크린샷 2023-07-05 오후 2 17 52](https://github.com/naver/egjs-flicking/assets/36656077/ae31f79b-01f0-4afb-af3a-dd825e6645e9)
<img width="539" alt="스크린샷 2023-07-05 오후 4 23 16" src="https://github.com/naver/egjs-flicking/assets/36656077/67113ea8-a408-46af-b153-dbcf6431449a">

<img width="546" alt="스크린샷 2023-07-05 오후 4 23 36" src="https://github.com/naver/egjs-flicking/assets/36656077/52bc6b1b-f2af-431a-b410-63dd7c268115">

**Comment by daybrush** [comment]
@UmKilYong 

I think there are more than 2 versions of vue.

try reinstalling

If not, try using `yarn resolution` or `npm overrides`.

Unifying the versions seems to work.

**Comment by malangfox** [comment]
Since there is no further comment, we will close the issue.
