### ISSUE TITLE
ngx-flicking 4.10.10 is broken directive styles under Angular V16

### ISSUE THREAD

**Issue by wen9218** [naver/egjs-flicking#815]
## Description
Hi, ngx-flicking 4.10.10 is not working properly under ng v16. directive styles like flicking-camera, flicking-panels are broken.
But ngx-flicking 4.10.10-beta.0 works well.
Overall
- ngx-flicking 4.10.11-beta0 - styles are **broken**
- ngx-flicking 4.10.10 - styles are **broken**
- ngx-flicking 4.10.10-beta0 - styles work well.

Can you please check and fix it in the next version?

**Comment by born2net** [comment]
Hi... yes we are having the same issues, please let us know if you need more input,
thank you.

**Comment by daybrush** [comment]
@wen9218 @born2net 

I'll check. It seems that the problem occurred when the angular version of the component was upgraded.

**Comment by daybrush** [comment]
@born2net @wen9218 

Can you tell me how Flicking was imported and how it was used in the template?

**Comment by wen9218** [comment]
@daybrush, I imported ngx-flicking module and used like this. Thanks for advancing.

![image](https://github.com/naver/egjs-flicking/assets/57497730/83d5e56a-57f2-4e16-a1ed-f2fc36550f19)
![image](https://github.com/naver/egjs-flicking/assets/57497730/2c3b495e-0f0c-4301-a77b-7596875d4c97)

**Comment by malangfox** [comment]
Hello @wen9218.

We have released @egjs/ngx-flicking version 4.10.11.
Can you check if the issue is reproduced in our latest version?

**Comment by wen9218** [comment]
Hi, @daybrush, @malangfox, 
I checked v4.10.11. It works fine. Thanks a lot!

**Comment by born2net** [comment]
thank you!!!
