### ISSUE TITLE
Dependency not found in yarn

### ISSUE THREAD

**Issue by omarmfs98** [naver/egjs-flicking#818]
## Description

Please I need help, this dependency is not found and it does not allow me to run my project, was it deleted in the dependency manager?

This version was not found https://[registry.yarnpkg.com/@egjs/component/-/component-3.0.2.tgz](https://registry.yarnpkg.com/@egjs/component/-/component-3.0.2.tgz)

![image](https://github.com/naver/egjs-flicking/assets/24736893/5ab1947d-3239-47cb-97c1-52f5eb53b450)

![image](https://github.com/naver/egjs-flicking/assets/24736893/2e0f7827-cfe0-4da2-aa17-61c86eefca95)

**Comment by omarmfs98** [comment]
@malangfox Hi!! please review this! 🙏

**Comment by malangfox** [comment]
Hello @omarmfs98.

Can you run the same command and include the `--verbose` flag?
It will print more information as to why the command failed.

**Comment by omarmfs98** [comment]
> 

It's normal now, but it did have errors yesterday, thank you anyway
