### ISSUE TITLE
Nextjs 13.4 app dir and react class components only works in client components

### ISSUE THREAD

**Issue by beihai-shinan** [naver/egjs-flicking#825]
## Description
This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component

## Steps to check or reproduce
in nextjs 13.4.6

**Comment by malangfox** [comment]
Hello @beihai-shinan.

We have added `'use client'` decorator to our react component.
Can you try using @egjs/flicking 4.11.1-beta.0 version?

**Comment by malangfox** [comment]
Since there is no further comment, we will close the issue.
If there are no issues with this change, it will be deployed via patch.

**Comment by Kovania** [comment]
I inform you that it works well on NextJs 14 with 4.11.1-beta.0 version.
