### ISSUE TITLE
Getting build error for ngx flicking argument issue from its node modules files

### ISSUE THREAD

**Issue by devHimanshu12** [naver/egjs-flicking#828]
## Description
My angualar cli  version is 14.2.12
and rest dependencies of angualar you can seen in screenshots
![Screenshot from 2023-08-25 12-58-16](https://github.com/naver/egjs-flicking/assets/89963043/ce23a7f3-89e0-4922-9343-aa4f1a581426)
![Screenshot from 2023-08-25 12-58-28](https://github.com/naver/egjs-flicking/assets/89963043/b5c7a535-4e89-4c67-acb0-36a36e78ab69)

## Steps to check or reproduce
i am using ngx flicking library 
version is 4.11.0
 
while build my application i am getting build  error related to ngx flicking from node modules argument issue which you can see in screen shot
![Screenshot from 2023-08-25 13-06-05](https://github.com/naver/egjs-flicking/assets/89963043/c730203c-75ec-4da9-a0f2-6edce2fe360e)

If any could help
I don't want to upgrade my angular verion to more than 14.

please provide solution if anyone knows.

**Comment by malangfox** [comment]
Hello @devHimanshu12.

It seems that components built from Angular 15 have compatibility issues with Angular 14.
You can add `"skipLibCheck": true,` to `compilerOptions` in tsconfig.json to avoid this error temporarily.

We'll let you know if our package provides an additional solution to this problem.

**Comment by devHimanshu12** [comment]
Thankyou so much @malangfox , i already did skipLibCheck true, and it solved my issue, but if you find better solution, let me know.

**Comment by malangfox** [comment]
Angular 14 version has been removed from Angular's LTS Support.
It may be unable to fix this issue in our package, which will be built with Angular 15 and higher.
If you want to use it in the Angular 14 version, it would be appropriate to use the option commented previously.
