### ISSUE TITLE
Provide an option for the container’s z-index

### ISSUE THREAD

**Issue by incleaf** [naver/egjs-flicking#83]
## Description
If there is an overlay layout using its z-index value as 100, we should reorganize the z-index values in order to use `egjs-flicking` since its container’s z-index value is 2000, which is pretty high.
It’d be good for various of use-cases if we can use an option such as `containerZIndex`.

**Comment by netil** [comment]
Hi @incleaf, thanks for the suggestion.
We took a value of `2000` for various reason, but I think giving an option is necessary.
