### ISSUE TITLE
Direction not working correctly for RTL

### ISSUE THREAD

**Issue by huynl-96** [naver/egjs-flicking#835]
## Description

I'm using `vue-flicking` for my work. The `horizontal` property is only working for normal LTR flow.
For RTL, the animation is not correct and not showing the next panels

## Steps to check or reproduce

https://github.com/naver/egjs-flicking/assets/15758406/42232bb0-8713-426f-a99c-990e4be64ba2

**Comment by malangfox** [comment]
This issue is resolved in version 4.11.1 of @egjs/flicking.
Try the latest version of the package and leave a comment if you encounter additional issues.
