### ISSUE TITLE
Flicking pagination not appearing (Angular)

### ISSUE THREAD

**Issue by kalvintamas** [naver/egjs-flicking#839]
I tried to use the bullet-styled paginator with Flicking in Angular but it didn't show up. I checked in the devtools window of Chrome, and the `<div>` was actually there (which I placed according to the tutorials [here](https://naver.github.io/egjs-flicking/Plugins#pagination)), but its height was 0 (width was 100% according to display: block). Also, it contained the bullets in `<span>` elements but their size was also 0. I checked the styles in devtools and they have not contained the styles from the example (which I also checked in devtools).

I started with installing @egjs/ngx-flicking and @egjs/flicking-plugins. Then I added it to the root module and imported it into the component I wanted to use. The images are displayed as expected and I can move them by swiping on them, but I have the above problem. After I noticed they didn't have the styles they should have, I tried to import them manually in the component's SCSS. After that, the styles were there, but I still couldn't see the paginator. EDIT: Now I found a guide on Github, that instructs to bundle `flicking.css` that I also tried but it didn't change anything either.

Any idea? Thanks in advance.

Some of my code:
```html
  <ngx-flicking #flicking class="d-lg-none"
    [options]="{ circular: true, panelsPerView: 1, useFractionalSize: true }"
    [plugins]="plugins"
    (needPanel)="onNeedPanel($event)"
    (moveEnd)="onMoveEnd($event)">
    <div flicking-panel *ngFor="let path of imageSources" class="panel flicker-container">
      <img [src]="path" [alt]="path" class="flicker-image">
    </div>
    <div in-viewport class="flicking-pagination"></div>
  </ngx-flicking>
```

```typescript
  plugins: Plugin[] = [
    new AutoPlay({ duration: 2000, direction: "NEXT", stopOnHover: false }),
    new Pagination({ type: "bullet" })
  ];
```

```scss
ngx-flicking {
  border-radius: 20px;
}

div[flicking-panel] {
  height: auto;
  width: auto;
}

.flicker-image {
  width: 100%;
  aspect-ratio: 16/9;
  object-fit: cover;
}
```

**Comment by kalvintamas** [comment]
After a little bit of trying I found that **I need to `@import '@egjs/flicking-plugins/css/pagination.css'` in `styles.scss`** as well as `@import '@egjs/flicking/dist/flicking.css';` and this way it works! 😃

Now that this is solved, could you help me make rounded corners on the whole container without including the bullets? I could make rounded corners on the whole container so that the images can be rounded but then the bullets wouldn't be visible. Then I made not the container but the images rounded-cornered and added margins between them. That way the bullets are visible but the images are not rounded on the edges when I swipe them (as you can see in the video). I would like to make some kind of mix of the two videos.

https://github.com/naver/egjs-flicking/assets/61846148/75425801-0227-4c54-9444-bf0e53918941


https://github.com/naver/egjs-flicking/assets/61846148/b79fc0ec-4f2c-40f9-acab-72ec9a30422c

**Comment by malangfox** [comment]
Hello @kalvintamas.

It looks like your pagination is outside of the flicking-viewport and not showing up.
Can you try to place the pagination inside the flicking-viewport?
You may follow this [demo](https://codesandbox.io/p/devbox/flicking-angular-pagination-839-4xmwmp?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A11%2C41) that is similar to your implementation.

**Comment by kalvintamas** [comment]
I could place the bullets inside the `.flicking-viewport`, but maybe I wasn't clear, I need them out of the viewport because of the design of the page. And I need the viewport to be rounded-cornered as well so when I swipe the images I won't see any corners either, also because of the design of the page.

But in the meantime, I managed to achieve what I wanted to: 😊

https://github.com/naver/egjs-flicking/assets/61846148/846357f5-cf4d-4389-8739-3693a999a237

Anyway, the lesson that could be useful to others:
- you have to **import the plugins' CSS** as well if you want to use the plugins (maybe you could put this into the guides),
- you have to use `afterContentInit()` (or a similar lifecycle method) to pass the Pagination plugin if you want to make pagination outside of the `.flicking-viewport` (ngx-flicking tag) as you can see in my code. Hope this helps someone!

Thanks for the help!

### My final code:
Component typescript:
```typescript
@Input() imageSources: string[] = [];
flickingPlugins: Plugin[] = [];

constructor(private element: ElementRef) { }

ngAfterContentInit(): void {
  const flickingParent: HTMLElement = this.element.nativeElement.querySelector('#flicking-parent');
  this.flickingPlugins = [
    new AutoPlay({ duration: 5000 }),
    new Pagination({ type: "bullet", parentEl: flickingParent })
  ];
}
```

HTML:
```html
<div id="flicking-parent" class="d-lg-none">
  <ngx-flicking
      [options]="{ circular: true, panelsPerView: 1, duration: 500, moveType: 'strict' }"
      [plugins]="flickingPlugins">
    <div flicking-panel *ngFor="let path of imageSources" class="panel">
      <img [src]="path" [alt]="path" class="flicker-image">
    </div>
  </ngx-flicking>
  <div class="flicking-pagination"></div>
</div>
```

SCSS:
```scss
ngx-flicking {
  border-radius: 10px;
}
div[flicking-panel] {
  margin: 0 0.25rem;
}

.flicker-image {
  width: 100%;
  aspect-ratio: 16/9;
  object-fit: cover;
  border-radius: 10px;
}

.flicking-pagination {
  position: initial;
  margin-top: 0.5rem;
  text-align: left;
}
```
