### ISSUE TITLE
Hot to set resposive `panelsPerView` on different screen sizes?

### ISSUE THREAD

**Issue by stefanobartoletti** [naver/egjs-flicking#852]
First of all thanks for this slider, it is very simple and easy to setup and works wonderfully.

I'm willing to set a different value for  `panelsPerView` based on screen size, so that I only have a single panel on mobile but 3 or more on desktop views.

In the docs I can see that there are no separate options for this, does the API have a way to easily accomplish this?

I see that in the docs site homepage the "framework ready" carousel is doing this. Is it done via some particular setting?

Thanks

**Comment by malangfox** [comment]
Hello @stefanobartoletti.

I think you can check to update `flicking.panelsPerView` when the width of the window changes, or check the window's initial width.
I've made a [demo](https://codepen.io/malangfox/pen/ZEoWgoq) that  `flicking.panelsPerView` changes by window size.

Can you check if is this the implementation you wanted?

**Comment by stefanobartoletti** [comment]
Thanks for your reply @malangfox.

This seems to be a great solution. I will try this and see if it is good for my case, meanwhile I tried to set a maximum width on the "panel" and it achieved more or less the same thing, without having to resort to javascript.

But I will check this solution too as soon as I can, maybe it will come in handy on other cases.
