### ISSUE TITLE
Compile Error "Generic type 'ExtendedVue' requires 5 type argument(s)."

### ISSUE THREAD

**Issue by herrjonas** [naver/egjs-flicking#855]
## Description
When building with "vue": "2.6.12" and "webpack": "4.46.0" I get the error `Generic type 'ExtendedVue' requires 5 type argument(s).` in  `/@egjs/vue-flicking/declaration/Flicking.d.ts(4,25)` and `@egjs/vue-flicking/declaration/index.d.ts(11,15)`

## Steps to check or reproduce
"@egjs/vue-flicking": "^4.11.2"
"vue": "2.6.12"
"webpack": "4.46.0"

**Comment by malangfox** [comment]
Hello @herrjonas.

We tried to reproduce this issue but were unable to reproduce it in our environment.
Can we check a repository or demo where this issue is occuring?

**Comment by herrjonas** [comment]
hi @malangfox, thanks for looking into this.
As this is occurring in a larger software project with many dependencies it's not easy to provide a test environment for that particular issue. However, as I wrote earlier, we were able to resolve the issue by using another webpack version. So I'm good for now.

Thanks again!
