### ISSUE TITLE
`renderOnlyVisible` option not working on documentation demo page.

### ISSUE THREAD

**Issue by remyhunt** [naver/egjs-flicking#869]
## Description

Attempted to set the `renderOnlyVisible` option in my Vue3 app, and it didn't work.

I noticed this isn't working on the documentation page - suggesting that this might be a cross-platform issue! 

[https://naver.github.io/egjs-flicking/Options](https://naver.github.io/egjs-flicking/Options)
<img width="970" alt="Screenshot 2024-06-24 at 3 18 12 PM" src="https://github.com/naver/egjs-flicking/assets/5217127/d335f177-c4bf-47f6-88c2-761132bb31b7">

**Comment by malangfox** [comment]
Hello @remyhunt.

When we checked the documentation page, we saw that `renderOnlyVisible` only renders the two Panels that fit inside the screen.

![image](https://github.com/naver/egjs-flicking/assets/13797320/ed651755-df2b-46b0-80d5-e2150e62c8f7)


This seems to be different than Flicking above without the option applied, which renders 5 Panels, and we would like to check if there's something different if the demo works wrong in your environment.

Could you let us know how many Panels in the bottom Flicking renders in the developer tools in your environment?

**Comment by remyhunt** [comment]
thanks for getting back to me @malangfox  - I had a misunderstanding of this option. 

My expectation was that it was intended to change the behavior of the slider to instantaneously change, rather than use a slide animation. How embarrassing for me, but I appreciate your help!
