### ISSUE TITLE
이미지가 있는 곳에서 스크롤 하는 경우 스크롤이 잘 안되요.

### ISSUE THREAD

**Issue by jexists** [naver/egjs-flicking#871]
이미지가 있는 부분을 스크롤할 경우는 안되는데 margin한 부분에서 스크롤할경우에는 잘됩니다. 

폰으로 스크롤할 경우에는 상관이 없는데 pc에서 스크롤 할 경우 잘 안되네요.

**Comment by malangfox** [comment]
안녕하세요 @jexists 님.

플리킹 내부의 이미지가 존재하는 부분을 스크롤할 때 플리킹이 멈춘다면, [preventDefaultOnDrag ](https://naver.github.io/egjs-flicking/ko/Options#preventdefaultondrag)옵션을 사용해볼 수 있겠습니다.
위 옵션을 적용해본 뒤 동작을 비교해볼 수 있을까요?

**Comment by jexists** [comment]
해결되었습니다 감사합니다 :)
