### ISSUE TITLE
A bug occurs when executing`resize` method bug in IE9

### ISSUE THREAD

**Issue by daybrush** [naver/egjs-flicking#92]
## Description

A bug occurs when execute 'resize' method bug in IE9

<img width="432" alt="2018-03-06 1 02 42" src="https://user-images.githubusercontent.com/3433062/37013689-b43f8ea2-213e-11e8-8ae8-7c7031f1734b.png">

when resize in a browser that does not support transform, left or top of the panels will not change.

**Comment by netil** [comment]
Hi @younkue, basically support for IE starts from 10 and above.
- https://github.com/naver/egjs-flicking#supported-browsers

**Comment by younkue** [comment]
Hi @netil
Flicking uses left, top properties for browsers that do not support transform.
When resize in a browser that does not support transform, left, top should be adjusted.

**Comment by netil** [comment]
for left/top styling changes are for environment like old Android devices.
It can be updated to support old IEs, but "official" support and adjusting supports are different.

This issue can be reviewed in the future, but there's no future plan to support "officially".
