### ISSUE TITLE
If call disableInput while holding it with touch, methods don't work.

### ISSUE THREAD

**Issue by daybrush** [naver/egjs-flicking#93]
## Description

If call 'disableInput' method while holding it with touch, mehotds like prev, next, moveTo, ... don't work.

```js
flicking._conf.touch.holding
```

**Comment by netil** [comment]
Could you give a real use case for that?
I can't get why needs or how to be called `.disableInput()` while holding.

**Comment by younkue** [comment]
I used PinchInput of Axes in Flicking. When zooming with PinchInput, I used`.disableinpt()` to prevent PanInput from going to the next panel.
