### ISSUE TITLE
Supporting esModuleInterop option in TypeScript

### ISSUE THREAD

**Issue by JaeYeopHan** [naver/egjs-flicking#94]
## Description
in `flicking.d.ts`
```ts
import * as Component from "@egjs/component";
```
Currently, we use `esModuleInterop: true` of ts-compiler option in TypeScript 2.7.x version. That is, the current version and way of importing module is not appropriate.

How about supporting ES6 module like [@egjs/axes](https://github.com/naver/egjs-axes)?

ref>> https://github.com/naver/egjs-component/issues/32

**Comment by netil** [comment]
Thanks @JaeYeopHan for the suggestion.
IMO, not only the definition should be updated, there're `imports` on source also.

Callable CommonJS modules will be updated to be imported as default imports.
- Ref: https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability
