### ISSUE TITLE
can't reference FlickingStatus interface

### ISSUE THREAD

**Issue by vreality64** [naver/egjs-flicking#98]
## Description

I'm using `TypeScript@2.7` and `eg.flicking@2.2`

currently `getStatus` function returns interface `string | FlickingStatus`.
If I want to reference status as FlickingStatus, I have to cast that like `status as FlickingStatus` or just reference them like below screenshot.

but actually none of that possible.

`FlickingStatus` is not exported and referencing status recognized as string.

|                           casting                            |
| :----------------------------------------------------------: |
| ![image](https://user-images.githubusercontent.com/886706/38223976-b6f32d02-3728-11e8-9e4b-a7ea0e3f0be4.png) |
|                    **direct referencing**                    |
| ![image](https://user-images.githubusercontent.com/886706/38223837-0539661c-3728-11e8-988e-67ec715e27f4.png) |

**Comment by netil** [comment]
Status will return as:
![image](https://user-images.githubusercontent.com/2178435/38609419-fa595008-3db8-11e8-9b69-43a4b1200f23.png)
